### ISSUE TITLE
`first-published-tag-for-merged-pr` doesn't work on some PRs

### ISSUE THREAD

**Issue by Abirdcfly** [refined-github/refined-github#5911] opened 2022-08-15 01:46 UTC
### Description

For example:
https://github.com/kubernetes/kubernetes/pull/110757 has merged into tag [v1.23.9](https://github.com/kubernetes/kubernetes/commit/2eed3eb9177536fe4012b715fcfc41b9c1d602c8)  but show `This pull request has not yet appeared in a release`

### How to replicate the issue

I've only found it on non-master or main branches so far.

### Extension version

22.8.8

### Browser(s) used

Chrome

**Comment by fregante** [comment] 2022-08-15 04:36
The feature is somewhat right, the merged commit does not appear in any tag. We use GitHub’s own interface to determine that and they say the same thing:

- https://github.com/kubernetes/kubernetes/commit/b85c292c307df31d279dd40f8bb2d546d98f1e05

You can see that only the branch appears there, not the tag:

<img width="332" alt="Screen Shot" src="https://user-images.githubusercontent.com/1402241/184577143-41ce06dd-aefd-4312-8208-61c769201bd9.png">


The whole "git strategy" of the repo is incompatible with how GitHub deals with git, which is confirmed by other snippets found on the repo, like on:

- https://github.com/kubernetes/kubernetes/releases/tag/v1.23.9

Obviously "4741 commits since this release" isn't right, but that's how git works, and the repo is fighting against it:


<img width="647" alt="Screen Shot" src="https://user-images.githubusercontent.com/1402241/184577253-135bdcce-2895-4d06-a315-528cbbb0ce68.png">


---


We can update the message to be more exact, like "The merge commit doesn't appear in any tags", similar to how it was before [my last change](https://github.com/refined-github/refined-github/commit/409d93c5b2a70a31245cd09673b10355462d06a7#diff-b961b80b3482549c5b5b567d504d06b30642c2bb3daf0adb3be39f95cfe2248dL39)

**Comment by fregante** [comment] 2022-08-15 04:37
The only thing we can do would be to message to be more exact, like "The merge commit doesn't appear in any tags", similar to how it was before [my last change](https://github.com/refined-github/refined-github/commit/409d93c5b2a70a31245cd09673b10355462d06a7#diff-b961b80b3482549c5b5b567d504d06b30642c2bb3daf0adb3be39f95cfe2248dL39)

**Closed** 2022-09-16 08:02 UTC
Labels: bug, help wanted, good first issue
