### ISSUE TITLE
Inconsistent first commit date according to GitHub

### ISSUE THREAD

**Issue by Dentrax** [refined-github/refined-github#5306] opened 2022-01-14 14:46 UTC
### Please ensure:

- [X] The bug is caused by Refined GitHub. It doesn't happen if I disable the extension.

### Example URLs

https://github.com/containers/youki

### Browser(s) used

Firefox 95

### Description

Both commits indicate: `a08887d59a8c5a9bc19761320c4eb2832dd6ad8f`

![Screen Shot 2022-01-14 at 17 44 28](https://user-images.githubusercontent.com/16493751/149534107-7194cb80-20df-4759-844c-d723ffcda4dc.png)

RGH: `22.1.11`

### Include in this issue:

- [ ] Screenshots/video/gif demonstrating the bug, if it’s visual
- [ ] Console errors, if any

**Comment by cheap-glitch** [comment] 2022-01-14 14:50
Duplicate of #4620

**Closed** 2022-01-14 14:53 UTC
Labels: bug
