### ISSUE TITLE
Prevent a tab from being closed/location changed, if there's not-yet-posted content on it (i.e. unsaved work)

### ISSUE THREAD

**Issue by pradyunsg** [refined-github/refined-github#5783] opened 2022-07-05 20:38 UTC
### Description

First off, thank you for maintaining this! This genuinely makes my life as an OSS maintainer easier! ✨❤️ 

---

Picture this: You've started responding to an issue/discussion, that requires you to write down a lot of stuff in a comment -- it's a code review and we're discussing the design feature, or it's a feature request and we're fleshing out whether it's feasible and what the challenges might be, or it's a governance discussion. Something that requires a bunch of time and effort to write down that comment.

And, you accidentally click a link that'll open in the same tab. Now, typically, the browser remembers exactly what I've written. Other times, you've just lost 30 minutes of writing because you accidentally clicked instead of control-clicked a link that you had in your post. Or maybe, you might end up closing this tab because you actually had a bunch of tabs open and were cleaning up the open tabs that you have.

Wouldn't it be great, if something protected you from your own carelessness, and used the "you have unsaved changes" prompt from the browser, to prevent you from accidentally moving away while you have an not-yet-posted content on page? Well, that's this feature request. :)

### Example URLs

Any GitHub page that lets you write a content in a text box, so... like... this issue?

**Comment by pradyunsg** [comment] 2022-07-05 20:41
This is somewhat related to https://github.com/refined-github/refined-github/issues/5680

**Comment by fregante** [comment] 2022-08-05 09:18
Duplicate of https://github.com/refined-github/refined-github/issues/1037

Unfortunately we can't prevent ajax navigation, so that kills half of the feature.

Also see:

- https://github.com/refined-github/refined-github/issues/1598
- `unfinished-comments`

**Closed by fregante** 2022-08-05 09:18 UTC
Labels: enhancement, under discussion
