### ISSUE TITLE
Select/unselect all features

### ISSUE THREAD

**Issue by ibrahima** [refined-github/refined-github#5760] opened 2022-06-30 23:21 UTC
### Description

Hi! Refined GitHub is pretty cool and has a lot of features. But it does have a performance impact, and I'd really like to limit the impact by selectively enabling features rather than having them all enabled and opting out of features I don't want. Would it be possible to add a "select all"/"unselect all" button so that we could do this more easily? Thanks!

### Example URLs

https://github.com/refined-github/refined-github

**Comment by fregante** [comment] 2022-07-01 11:04
Duplicate of https://github.com/refined-github/refined-github/issues/3535

**Comment by fregante** [comment] 2022-07-01 11:04
Duplicate of https://github.com/refined-github/refined-github/issues/2684

**Comment by amithm7** [comment] 2022-12-12 21:02
Also, an option to disable new features by default would be nice.

**Closed** 2023-09-27 11:01 UTC
Labels: help wanted, meta, under discussion
