### ISSUE TITLE
Hide Copilot widget on dashboard

### ISSUE THREAD

**Issue by Leo40Git** [refined-github/refined-github#8177] opened 2024-12-27 10:22 UTC
### Description

See title. This is easy enough to do with any adblocker addon (just block all elements with ID `copilot-dashboard-entrypoint`), but it'd be nice to have integrated into this addon.

<details>
<summary>Mockup:</summary>
Before:

![image](https://github.com/user-attachments/assets/d27766a1-a000-497e-90c8-734b78eff47f)
After:

![image](https://github.com/user-attachments/assets/427c7410-8ccc-4939-a21d-4e022ade6dc0)
</details>

### Example URLs

https://github.com

**Comment by fregante** [comment] 2024-12-27 10:48
Duplicate of #8168 #8124 #8004 #8173

**Closed by fregante** 2024-12-27 10:48 UTC
Labels: enhancement, under discussion
