### ISSUE TITLE
`highlight-collaborators-and-own-conversations` bad wrapping

### ISSUE THREAD

**Issue by mathomp4** [refined-github/refined-github#7360] opened 2024-05-13 19:29 UTC
### Description

I'm loving this extension, but I'm seeing an oddity on one of my repos. Here is an example screenshot:

<img width="982" alt="Screenshot 2024-05-13 at 3 23 28 PM" src="https://github.com/refined-github/refined-github/assets/2982494/034e8f8b-5ad5-4b02-9f07-f27a1f5b7108">

For some PRs, the nice "user oval" thing is split into two lines. I clicked the "Find feature" button and it said:

> "The change or issue is caused by warning-for-disallow-edits."

but when I disabled that, it didn't change anything. So I'm at a loss. 

### How to replicate the issue + URL

I see this issue at this URL:

https://github.com/GEOS-ESM/MAPL/pulls?q=is%3Apr+sort%3Aupdated-desc+is%3Aopen

but, interestingly, not at the "generic" PR URL:

https://github.com/GEOS-ESM/MAPL/pulls

So perhaps it's being caused by the extra bits at the end there?

### Extension version

24.4.9

### Browser(s) used

Chrome 124.0.6367.202 Arm64 macOS

**Comment by fregante** [comment] 2024-05-14 00:13
This is most likely caused by the added branch to the right. I forgot the name of the feature. Technically it's GitHub's poor layout setup for the PR line that's causing this bad wrapping. We can't try to fix it because we're then *more* likely to introduce bugs down the line.

**Comment by fregante** [comment] 2024-05-14 01:21
I think this specific issue can be fixed by avoiding the wrap inside the bubble, even if it might push the issue elsewhere 👍

**Comment by mathomp4** [comment] 2024-05-14 13:06
Ahh. Okay. That would be `highlight-non-default-base-branch`. And if I turn that off, the oval is no longer split. I do like that (since pretty much *all* the PRs in that repo are to non-default branches), but not crucial.

Ah well.

**Closed** 2024-06-02 11:50 UTC
Labels: bug, help wanted, small
