### ISSUE TITLE
Way to filter GitHub Actions tests by result state

### ISSUE THREAD

**Issue by janpio** [refined-github/refined-github#5621] opened 2022-05-05 15:24 UTC
### Description

It would be nice to be able to filter the GH Actions workflow results by the state. We have _many_ tests in our workflows, so when GitHub says "144 successful, 2 skipped, 9 queued, and 1 failing checks" it takes quite a bit of scrolling to get to the failing test:

<img width="689" alt="image" src="https://user-images.githubusercontent.com/183673/166957095-d71d4e90-2636-433a-9212-e5e0c982e1dd.png">

It could be nice to have a way to filter down the tests by their state, only showing the "failed" ones for example.

### Example URL

https://github.com/prisma/ecosystem-tests/pull/2695#partial-pull-merging

**Comment by cheap-glitch** [comment] 2022-05-05 15:27
Related:
- https://github.com/refined-github/refined-github/issues/3136
- https://github.com/refined-github/refined-github/issues/4958

**Comment by janpio** [comment] 2022-05-05 16:30
Sorting by state (failed first, then succeeded) might actually also be an interesting way that does not need interaction. (#3136 mentions sorting by workflow, which the checks are not for some reason 🤷 )

**Comment by fregante** [comment] 2022-05-05 22:34
Duplicate of https://github.com/refined-github/refined-github/issues/5062

**Closed by fregante** 2022-05-05 22:35 UTC
Labels: enhancement, under discussion
