### ISSUE TITLE
Missing gap between pull request title and build status

### ISSUE THREAD

**Issue by scrlkx** [refined-github/refined-github#7443] opened 2024-06-13 20:13 UTC
### Description

In the /pulls page of any repository there is a missing gap between the pull request title and the build status.

Refined GitHub disabled:
![image](https://github.com/refined-github/refined-github/assets/22862212/5845a1c9-4f15-42cf-9270-7a50249738f4)

Refined GitHub  enabled:
![image](https://github.com/refined-github/refined-github/assets/22862212/8191fa92-6c10-44c0-88bc-b65d789728ab)

More closely:
![image](https://github.com/refined-github/refined-github/assets/22862212/3fd368cf-bf2f-4424-b979-9c4923ffadef)

### How to replicate the issue + URL

It happens on Refined GitHub pull requests page.

https://github.com/refined-github/refined-github/pulls?q=is%3Apr+is%3Aopen+sort%3Aupdated-desc

### Extension version

24.6.9

### Browser(s) used

Mozilla Firefox version 126.0.1

**Comment by fregante** [comment] 2024-06-14 00:05
Duplicate of https://github.com/refined-github/refined-github/issues/7398

**Closed** 2024-06-14 00:04 UTC
Labels: bug
