### ISSUE TITLE
`release-download-count` not working anymore in `releases` page

### ISSUE THREAD

**Issue by lucacome** [refined-github/refined-github#5162] opened 2021-12-09 23:03 UTC
### Please ensure:

- [X] The bug is caused by Refined GitHub. It doesn't happen if I disable the extension.

### Include in this issue:

- [x] Screenshots/video/gif demonstrating the bug, if it’s visual
- [ ] Console errors, if any

### Description

I used to be able to see the number of downloads for each asset attached to a release, in the `releases` page. This doesn't work anymore, I'm assuming because of the new release page format.

The number is still shown when opening a specific release.

### Example URL

https://github.com/nginxinc/nginx-prometheus-exporter/releases

### Browser(s) used

Chrome

**Comment by lucacome** [comment] 2021-12-09 23:06
Releases page [nginxinc/nginx-prometheus-exporter/releases](https://github.com/nginxinc/nginx-prometheus-exporter/releases)
![image](https://user-images.githubusercontent.com/603885/145489624-222ec568-8e13-4cf8-ac30-7ddcab071c0a.png)
Single release https://github.com/nginxinc/nginx-prometheus-exporter/releases/tag/v0.9.0
![image](https://user-images.githubusercontent.com/603885/145489664-6837895c-2577-40c4-aaf1-d6d7dac94112.png)

**Comment by yakov116** [comment] 2021-12-09 23:18
Duplicate of https://github.com/refined-github/refined-github/issues/5147

Will be fixed in the next release

**Closed by yakov116** 2021-12-09 23:18 UTC
Labels: bug

**Comment by lucacome** [comment] 2021-12-09 23:22
Sorry about that! I didn't think about searching in the closed issues, thanks!

**Comment by yakov116** [comment] 2021-12-10 00:10
Np 

Thanks for reporting
