### ISSUE TITLE
'Preview' option does but update when changing files.

### ISSUE THREAD

**Issue by RedYetiDev** [refined-github/refined-github#7329] opened 2024-04-05 12:29 UTC
### Description

When changing files via the sidebar, the 'Preview' button does not update based on the currently viewed file.

### How to replicate the issue + URL

1. Visit <https://github.com/refined-github/refined-github/blob/main/source/options.html>
	> Verify the 'Preview' button is there, and if not, reload
2. Use the sidebar to navigate to any other file
3. Notice that the 'Preview' button remains linked to the `options.html` file.

### Extension version

24.4.1

### Browser(s) used

Google Chrome 123.0.6312.86 (Official Build) (64-bit)

**Comment by fregante** [comment] 2024-04-05 14:17
Duplicate of https://github.com/refined-github/refined-github/issues/6554

**Comment by fregante** [comment] 2024-04-05 14:17
Yes unfortunately it's:

- https://github.com/refined-github/refined-github/issues/6554

**Closed by fregante** 2024-04-05 14:17 UTC
Labels: bug
