### ISSUE TITLE
Wrong number of issues listed

### ISSUE THREAD

**Issue by LilithHafner** [refined-github/refined-github#6826] opened 2023-08-14 16:21 UTC
### Description

The number of issues listed is 21, but the currect number is 117. There are 21 bugs and 117 issues, but somehow the number of bugs slipped into the header of the issue tab.

<img width="1096" alt="Screenshot 2023-08-14 at 11 17 48 AM" src="https://github.com/refined-github/refined-github/assets/60898866/de30759e-3f6a-4dfc-bf8e-3953e1bb84e6">

### How to replicate the issue + URL

I saw this on https://github.com/refined-github/refined-github/issues/6822, but I'm not sure what the exact reproduction steps are.

### Extension version

23.8.3

### Browser(s) used

Chrome

**Comment by fregante** [comment] 2023-08-14 21:34
Duplicate of https://github.com/refined-github/refined-github/issues/6469

**Closed by fregante** 2023-08-14 21:34 UTC
Labels: bug
