### ISSUE TITLE
`ci-link`: Cannot read properties of undefined (reading 'parentElement')

### ISSUE THREAD

**Issue by AdamRaichu** [refined-github/refined-github#6562] opened 2023-04-25 12:50 UTC
### Description

```
TypeError: Cannot read properties of undefined (reading 'parentElement')
    at init (chrome-extension://hlepfoohegkhhmjieoechaddaejaokhf/refined-github.js:6375:65)
    at async runFeature (chrome-extension://hlepfoohegkhhmjieoechaddaejaokhf/refined-github.js:3718:20)
    at async setupPageLoad (chrome-extension://hlepfoohegkhhmjieoechaddaejaokhf/refined-github.js:3724:34)
```

### How to replicate the issue + URL

https://github.com/JannisX11/snowstorm/graphs/contributors

### Extension version

23.4.15

### Browser(s) used

Chrome

**Comment by fregante** [comment] 2023-04-25 14:07
Duplicate of https://github.com/refined-github/refined-github/issues/6454

**Closed** 2023-04-25 14:07 UTC
Labels: bug
