### ISSUE TITLE
Approvals can't be made in PR.

### ISSUE THREAD

**Issue by NetLSS** [refined-github/refined-github#6634] opened 2023-05-09 00:55 UTC
### Description

![image](https://user-images.githubusercontent.com/38928282/236967021-a2156c29-fce1-4926-ab1d-b0f75de9537e.png)

Approvals can't be made in PR.

Pressing the approve button does nothing.

### How to replicate the issue + URL

private repo

### Extension version

23.5.6

### Browser(s) used

Brave Browser (v1.51.110)

**Comment by hyeonjae** [comment] 2023-05-09 03:01
I have the same problem.

**Comment by fregante** [comment] 2023-05-09 06:20
Duplicate of #6633

**Closed by fregante** 2023-05-09 06:20 UTC
Labels: bug

**Comment by fregante** [comment] 2023-05-09 06:24
You're both on GitHub Enterprise, correct?

**Comment by NetLSS** [comment] 2023-05-09 10:03
> You're both on GitHub Enterprise, correct?

Yes, that's right
