### ISSUE TITLE
Auto-hide pull request changes on creation

### ISSUE THREAD

**Issue by 3kh0** [refined-github/refined-github#6157] opened 2022-11-13 02:05 UTC
### Description

So I was making a new pull and this was quite the big change, so when I went to make it, it took a long time to load, because it was also displaying all of the changes you did, similar to the file review window. But for me I do not need this, while so do, so I have an idea, to make it so it automatically starts out collapsed and if you want to see it, you just click it and it would expand

### Screenshot

I suck at Photoshop, but this would work just like the feature where you can go a repo front page, and collapse the file directory.

collapsed

![image](https://user-images.githubusercontent.com/58097612/201501989-991f771c-fc72-473c-81e8-990e96ef067c.png)

not collapsed

![2022_11_12_0z2_Kleki](https://user-images.githubusercontent.com/58097612/201502016-421b6843-ff20-4164-926b-50d24abd444d.png)

use your imagination on this one 😉

### Example URLs

https://github.com/3kh0/3kh0.github.io/compare/main...revert-279-json-update

after you hit create pull request

![2022_11_12_0z5_Kleki](https://user-images.githubusercontent.com/58097612/201502083-5c84cb66-47a0-44ad-9ad2-dc6ed7a82cc7.png)

**Comment by fregante** [comment] 2022-12-03 10:13
I'm not sure what the problem is exactly because GitHub already hides the diff on large compare pages, it only shows the commits. https://github.com/refined-github/refined-github/issues/5440 even asks to do the opposite. Closing for now

**Closed by fregante** 2022-12-03 10:13 UTC
Labels: enhancement, under discussion
