### ISSUE TITLE
Quickly copy review comment filename to clipboard

### ISSUE THREAD

**Issue by pgimalac** [refined-github/refined-github#7190] opened 2023-12-28 23:02 UTC
### Description

When doing a review, Github has a convenient button to quickly copy a filename to the clipboard.

When looking at review comments, there is no such button, while I often need to copy the filename to open it in my IDE (to see the lines around the comment and/or fix it).

Furthermore, a left click on the filename to copy the text collapses the comment, which is usually not what I want to do.

Having the quick copy to clipboard button like when doing a review would be very convenient.

<table>
<tr>
 <td> Files tab
 <td> Conversations tab (original)
 <td> Conversations tab (expected)
<tr>
 <td> <img width="415" alt="image" src="https://github.com/refined-github/refined-github/assets/23154723/aa78272e-3857-4ebd-8eee-3890c82404df">
 <td> 
<img width="442" alt="image" src="https://github.com/refined-github/refined-github/assets/23154723/7c054ec8-13d9-4278-bbf4-642d72b158ce">
 <td> 
<img width="442" alt="image" src="https://github.com/refined-github/refined-github/assets/23154723/1765771d-f32f-45af-9224-db293734a38b">
</table>

If you think this can be part of this project I can implement it.

### Example URLs

https://github.com/refined-github/sandbox/pull/10

**Comment by fregante** [comment] 2023-12-29 00:59
Duplicate of https://github.com/refined-github/refined-github/issues/6398

**Closed by fregante** 2023-12-29 00:59 UTC
Labels: enhancement, under discussion

**Comment by pgimalac** [comment] 2023-12-29 10:12
You are right they are duplicates, my bad.
I guess I'll just use a userscript.
