### ISSUE TITLE
Issue's project not displayed

### ISSUE THREAD

**Issue by Zenoo** [refined-github/refined-github#5774] opened 2022-07-04 10:57 UTC
### Please ensure:

- [X] The bug is caused by Refined GitHub. It doesn't happen if I disable the extension.
- [X] The bug happens after clearing extension cache. The "Clear cache" button below can also be found at the bottom of the options page.

### Example URLs

https://github.com/HemantNegi/jquery.sumoselect/issues/329

### Extension version

22.7.1

### Browser(s) used

Chrome Version 103.0.5060.66 (Official Build) (64-bit)

### Description

The projects tab doesn't show the selected project in an issue.

Without Refined Github:

![](https://i.imgur.com/PA7RQuY.png)

With Refined Github

![](https://i.imgur.com/bOhxMif.png)

### Include in this issue:

- [X] Screenshots/video/gif demonstrating the bug, if it’s visual
- [ ] Console errors, if any

**Comment by fregante** [comment] 2022-07-04 11:37
Duplicate of https://github.com/refined-github/refined-github/issues/5757

**Closed by fregante** 2022-07-04 11:37 UTC
Labels: bug
