### ISSUE TITLE
Make "hide events and collapsed comments" the default

### ISSUE THREAD

**Issue by sionescu** [refined-github/refined-github#6540] opened 2023-04-18 01:26 UTC
### Description

On a PR conversation page, I'd like to be able hide all events and collapsed comments by default. I'm working on a (private) repo with tons of CI/CD activity and those events are mostly useless clutter.
Additionally, I'd like to be able to hide comments from bots (like the "github-actions" bot) as well.

### Example URLs

Not public.

**Comment by fregante** [comment] 2023-04-18 02:13
Duplicate of https://github.com/refined-github/refined-github/issues/4750

**Closed by fregante** 2023-04-18 02:13 UTC
Labels: enhancement, under discussion

**Comment by sionescu** [comment] 2023-04-18 16:11
Can it be made configurable ? If not, why not ? Perhaps some people want to always see all events, but I always want to hide them all. I can't think of a single event that's useful to be displayed by default.

**Comment by fregante** [comment] 2023-04-18 16:18
We don't add options:

- https://github.com/refined-github/refined-github/wiki/%22Can-you-add-this-feature%3F%22#3-it-doesnt-require-options

I have two good news:

- there's a keyboard shortcut (I think it's `i`?)
- you could write a userscript to automatically click dropdown on load
