### ISSUE TITLE
Ability to add a line length ruler

### ISSUE THREAD

**Issue by bsrz** [refined-github/refined-github#6434] opened 2023-03-27 16:59 UTC
### Description

See title, also see image:
![](https://user-images.githubusercontent.com/1077441/228012551-c7764978-1cb6-4e33-ad47-8562f7296134.png)

### Example URLs

All code files view

**Comment by fregante** [comment] 2023-03-27 17:15
Duplicate of https://github.com/refined-github/refined-github/issues/1484

**Closed by fregante** 2023-03-27 17:15 UTC
Labels: enhancement, under discussion

**Comment by bsrz** [comment] 2023-03-28 14:28
Sadly, that solution doesn't work. Perhaps it's caused by the GitHub dark theme.
A nice clean line would be much better than an overly subtle gradient, that I have to manually add through custom CSS.
