### ISSUE TITLE
Performance issue opening and filtering label list

### ISSUE THREAD

**Issue by SkySkimmer** [refined-github/refined-github#7207] opened 2024-01-09 14:18 UTC
### Description

When opening or filtering the label list in a PR or issue on https://github.com/coq/coq (repo has 144 labels) firefox hangs for single digit seconds with 1 CPU at 100%.

The "identify feature" tool points to `locked-issue` which makes no sense since it's disabled (https://github.com/refined-github/refined-github/issues/7116).

### How to replicate the issue + URL

I guess you need a repository with lots of labels where you have label setting rights (to get the label dropdown) to reproduce.

### Extension version

23.12.17

### Browser(s) used

firefox 121.0 (linux, debian testing)

**Comment by fregante** [comment] 2024-01-09 14:30
Duplicate of https://github.com/refined-github/refined-github/issues/7176

**Closed by fregante** 2024-01-09 14:30 UTC
Labels: bug
