### ISSUE TITLE
Upload to Microsoft Edge Store

### ISSUE THREAD

**Issue by QuarticCat** [refined-github/refined-github#6362] opened 2023-02-19 11:33 UTC
Although MS Edge can add extensions downloaded from the Chrome store, these extensions will not be synced. It would be better if you can upload this extension to the Edge store as well.

**Comment by fregante** [comment] 2023-02-19 11:36
Duplicate of https://github.com/refined-github/refined-github/issues/1914


> these extensions will not be synced

What kind of sync are you referring to?

**Closed** 2023-02-19 11:36 UTC
Labels: under discussion

**Comment by QuarticCat** [comment] 2023-02-19 11:50
@fregante  I mean this: https://support.microsoft.com/en-us/microsoft-edge/why-are-some-of-my-extensions-missing-on-the-new-microsoft-edge-2cb5d2e3-72ce-0019-3fbf-ae4efd414d3a

> However, only extensions found in the new [Microsoft Edge add-ons website](https://microsoftedge.microsoft.com/addons/) can be imported.

**Comment by fregante** [comment] 2023-02-19 12:03
That's not "syncing", that page is about the user moving from Chrome to Edge. While nice, it takes little to re-install it from the Chrome Web Store as suggested on that page.

**Comment by QuarticCat** [comment] 2023-02-19 12:14
Oh, I'm sorry. Some of my extensions were not synced and I met this problem twice. I hurried to open a top search result but didn't read it carefully. My apologies. This problem might be caused by other factors.
