### ISSUE TITLE
`clean-dashboard` doesn't work with consecutive events

### ISSUE THREAD

**Issue by kidonng** [refined-github/refined-github#4778] opened 2021-09-10 15:50 UTC
### Please ensure:

- [X] The bug is caused by Refined GitHub. It doesn't happen if I disable the extension.

### Description

When a user created multiple repositories, the events are shown like this in the dashboard:

<img width="696" alt="Screen Shot 2021-09-10 at 23 36 27" src="https://user-images.githubusercontent.com/44045911/132881556-fbdea7ba-dfa6-44d3-a274-32358cc6c411.png">

Expanded:

<img width="693" alt="Screen Shot 2021-09-10 at 23 36 32" src="https://user-images.githubusercontent.com/44045911/132881631-114c30ab-2742-4127-8a3d-f8b53a5169b5.png">

With Refined GitHub:

<img width="686" alt="Screen Shot 2021-09-10 at 23 36 43" src="https://user-images.githubusercontent.com/44045911/132881667-1bfe6e73-dd8c-4eda-a499-687f54b19cef.png">

### Example URL

https://github.com/

### Browser(s) used

Chrome

**Comment by kidonng** [comment] 2022-03-05 14:50
What this bug looks like now:
<img width="660" alt="Screen Shot 2022-01-31 at 23 25 37" src="https://user-images.githubusercontent.com/44045911/156888446-e7448b5c-59a8-415e-b3ff-234110365f8a.png">

And it's not only about repo creation but other events as well (I remember we fixed a padding issue before?)

<img width="664" alt="Screen Shot 2022-01-31 at 23 26 30" src="https://user-images.githubusercontent.com/44045911/156888451-5bbeb1d5-a862-48ab-ac02-a5101059996a.png">

**Comment by fregante** [comment] 2022-03-05 16:25
hmmm it works well for me, I'm not seeing any follow events nor any star/unstar buttons

<img width="502" alt="Screen Shot 2" src="https://user-images.githubusercontent.com/1402241/156891768-a2c166a6-ac12-408d-9d06-d38db84e6786.png">

**Comment by fregante** [comment] 2022-03-05 16:29
Duplicate of https://github.com/refined-github/refined-github/issues/4760

**Closed** 2022-03-05 16:31 UTC
Labels: bug, help wanted
