### ISSUE TITLE
PR Reviewer Templates

### ISSUE THREAD

**Issue by josh-bouganim-avant** [refined-github/refined-github#6539] opened 2023-04-18 00:17 UTC
### Description

Currently, Github supports [Pull Request templates ](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/creating-a-pull-request-template-for-your-repository) but does not support a template for the PR Review.  

We would like to create a template with a checklist for the PR Reviewer to make sure that they are checking/reviewing everything they are supposed to be looking at.  This template would follow similar logic as the PR template but be named `pull_request_reviewer_template.md` instead.

Example:

![image](https://user-images.githubusercontent.com/97702138/232637208-5e7e4669-faef-4c82-a6d8-3d9229a8b7f2.png)

Thanks for your consideration!

### Example URLs

https://github.com/refined-github/refined-github/pull/6538/files

**Comment by busches** [comment] 2023-04-18 00:32
Did you submit this feedback to GH? Seems too niche/complicated for RGH IMO.

**Comment by fregante** [comment] 2023-04-18 02:09
Duplicate of https://github.com/refined-github/refined-github/issues/1621

**Closed by fregante** 2023-04-18 02:09 UTC
Labels: enhancement, under discussion
