### ISSUE TITLE
Show author icon (profile pic) in PR list page

### ISSUE THREAD

**Issue by ChillarAnand** [refined-github/refined-github#6491] opened 2023-04-10 12:49 UTC
### Description

Instead of showing name, showing profile pic will be much better to get the information at a glance.

### Example URLs

https://github.com/ChillarAnand/avilpage.com/pulls?q=is%3Apr+sort%3Aupdated-desc+is%3Aclosed

**Comment by fregante** [comment] 2023-04-10 12:56
Duplicate of https://github.com/refined-github/refined-github/issues/4906

**Closed by fregante** 2023-04-10 12:56 UTC
Labels: enhancement, under discussion
