### ISSUE TITLE
`clean-repo-sidebar`: Cannot read properties of undefined (reading 'parentElement')

### ISSUE THREAD

**Issue by whoami15** [refined-github/refined-github#6668] opened 2023-05-20 03:48 UTC
### Description

The error is showing on any repo, e.g. visit the repository below and open the console.

https://github.com/whoami15/tasty-bites

```
 ❌ clean-repo-sidebar
 📕 23.5.10 → TypeError: Cannot read properties of undefined (reading 'parentElement')
    at moveReportLink (chrome-extension://hlepfoohegkhhmjieoechaddaejaokhf/refined-github.js:5789:90)
    at async Promise.all (index 4)
    at async init (chrome-extension://hlepfoohegkhhmjieoechaddaejaokhf/refined-github.js:5797:9)
    at async runFeature (chrome-extension://hlepfoohegkhhmjieoechaddaejaokhf/refined-github.js:4286:20)
    at async setupPageLoad (chrome-extension://hlepfoohegkhhmjieoechaddaejaokhf/refined-github.js:4293:37)
 🔍 Search issue https://github.com/refined-github/refined-github/issues?q=is%3Aissue+is%3Aopen+label%3Abug+clean-repo-sidebar
 🚨 Report issue https://github.com/refined-github/refined-github/issues/new?template=1_bug_report.yml&title=%60clean-repo-sidebar%60%3A+Cannot+read+properties+of+undefined+%28reading+%27parentElement%27%29&repro=https%3A%2F%2Fgithub.com%2Fwhoami15%2Ftasty-bites&description=%60%60%60%0ATypeError%3A+Cannot+read+properties+of+undefined+%28reading+%27parentElement%27%29%0A++++at+moveReportLink+%28chrome-extension%3A%2F%2Fhlepfoohegkhhmjieoechaddaejaokhf%2Frefined-github.js%3A5789%3A90%29%0A++++at+async+Promise.all+%28index+4%29%0A++++at+async+init+%28chrome-extension%3A%2F%2Fhlepfoohegkhhmjieoechaddaejaokhf%2Frefined-github.js%3A5797%3A9%29%0A++++at+async+runFeature+%28chrome-extension%3A%2F%2Fhlepfoohegkhhmjieoechaddaejaokhf%2Frefined-github.js%3A4286%3A20%29%0A++++at+async+setupPageLoad+%28chrome-extension%3A%2F%2Fhlepfoohegkhhmjieoechaddaejaokhf%2Frefined-github.js%3A4293%3A37%29%0A%60%60%60
```

![image](https://github.com/refined-github/refined-github/assets/16274153/05b6b315-2609-40d0-8706-c76fc553c81c)

### How to replicate the issue + URL

https://github.com/whoami15/tasty-bites

### Extension version

23.5.10

### Browser(s) used

Google Chrome Version 113.0.5672.94 (Official Build) (64-bit)

**Comment by fregante** [comment] 2023-05-20 04:07
Duplicate of https://github.com/refined-github/refined-github/issues/6569

**Closed by fregante** 2023-05-20 04:07 UTC
Labels: bug
