### ISSUE TITLE
Double-scroll areas after expanding all lines

### ISSUE THREAD

**Issue by samholmes** [refined-github/refined-github#5468] opened 2022-03-07 20:27 UTC
### Please ensure:

- [X] The bug is caused by Refined GitHub. It doesn't happen if I disable the extension.
- [X] The bug happens after clearing extension cache. The "Clear cache" button below can also be found at the bottom of the options page.

### Example URLs

https://github.com/refined-github/refined-github/pull/5422/commits/1bb5e36ce3734a045c5e4aaeeba6e0d29d381789#diff-84b7041bfeae43fea26aac38d2eb71d1c2ce5d7bdb2cd6a9a7b3502662a26da8

### Extension version

22.3.3

### Browser(s) used

Brave – Version 1.35.100 Chromium: 98.0.4758.87 (Official Build) (arm64)

### Description

1. View [`1bb5e36` (#5422)](https://github.com/refined-github/refined-github/pull/5422/commits/1bb5e36ce3734a045c5e4aaeeba6e0d29d381789#diff-84b7041bfeae43fea26aac38d2eb71d1c2ce5d7bdb2cd6a9a7b3502662a26da8)

2. Expand file `source/features/collapsible-content-button.tsx`
3. Scroll up and down

Expected: Only one scroll area for the webpage's document's body or window is present

Actual: There is another scroll area present for the file container element with a little amount of scroll leeway.

Screen Recording:

https://user-images.githubusercontent.com/517469/157112498-a2ec92ff-bc3c-4f2f-a6fc-bec678a3683c.mp4

### Include in this issue:

- [X] Screenshots/video/gif demonstrating the bug, if it’s visual
- [ ] Console errors, if any

**Comment by fregante** [comment] 2022-03-07 20:36
This is not a Refined GitHub bug, I can replicate it without RG

**Comment by samholmes** [comment] 2022-03-07 21:10
> This is not a Refined GitHub bug, I can replicate it without RG

I didn't know GH has the expand all lines feature now. I've been using RG mainly for this feature.

**Comment by cheap-glitch** [comment] 2022-03-08 09:37
> I didn't know GH has the expand all lines feature now.

It was dropped in https://togithub.com/refined-github/refined-github/pull/4150.

Maybe the fix for this is as simple as:

```css
.js-blob-wrapper {
	overflow-y: hidden !important;
}
```

**Comment by fregante** [comment] 2022-03-09 10:53
> ```css
> overflow-y: hidden
> ```

_vade retro satana_

As the name suggests, that just hides the issue.

I found the cause by deleting one element at a time in the table:

<img width="260" alt="Screen Shot 6" src="https://user-images.githubusercontent.com/1402241/157427276-496a0974-c90d-48c8-8eed-93d490371396.png">

This is the line number and that `top: 1px` pushes it 1px outside the table, which lengthens the scrollable content. A fix could probably just add `margin-bottom: -1px` to it but I don't remember if that actually reduces the scrollable height.

**Comment by cheap-glitch** [comment] 2022-03-09 12:07
How about a simple `top: 0 !important`? Tried it in my custom CSS and it doesn't seem to break anything.

**Comment by fregante** [comment] 2022-03-09 12:45
I haven't checked but I assume that that would change (break) the number text alignment

**Comment by cheap-glitch** [comment] 2022-03-09 14:02
> I haven't checked but I assume that that would change (break) the number text alignment

Actually this is not the line numbers, but the `+`/`-` diff signs, which are hidden by RGH anyway.

**Comment by fregante** [comment] 2022-03-10 02:06
Sounds like our GitHub bugs CSS file will receive a +6 diff then 😌

**Comment by fregante** [comment] 2022-03-15 07:19
This bug is really annoying

**Closed** 2022-03-15 08:00 UTC
Labels: enhancement, help wanted, good first issue, Please! ♥︎, github bug
