### ISSUE TITLE
`pr-branch-auto-delete` also deletes branch if it was not merged by the user

### ISSUE THREAD

**Issue by dertieran** [refined-github/refined-github#5868] opened 2022-07-29 14:54 UTC
### Description

Not quite sure if this changed recently, but at least I did not notice it before.

I reviewed a PR of another user and kept it open in the background.
Later another user merged the PR and when I came back the branch was deleted by me with the new deleted **via Refined Github** message *(which was a good information)*.

So now I deleted a branch that I did not create and also did not merge.
I feel like I should at least be the one who merged the PR to delete the branch.
I guess it's also okay if it is my own PR and someone else merges it.
But then again it is weird that I need to have the PR open for it to work.

Happy to look into this if this is not an intended behavior, then I might just disable the feature for me 😄 

### How to replicate the issue

Instead of having two github accounts to create and merge the PR with it should also work to use two browsers with the same github account.

1. Open a PR with a browser that has rgh installed.
2. Keep the browser tab open.
3. Merge the PR from another browser *(and maybe account)* without rgh installed.
4. The deleted **via Refined Github** should appear in the first browser.

### Extension version

22.7.20

### Browser(s) used

Google Chrome 105.0.5195.10

**Comment by fregante** [comment] 2022-07-29 15:03
Ugh, I did this. The feature used to be activated after a click on the merge button:

https://github.com/refined-github/refined-github/blob/afb434cd033a085cf7b226b0d6f8d84f326813d6/source/features/pr-branch-auto-delete.tsx#L17-L20

But now there's no such event, it just looks for a merge timeline event, which can already exist:

https://github.com/refined-github/refined-github/blob/808c68f3745cfe15d1995546d5519b75dc9386e1/source/features/pr-branch-auto-delete.tsx#L45

The problem probably started because I added a new feature that appeared after a merge, but it did not actually need to be enabled after the actual *merge action**:

https://github.com/refined-github/refined-github/blob/3547c9bc0e60443dafe06752bc94e9e5b73f8d55/source/features/first-published-tag-for-merged-pr.tsx

I disabled this feature via autofix because that's kinda bad.

**Comment by fregante** [comment] 2022-07-31 08:05
The issue is far rarer than I thought:

- the feature is only active when the PR is open, so a collaborator needs to be on the tab _while_ it's merged

Still a bug, but far less severe than I thought. If you visit a merged PR it won't be activated.

**Comment by SuperSandro2000** [comment] 2022-08-26 10:02
How can I activate this feature again if I don't care if this bug exists and may actually find it useful?

**Comment by fregante** [comment] 2022-08-26 10:12
Hotfixes can't be disabled yet. We can probably drop the hotfix since it happens rarely. It'd be nice to have it fixed though, it's not too difficult: we have to first attach a `delegate` listener to the merge button.

**Comment by fregante** [comment] 2022-08-28 17:02
The feature is now active again. This bug still needs to be fixed though

**Comment by eglove** [comment] 2022-08-29 14:53
This should not be default behavior anyway. Not everyone deletes branches.

**Comment by yakov116** [comment] 2022-08-29 15:00
> This should not be default behavior anyway. Not everyone deletes branches. I just discovered this feature after it surprise deleted a branch.

See #3636 and #2267

**Closed** 2022-09-15 10:55 UTC
Labels: bug, help wanted, good first issue, Please! ♥︎
