### ISSUE TITLE
Fix comment header on PR to not hide and add button to copy filename to clipboard

### ISSUE THREAD

**Issue by jsjoeio** [refined-github/refined-github#7686] opened 2024-08-14 21:11 UTC
### Description

Often times I will get a PR comment and I want to go to the file to make the requested change. So I have to click and highlight the file name, but have the time I end up closing the comment which is frustrating.

![2024-08-14 14 10 04](https://github.com/user-attachments/assets/578f4aef-49db-440b-b813-34c4516f3692)

Instead, I'd like to propose:
1. remove functionality where clicking collapses the comment
2. add a button to copy the filename to the clipboard

### Example URLs

https://github.com/refined-github/refined-github/pull/7685

**Comment by kovsu** [comment] 2024-08-15 01:04
I think just need right click. 🤔

**Comment by fregante** [comment] 2024-08-15 01:39
Duplicate of https://github.com/refined-github/refined-github/issues/7258

**Closed by fregante** 2024-08-15 01:39 UTC
Labels: enhancement, under discussion

**Comment by jsjoeio** [comment] 2024-08-15 17:29
Sorry, my search-fu failed me when I looked for dupes - that script works perfectly! Thanks for everything Federico!
