### ISSUE TITLE
`clean-repo-tabs`: menuItem is undefined

### ISSUE THREAD

**Issue by cheap-glitch** [refined-github/refined-github#7140] opened 2023-12-05 12:07 UTC
### Description

```
onlyShowInDropdown@moz-extension://49f9749d-a211-4327-ae0d-6e28fb7a9a1c/assets/refined-github.js:12081:7
init@moz-extension://49f9749d-a211-4327-ae0d-6e28fb7a9a1c/assets/refined-github.js:12142:27
```

The feature throws an error on those lines:
https://github.com/refined-github/refined-github/blob/a0381ca315606a53def92932ed7927dca84d8963/source/features/clean-repo-tabs.tsx#L43-L44

### How to replicate the issue + URL

1. Open https://github.com/refined-github/sandbox/pull/12/checks
2. Click on the "Files" tab

### Extension version

23.12.1

### Browser(s) used

Firefox

**Comment by fregante** [comment] 2023-12-05 14:52
If it happens only after a navigation, it's probably due to:

- https://github.com/refined-github/refined-github/issues/6437

I should really look into those AJAX issues

**Comment by fregante** [comment] 2024-06-20 06:13
Closing in favor of https://github.com/refined-github/refined-github/issues/6437

**Comment by fregante** [comment] 2024-07-09 13:40
I was wrong, https://github.com/refined-github/refined-github/pull/7513 does not fix it

**Comment by fregante** [comment] 2024-11-07 11:59
Duplicate of https://github.com/refined-github/refined-github/issues/7806

**Comment by fregante** [comment] 2024-11-10 11:08
Again unrelated 😂

**Closed** 2024-11-10 11:31 UTC
Labels: bug, help wanted, ajax
