### ISSUE TITLE
`sicky-sidebar` causes repo sidebar to overlay readme

### ISSUE THREAD

**Issue by Xenfo** [refined-github/refined-github#6834] opened 2023-08-16 21:54 UTC
### Description

![image](https://github.com/refined-github/refined-github/assets/46873232/050bdac5-a833-4119-b369-d41cc64a61bd)

I'm not sure what happened since this was working an hour ago but now the sidebar overlays the repo's readme.

### How to replicate the issue + URL

1. Visit https://github.com/altdesktop/playerctl
2. Scroll

### Extension version

23.8.3

### Browser(s) used

Firefox

**Comment by fregante** [comment] 2023-08-16 22:14
Duplicate of https://github.com/refined-github/refined-github/issues/6408

**Comment by fregante** [comment] 2023-08-16 22:16
Perhaps sticky-sidebar should be disabled in Firefox. Lets had a `supportsHasSelector` filter to the `include` array

**Closed** 2023-08-25 08:08 UTC
Labels: bug, help wanted, small, firefox
