### ISSUE TITLE
`closing-remarks` shows earliest tag alphabetically, not chronologically

### ISSUE THREAD

**Issue by aryairani** [refined-github/refined-github#7208] opened 2024-01-09 16:07 UTC
### Description

The feature says the first tag containing the PR was `pre-release`

<img width="715" alt="image" src="https://github.com/refined-github/refined-github/assets/538571/3ae7e858-a045-4894-b99c-5eac3bdcacd3">

But the first tag is actually `release/0.5.13`; `pre-release` happens to be the _last_ tag containing the PR.

<img width="358" alt="image" src="https://github.com/refined-github/refined-github/assets/538571/6adb3e88-3152-4954-9c69-22d732b9cdf0">

Note: the `pre-release` tag in this repo changes over time, but the bug still happens after clearing the extension cache, so I don't suppose it's a stale result.

### How to replicate the issue + URL

https://github.com/unisonweb/unison/pull/4519

### Extension version

23.12.17

### Browser(s) used

Chrome 120.0.6099.129 (Official Build) (arm64)

**Comment by fregante** [comment] 2024-01-09 16:12
Duplicate of https://github.com/refined-github/refined-github/issues/7206#issuecomment-1881121805

**Comment by fregante** [comment] 2024-01-09 16:30
Thank you @aryairani  🙏 ☺️

**Comment by aryairani** [comment] 2024-01-09 21:24
> * Refer to [`closing-remarks`: options to exclude pre-release tags (feature request) #7206 (comment)](https://github.com/refined-github/refined-github/issues/7206#issuecomment-1881121805)

Hi @fregante — I'm a little uncertain. I don't believe it's an issue of excluding or including pre-release tags.

My understanding is that the UI is supposed to show the earliest tag that included the PR in question. In my scenario, the earliest tag isn't the pre-release tag, it's the actual release tag; but the UI is showing the pre-release tag. 

What am I missing?
Thank you!

**Comment by aryairani** [comment] 2024-01-09 21:27
(Actually I think it might the same issue described in #7206, but the submitter mistakenly focused on "pre-release" vs "release" metadata, which I think are a red herring.)

**Comment by fregante** [comment] 2024-01-10 01:16
We just ask GitHub for the order, so you can change it by changing the time of creation of the tags. But the core logic remains: this pattern requires `--force`, so it's not something we should support

**Comment by aryairani** [comment] 2024-01-10 02:21
> We just ask GitHub for the order, so you can change it by changing the time of creation of the tags. But the core logic remains: this pattern requires `--force`, so it's not something we should support

Sorry, I still didn't understand.

I think maybe the order is coming back wrong or needs to be sorted differently? I want pre-release tags to be included in the results, but in this case the pre-release tag is not the earliest tag.

<img width="386" alt="image" src="https://github.com/refined-github/refined-github/assets/538571/8941a2f4-9ddc-4f5f-aa69-5d43e232af3d">

<img width="692" alt="image" src="https://github.com/refined-github/refined-github/assets/538571/da8e79b2-8cec-4469-8dfe-077a84653b1a">

`release/0.5.13` includes the PR and is earlier than `pre-release`

> We just ask GitHub for the order

Where does this happen? Maybe I can help debug.

**Comment by fregante** [comment] 2024-01-10 03:06
See the firstTag updater function: https://github.com/refined-github/refined-github/blob/main/source/features/closing-remarks.tsx

I wonder if GitHub is showing the tags in an unexpected order in the dom, I thought we were using the API. Probably there isn't an equivalent API.

**Comment by aryairani** [comment] 2024-01-10 05:34
Should we reopen this bug since I don't think it's a dup of #7206?

**Comment by fregante** [comment] 2024-01-10 06:12
So it seems that GitHub lists tag in alphabetical order:

- https://github.com/unisonweb/unison/branch_commits/5eadbc6a40e2f3d8c54e42bfa2c3ead3566a071b

We expect the "earliest tag" to appear last on that list, because that's generally the case.

To fix this issue and to future-proof this feature, I'd be open to use the API, if it's possible. I think we went with this snippet because the API doesn't expose this information, calculating it would be expensive.

**Comment by aryairani** [comment] 2024-01-10 20:37
As a workaround I can maybe rename my `pre-release` to `nightly`, which comes before `release` in alphabetical order. 🤦  Thanks for looking into this.

**Comment by wookayin** [comment] 2024-01-10 22:01
@aryairani Alphabetically, `nightly` < `pre-release` < `release-*` < `v`, so you might instead want a tag that comes *after* `release`, i.e. s, t, u, v, w, ...  I do have a same pain in #7206, where `nightly` precedes `v`.

**Comment by aryairani** [comment] 2024-01-12 14:30
@wookayin Oh yeah! 🤦 
@fregante maybe this issue should be `closing-remarks` shows earliest tag alphabetically rather than chronologically.
i.e. you would see the same problem if the versioning scheme changes (even though none of them would necessarily be non-version tags)

**Comment by aryairani** [comment] 2024-01-26 22:56
Ok, I guess I have my functioning workaround in place now, thanks to @wookayin's alphabet help, by calling my nightly tag `trunk-build`, which comes after `release/*` alphabetically.  (I had called it my "trunk build" tag `trunk` briefly, but ran into conflicts with the `trunk` branch.)

**Comment by fregante** [comment] 2024-02-02 09:17
Tags that include the word `nightly` and tags that don't have a version (minimum `\d\.\d` expected) are now excluded:

- https://github.com/refined-github/refined-github/pull/7243

This specific issue can stay open because I'd still want ordering, but I think this can only be done via API. I don't want to get into the sorting of tags because soon enough there will be a repo with `1.0.0` and `release/2.0.0` and `beta/2.0.0` and I can't figure out every combination of that.

**Comment by fregante** [comment] 2024-06-12 06:17
> To fix this issue and to future-proof this feature, I'd be open to use the API, if it's possible. I think we went with this snippet because the API doesn't expose this information, calculating it would be expensive.

This information is not available on the API. This can be confirmed by visiting their docs:

https://docs.github.com/en/graphql/reference/objects#commit

In the Commit object, there's no way to get any tag references.

If we had access to git, this would be possible via `git tag --contains the-commit-hash`

**Closed by fregante** 2024-06-12 06:17 UTC
Labels: bug, help wanted

**Comment by Johnson1s** [comment] 2024-08-09 20:27
LIVE_API_KEY:e2b96942414af820594b4dd03f49e22e:4d786f5694d4bb1adac34eb14ee9b961
