### ISSUE TITLE
Feature: enable sticky action bar for long pull requests 

### ISSUE THREAD

**Issue by a0m0rajab** [refined-github/refined-github#7111] opened 2023-11-25 20:46 UTC
### Description

When you open a PR, there is an action bar present for editing and using extra tools. 
![image](https://github.com/refined-github/refined-github/assets/18273833/9dfa53ee-758c-4cd5-9ed2-11da7eb05479)

This action disappears with the scroll for long PRs.

This proposal suggests keeping the action bar sticky on the top of the page once you start scrolling.

Similar to: https://github.com/refined-github/refined-github/issues/6176

Example video for the issue: 

https://github.com/refined-github/refined-github/assets/18273833/94c879f2-bc1b-4ffa-a114-51da43d5e53b

### Example URLs

https://github.com/open-sauced/app/compare/beta...a0m0rajab:insights:feat/add-cart-title

**Comment by a0m0rajab** [comment] 2023-11-25 20:49
GitHub has something similar for files: https://github.com/refined-github/refined-github/pull/6465/files

They use the next CSS classes for the files header: 
```
file-header d-flex flex-md-row flex-column flex-md-items-center file-header--expandable js-file-header js-skip-tagsearch  sticky-file-header js-position-sticky js-position-sticky-stacked
```

**Comment by fregante** [comment] 2023-11-26 02:03
Duplicate of https://github.com/refined-github/refined-github/issues/4368

**Closed by fregante** 2023-11-26 02:03 UTC
Labels: enhancement, under discussion
