### ISSUE TITLE
Option to disable relative date display

### ISSUE THREAD

**Issue by maddes-b** [refined-github/refined-github#6143] opened 2022-11-05 11:14 UTC
### Description

"1h ago" is not precise (can be anything from 60 to 119 minutes ago) and "1year ago" is even worst.
Just give coders/admins an option to see all detail information so they can work without hassle.
If there are multiple commits, releases and git hub actions within a "short time", which later could be the cause of an issue, then those relative dates are disturbing analysis and consuming time.

If a timezone is needed then UTC as default would be fine as technical people know different timezones and also their offset to UTC. Newbies can easily learn what's the offeset to UTC via Wikipedia or [www.timeanddate.com](https://www.timeanddate.com/).
Otherwise adding an option to set a timezone for the user would be helpful for others.

### Screenshot

n/a

### Example URLs

n/a

**Comment by fregante** [comment] 2022-11-05 11:30
Refined GitHub doesn't offer such options. Either we enable the feature for everyone by default, or we don't add it. 

The good thing is that you can already see the real date by hovering the relative time element.

**Comment by fregante** [comment] 2022-11-05 11:31
Duplicate of https://github.com/refined-github/refined-github/issues/47

**Closed by fregante** 2022-11-05 11:30 UTC
Labels: enhancement, under discussion

**Comment by maddes-b** [comment] 2022-11-05 11:45
Thanks for mentiong #47, I installed [Tampermonkey](https://www.tampermonkey.net/) and then the mentioned UserScript [GitHub-static-time](https://github.com/Mottie/GitHub-userscripts/wiki/GitHub-static-time).
That works well.

**Comment by ST-DDT** [comment] 2026-06-14 19:54
On GitHub mobile browsers you dont have the ability to hover the element.
Would it be possible to add "tap to display absolute date" so GH gets at least usable on mobile?
