### ISSUE TITLE
Unhandled auth token permissions infinite loop / crash

### ISSUE THREAD

**Issue by binury** [refined-github/refined-github#5215] opened 2021-12-16 18:30 UTC
### Please ensure:

- [X] The bug is caused by Refined GitHub. It doesn't happen if I disable the extension.

### Include in this issue:

- [x] Screenshots/video/gif demonstrating the bug, if it’s visual
- [x] Console errors, if any

### Description

![image](https://user-images.githubusercontent.com/1146921/146427777-fa701713-2f85-4be5-8b3c-d40e1f6a9cd9.png)

I can replicate this 100% of the time by viewing a file **at a commit ref and then using the dropdown to change to a branch**, on Firefox 95
(Presumably only when no auth token is available to the extension)

```
 4 index.tsx:55:10
ℹ️ latest-tag-button → Personal token required for this feature 4 index.tsx:55:10
ℹ️ list-prs-for-file → Personal token required for this feature 4 index.tsx:55:10
ℹ️ latest-tag-button → Personal token required for this feature 4 index.tsx:55:10
ℹ️ list-prs-for-file → Personal token required for this feature 4 index.tsx:55:10
ℹ️ latest-tag-button → Personal token required for this feature 4 index.tsx:55:10
ℹ️ list-prs-for-file → Personal token required for this feature 4 index.tsx:55:10
ℹ️ latest-tag-button → Personal token required for this feature 4 index.tsx:55:10
ℹ️ list-prs-for-file → Personal token required for this feature 4 index.tsx:55:10
ℹ️ latest-tag-button → Personal token required for this feature 4 index.tsx:55:10
ℹ️ list-prs-for-file → Personal token required for this feature 4 index.tsx:55:10
ℹ️ latest-tag-button → Personal token required for this feature 4 index.tsx:55:10
ℹ️ list-prs-for-file → Personal token required for this feature 4 index.tsx:55:10
ℹ️ latest-tag-button → Personal token required for this feature 4 index.tsx:55:10
ℹ️ list-prs-for-file → Personal token required for this feature
```

### Example URL

https://github.com/binury/quest-helper/blob/34ba43c58e812c41a63c84fa2872f3c08cc12c67/src/main/java/com/questhelper/panel/questorders/QuestOrders.java

### Browser(s) used

Firefox 95

**Comment by binury** [comment] 2021-12-16 18:32
Hmm. Actually, this occurs even with a valid auth token- although in that case there is no console output

**Comment by fregante** [comment] 2021-12-17 06:11
I'll take a look, but this shouldn't be due to API calls since those calls aren't made at all when the token is missing. 

If this is really caused by RGH, it should be some feature that clicks something automatically or makes requests. 

Do you see a lot of requests in the file? Are they triggered by Refined GitHub?

**Comment by fregante** [comment] 2021-12-17 06:12
Closing as the linked file is very small and I don’t think it's due to this extension. Please leave a comment if you're sure it's otherwise.

**Closed** 2021-12-17 06:12 UTC
Labels: bug
