### ISSUE TITLE
Add flag to default to "hide whitespace changes" in PRs

### ISSUE THREAD

**Issue by ashughes** [refined-github/refined-github#5829] opened 2022-07-15 00:03 UTC
### Description

When reviewing PRs, I _usually_ want to hide whitespace changes. It'd be great if there was a flag to enable this as the default behavior rather than having to click the "Hide whitespace changes" button (or use the shortcut) every time. :pray: 

### Example URLs

https://github.com/refined-github/refined-github/pull/5827/files

**Comment by busches** [comment] 2022-07-15 00:34
Duplicate of #2503

**Closed by busches** 2022-07-15 00:34 UTC
Labels: enhancement, under discussion
