### ISSUE TITLE
Allow to filter PR  job results by type

### ISSUE THREAD

**Issue by staabm** [refined-github/refined-github#5855] opened 2022-07-26 12:17 UTC
### Description

in some projects there are a lot of github actions running and finding those which errored requires scrolling thru a huge list.

![grafik](https://user-images.githubusercontent.com/120441/181003610-97577299-aa8a-4199-86b9-891f104263ec.png)

would be great if I could somehow filter the list by result (succeeded, errorred, skiped) to only show me the errored ones

### Example URLs

https://github.com/phpstan/phpstan-src/pull/1558

**Comment by kidonng** [comment] 2022-07-27 05:16
We kinda have an open issue for this: #3136

**Comment by fregante** [comment] 2022-07-27 05:21
Duplicate of https://github.com/refined-github/refined-github/issues/5621

**Closed by fregante** 2022-07-27 05:21 UTC
Labels: enhancement, under discussion
