### ISSUE TITLE
A feature to display the size of a file or folder

### ISSUE THREAD

**Issue by DarkFlameMasterDev** [refined-github/refined-github#6748] opened 2023-06-24 15:18 UTC
### Description

A feature to display the size of a file or folder
一项可显示文件或者文件夹大小的功能
Of course detecting folder size may be used recursively search, which can be a drag on performance, but it's actually quite useful
当然 检测文件夹大小可能会用到递归，这有可能会拖慢性能，但是其实还挺有用的

### Example URLs

Sorry, I didn't understand what link I needed to provide

**Comment by fregante** [comment] 2023-06-24 19:50
Duplicate of https://github.com/refined-github/refined-github/issues/2431

**Closed by fregante** 2023-06-24 19:50 UTC
Labels: enhancement, under discussion

**Comment by melange396** [comment] 2023-07-20 00:11
I can find only 2 Chrome extensions that claim to do this: [Enhanced GitHub](https://chrome.google.com/webstore/detail/enhanced-github/anlikcnbgdeidpacdbdljnabclhahhmd) and [GitHub Repository Size](https://chrome.google.com/webstore/detail/github-repository-size/apnjnioapinblneaedefcnopcjepgkci/).  Neither has been updated in a long time (the first is >1.5 years stale, and the other is >3 years), and they don't seem to be supported by their authors anymore.  Also, both are currently broken -- they only show sizes for files in the root directory of the repo, see [this issue](https://github.com/softvar/enhanced-github/issues/132)).

It would be nice to have this functionality provided and backed by active (and competent and accomplished and really good looking) developers like yourselves.  Or, if you wanted to surpass what they have done, you could display line counts for each file instead of (or in addition to) sizes/bytes.
