### ISSUE TITLE
Next reviewable PR

### ISSUE THREAD

**Issue by gergelyke-dd** [refined-github/refined-github#6170] opened 2022-11-17 23:40 UTC
### Description

I was wondering if there would be an appetite for adding a feature that would prompt users after leaving a review to take a look at another PR? 

This would allow folks to "stay in the flow", and review a few more PRs while at it.

### Example URLs

https://github.com/refined-github/refined-github/pull/6169

**Comment by fregante** [comment] 2022-11-18 00:59
Duplicate of #343

**Closed by fregante** 2022-11-18 00:59 UTC
Labels: enhancement, under discussion
