### ISSUE TITLE
Import/export refined github settings

### ISSUE THREAD

**Issue by 0xdevalias** [refined-github/refined-github#3981] opened 2021-02-15 01:50 UTC
This extension has a LOT of features, and it took me quite a while to go through and toggle all of the ones off/on to suit my needs/desires. It would be good if I was able to export my settings as a `.json` file or similar, so that I can back them up, and/or to be able to share them with my friends/colleagues.

Then there would also need to be a way for me to import this `.json` of settings again too.

**Comment by fregante** [comment] 2021-02-15 03:27
Duplicate of #2726

**Comment by tupaschoal** [comment] 2021-10-21 03:24
I definitely vouch for that, specially because I want to use the same settings on different machines that I own, so it would be very handy.

**Comment by kidonng** [comment] 2021-10-21 04:05
For the moment, you can use the following method to sync settings manually:

```js
// 1. Open Console from DevTools of the options page
// 2. Run the snippet to copy the list of disabled features
copy($$('.feature > input:not(:checked)').map(i => i.id))
// 3. On another browser, open console and input disabled features
disabledFeatures = // paste here
// 4. Run the snippet to sync states
$$('.feature > input').forEach(i => i.checked === disabledFeatures.includes(i.id) && i.click())
```

---

@tupaschoal If you own the machines, you can just login to the same account and the browser will sync them.

**Comment by tupaschoal** [comment] 2021-10-23 00:25
Thanks for the console commands. I don't want to login because some machines are not owned by me (i.e. work machines), but used on a daily basis.

**Comment by noroadsleft** [comment] 2023-04-10 19:36
I'm immensely grateful for this extension - it's become a vital part of my toolkit here on GitHub - so I am greatly dismayed to become the bearer of potentially bad news:

I'm attempting to use this feature in Firefox, and it does not appear to work at all. Clicking Export or Import results in the following:

![image](https://user-images.githubusercontent.com/18669334/230980397-fc0cca98-fbae-47cb-a011-a41240c04db2.png)

This is with Refined GitHub 23.4.10 in [Firefox 111.0 running on Linux Mint 21.1 MATE 64-bit](https://user-images.githubusercontent.com/18669334/230980732-dfbdc03c-df40-44a5-afe1-afa74a35fc09.png), but I received the same error attempting to export the settings from my Firefox 111.0.1 on Windows 8.1 64-bit.

I'm unclear as to whether this requires https://github.com/fregante/webext-options-sync/pull/65 to be merged in order to work, so if that's the case please let me know. Otherwise I'll just wait patiently.

Thank you for a wonderfully powerful extension.

**Comment by kidonng** [comment] 2023-04-11 04:00
That PR is included, but it seems to use an API that only Chromium supports now: https://developer.mozilla.org/en-US/docs/Web/API/Window/showOpenFilePicker

@fregante is this required by extension context? Couldn't we use file input and Blob?

**Comment by fregante** [comment] 2023-04-11 04:09
Ouch when I wrote that alert box I thought this feature was just available in the latest version of every browser, just super new. I'm not sure about where I got that idea from 🤔 

In the PR you can see I had initially implemented it via input[type=file] and a[download]. The advantage of the new API is that it shows a "save file" dialog instead of just throwing the file into the Downloads folder. 

I'll update the feature to support both methods I guess 🥲

**Comment by fregante** [comment] 2023-04-11 15:33
The feature is here, the PR is open in the repo.

**Closed** 2023-04-11 15:32 UTC
Labels: help wanted, meta

**Comment by fregante** [comment] 2023-04-14 13:35
> I thought this feature was just available in the latest version of every browser

Cause: https://caniuse.com/native-filesystem-api

<img width="544" alt="Screenshot" src="https://user-images.githubusercontent.com/1402241/232058482-f8c13cd7-1966-4c25-ad50-e9a088c76136.png">


Anyway, a fix is in. Will publish a new version this weekend probably
