### ISSUE TITLE
`clean-repo-sidebar` throws an error in attempting to move a nonexistent report link

### ISSUE THREAD

**Issue by DanielMiao1** [refined-github/refined-github#6648] opened 2023-05-14 17:38 UTC
### Description

In the `clean-repo-sidebar` feature, the following code [(source link)](https://github.com/refined-github/refined-github/blob/main/source/features/clean-repo-sidebar.tsx#L59) was introduced to the [`moveReportLink function`](https://github.com/refined-github/refined-github/blob/main/source/features/clean-repo-sidebar.tsx#L56) in #6500 to select the "Report repository" button, which is used afterwards to move it to the bottom of the sidebar:

<code>const reportLink = <b><i>select('.Layout-sidebar a[href^="/contact/report-content"]')!</i></b>.parentElement!;</code>

However, the code throws an error due to the non-null assertion operator when the `select` function above returns an null value in repositories owned by the user (see figures below) where report link does not exist.

### How to replicate the issue + URL

1. Navigate to the home page of a repository that you have ownership or collaborator access on, such as https://github.com/fregante/GhostText
2. The error occurs
&nbsp;

**Figure 1**
_The error occurs in a repository home page where the report button does not exist_

![Screenshot 2023-05-11 at 9 13 46 AM](https://github.com/refined-github/refined-github/assets/83146190/00a4af67-23a7-4623-a9cd-bca0b78b1d07)

&nbsp;
**Figure 2**
_The same issue, on Firefox_

![Screenshot 2023-05-11 at 12 28 04 PM](https://github.com/refined-github/refined-github/assets/83146190/673c3365-c1a8-47d9-bba6-db074b2e13fd)

### Extension version

23.5.10

### Browser(s) used

all supported browsers

**Comment by fregante** [comment] 2023-05-14 18:33
Duplicate of https://github.com/refined-github/refined-github/issues/6569

**Comment by fregante** [comment] 2023-05-14 18:36
Actually it's not quite the same reason, so I'll reopen this and send a PR

**Closed** 2023-05-14 18:42 UTC
Labels: bug
