### ISSUE TITLE
`latest-tag-button` is vertically misaligned when window width < 800px

### ISSUE THREAD

**Issue by cheap-glitch** [refined-github/refined-github#5347] opened 2022-01-29 18:45 UTC
### Please ensure:

- [X] The bug is caused by Refined GitHub. It doesn't happen if I disable the extension.
- [X] The bug happens after clearing extension cache. The "Clear cache" button can be found at the bottom of the options page.

### Example URLs

https://github.com/dotnet/runtime/tree/09ff1acdad2e7789908b5db9bb89896144c13042/src/libraries/Microsoft.VisualBasic.Core

### Extension version

22.1.18

### Browser(s) used

Firefox

### Description

![image](https://user-images.githubusercontent.com/46634000/151673453-133105c0-b5e7-4666-80d4-44a03c8fc5fd.png)

### Include in this issue:

- [X] Screenshots/video/gif demonstrating the bug, if it’s visual
- [ ] Console errors, if any

**Comment by kidonng** [comment] 2022-01-29 21:18
Fix is simple: drop `.flex-self-center` and `.btn-sm` (#3356):

![image](https://user-images.githubusercontent.com/44045911/151677760-530eace0-ff7c-4a64-b45d-8a43e4096fdb.png)

<sub>Unless you want to stick to the small size and ignore this bug.</sub>

**Comment by fregante** [comment] 2022-02-02 07:47
> Unless you want to stick to the small size and ignore this bug.

Logic is simple: big is current page, small is navigation. Put 3 identical buttons there and nothing makes sense.

Where am I?

<img width="298" alt="Screen Shot 1" src="https://user-images.githubusercontent.com/1402241/152113652-1b11c76d-c2c9-47e6-b191-2f09fbdb4c48.png">

**Comment by fregante** [comment] 2022-02-02 07:54
Duplicate of https://github.com/refined-github/refined-github/issues/4229

**Comment by kidonng** [comment] 2022-02-02 21:05
> Logic is simple: big is current page, small is navigation.

This is also navigation, however it uses standard size:

<img width="909" alt="Screen Shot 2022-02-03 at 04 57 28" src="https://user-images.githubusercontent.com/44045911/152236278-a3be37eb-fcf8-4a41-8492-48c31c60f993.png">

> Put 3 identical buttons there and nothing makes sense.

I thought we are only talking about `latest-tag-button`. What else features could be mistaken?

> Where am I?
> 
> <img alt="Screen Shot 1" width="298" src="https://user-images.githubusercontent.com/1402241/152113652-1b11c76d-c2c9-47e6-b191-2f09fbdb4c48.png">

You made a good point here, but I doubt anyone would actually be confused by it, unless they haven't used the branch selector once.

**Closed** 2022-02-03 02:09 UTC
Labels: bug, help wanted, good first issue
