### ISSUE TITLE
Download button replicated

### ISSUE THREAD

**Issue by mergd** [refined-github/refined-github#6666] opened 2023-05-19 17:24 UTC
### Description

Cleared cache, tried the troubleshooting steps.

<img width="1237" alt="Screenshot 2023-05-19 at 10 15 10 AM" src="https://github.com/refined-github/refined-github/assets/24722014/485e1d0d-d964-4b3f-92cf-bbec60b48f88">

### How to replicate the issue + URL

Putting a random Github link as it affects any github repo.
https://github.com/latticexyz/mud/tree/main/examples/minimal/packages/plugin-example/ts/register

To replicate:
1. Enter a repository, and enter a folder, and then a file in the folder
2. Use the browser back button to go back to the folder 
3. Go to any file in the folder
4. Go back to the folder
5. Each cycle of this entering and exiting files within a directory appends a download button on to the menu shown
6. Reloading the page removes the appended download buttons

### Extension version

23.5.10

### Browser(s) used

Arc

**Comment by fregante** [comment] 2023-05-19 18:58
Duplicate of https://github.com/refined-github/refined-github/issues/6414

**Closed by fregante** 2023-05-19 18:58 UTC
Labels: bug
