### ISSUE TITLE
Add a `copy-path` button to PR review comments

### ISSUE THREAD

**Issue by justinsmid** [refined-github/refined-github#6398] opened 2023-03-01 14:17 UTC
### Description

When looking at `Files changed` in a PR, each file has a copy button next to its name:

![image](https://user-images.githubusercontent.com/34271675/222165274-eb94e55e-c128-4de1-a222-c9883b1bb5f3.png)

When looking at review comments in `Conversation`, there is no such button:

![image](https://user-images.githubusercontent.com/34271675/222165739-786ff3ea-351e-44d4-8ca8-6f4accbb488e.png)

I would like such a button to be added there aswell.

### Example URLs

https://github.com/refined-github/refined-github/pull/6394

**Comment by fregante** [comment] 2023-03-01 14:27
Duplicate of https://github.com/refined-github/refined-github/issues/1912

**Comment by justinsmid** [comment] 2023-03-01 15:02
True, my bad!

If I may continue the discussion though: your closing comment on that issue seems to imply this feature would be helpful to review**er**s. 

> (...), Just click the filename and **keep reviewing** from the Files tab, (...)

To me, this feature would be most useful from the POV of the **assignee**, however.
When a reviewer leaves comments on changes in my PR, I want to be able to look at these comments in the `Conversation` tab, and quickly open the relevant files in my editor. I don't want to have to keep switching between the `Conversation` and `Files changed` tabs when processing feedback just to be able to copy the filename.

> Discussions are already pretty busy, I don't wanna add any more buttons

This is definitely fair though. If you still feel this way about it and don't want to add it because it would add too much clutter, I understand.

**Comment by kidonng** [comment] 2023-03-20 15:28
> When a reviewer leaves comments on changes in my PR, I want to be able to look at these comments in the `Conversation` tab, and quickly open the relevant files in my editor.

Not related to GitHub (interface), but editor plugins may be useful for this use case, like [this one for VSCode](https://marketplace.visualstudio.com/items?itemName=GitHub.vscode-pull-request-github).

**Comment by fregante** [comment] 2023-09-08 12:37
Too many feature requests, realistically we’ll never get there. I’m closing those I think aren’t worth it.

**Closed by fregante** 2023-09-08 12:37 UTC
Labels: enhancement, under discussion
