### ISSUE TITLE
`pr-branch-auto-delete` deletes branches that are the base of other PRs

### ISSUE THREAD

**Issue by BasSchoutenTribe** [refined-github/refined-github#7782] opened 2024-09-04 10:28 UTC
### Description

While this option can be very usefull, it needs to be enabled with great awareness as this will make a merge desctructive by deleting branches. Also, if pull requests exist into the branch that is deleted, all requests are changed to be merged into the default branch. If you are not carefull when merging those PRs you might be merging them into the wrong branch.

My suggestion: Do not set this on by default

### Example URLs

Not applicable

**Comment by fregante** [comment] 2024-09-04 10:46
Duplicate of https://github.com/refined-github/refined-github/issues/2267 https://github.com/refined-github/refined-github/issues/3636 and many many more.


> make a merge desctructive by deleting branches

Deleting branches is not destructive, branches can be restore with a click.



> all requests are changed to be merged into the default branch

This is a good point, but it can _also_ be restored. I just tried merging and deleting https://github.com/refined-github/sandbox/pull/89 and then re-basing https://github.com/refined-github/sandbox/pull/90

So, question: why do you have a second PR pointing to a branch you already merged from? Does the branch have a specific name like `develop`?

**Comment by BasSchoutenTribe** [comment] 2024-09-04 10:56
Sorry I didnt look for duplicates ... but my main concern is the unwanted and unseen modification of pull requests when a branch is deleted. Restoring the branch does not restore the pull requests.

The actual use case it not that important. IF you have a PR merging into the branch you are merging (and its not the default) branch then the pr;s get modified.

Our usecase is because we are in a transition period we have two master branches and two production branches. 
temporarily we have feature imlementations done in two feature branches `featureX-v1 -> master` and `featureX-v2 -> master-v2`

When we merge `master-v2 -> production-v2` (an almost daily action) then master-v2 gets deleted because it is not the default branch and PRs like  `featureY-v2 -> master-v2` gets changed into `featureY-v2 -> master`

**Comment by fregante** [comment] 2024-09-04 11:17
The concern about deleting branches that are the base of other PRs is valid. I asked your use case because we’re already planning on addressing yours:

- https://github.com/refined-github/refined-github/issues/7755

An additional safety check could be to query the API for open PRs pointing to the branch that is about to be deleted. 

But, as always, if you don’t want branches to be deleted, use branch protections. If this advice is not part of the (info) bubble we add, then we should include it there too.

**Comment by fregante** [comment] 2024-09-04 11:21
PR(s) welcome to:

- [ ] check for open PRs pointing to the branch 
- [ ] extend the info bubble to link to [the wiki](https://github.com/refined-github/refined-github/wiki/Extended-feature-descriptions), where we’ll explain what to do better

**Comment by BasSchoutenTribe** [comment] 2024-09-04 11:41
The suggestion to protect branches is a very good suggestion .. why didnt i think of that before ??
thanks.

Feel free to close this issue and keep one of the duplicates as the main issue

**Closed** 2024-12-02 07:23 UTC
Labels: bug, help wanted
