### ISSUE TITLE
Add a button to jump to first and latest commit

### ISSUE THREAD

**Issue by Androz2091** [refined-github/refined-github#3455] opened 2020-08-12 15:39 UTC
Hey! I'm the one who opened the issue to add the `repo-age` feature, because I think it's really interesting to know how a project was... in the beginning, and what was done first. Sometimes I spend a lot of time spamming the "Older" button to see what the first commits were. So if we could add these buttons it would be really really useful:
![Capture d’écran 2020-08-12 à 17 30 19](https://user-images.githubusercontent.com/42497995/90035588-4190db80-dcc2-11ea-9579-ff676629cecb.png)
(or first page/last page, some websites use this term)

It would be very easy to make them, as we could just get the first commit hash, the number of commits and then generate an URL like `https://github.com/Androz2091/AtlantaBot/commits/master?after=FIRSTCOMMITHASH+NUMBEROFCOMMITS&branch=master`.

**Comment by sindresorhus** [comment] 2020-08-12 16:43
I've had this use-case before too, but I don't think it's common enough to be with the other navigation buttons. It could just be a small "Last page" link somewhere.

**Comment by fregante** [comment] 2020-08-12 17:20
Duplicate of https://github.com/sindresorhus/refined-github/issues/2882

**Comment by fregante** [comment] 2020-08-12 17:25
### Newest

It's already possible: 

![](https://user-images.githubusercontent.com/1402241/90046798-d7c80000-dcc8-11ea-93ec-00ed80718540.gif)

### Oldest

It's already possible to get the very first commit thanks to `repo-age` (https://github.com/sindresorhus/refined-github/pull/3169), but there's no way to see the History page once there.

**Comment by fregante** [comment] 2020-08-12 17:32
First commit example: https://github.com/sindresorhus/refined-github/commit/07ecc75e81cbc466d6bc98a12505ae58fec68d59

**Comment by Androz2091** [comment] 2020-08-13 14:54
> I've had this use-case before too, but I don't think it's common enough to be with the other navigation buttons. It could just be a small "Last page" link somewhere.

Yes, I agree, a small link to jump to the last page would be better than a button the same size as the main buttons.

> It's already possible to get the very first commit thanks to repo-age (#3169), but there's no way to see the History page once there.

Yes, I saw that, and it's why a link could be useful. And for me a link to the "oldest page" is more interesting than the "newest page" one, as we are on this page by default.

**Comment by fregante** [comment] 2020-08-13 23:09
If we extract this part of the function, this feature would come for free since the `commitCount` would already be cached: 

https://github.com/sindresorhus/refined-github/blob/6bba1c5de1e8b609e010f252d72ff9c63af431a6/source/features/repo-age.tsx#L46-L63

Probably:

```js
const getLatestCommitInfo = cache.function(async () => {
	const {repository} = await api.v4(`
		repository(${getRepoGQL()}) {
			defaultBranchRef {
				target {
					... on Commit {
						oid
						committedDate
						resourcePath
						history {
							totalCount
						}
					}
				}
			}
		}
	`);

	const {target} = repository.defaultBranchRef;
	return {
		hash: target.oid,
		path: target.resourcePath,
		date: target.committedDate,
		commitCount: history.totalCount
	};
}, {
	cacheKey: () => 'latest-commit-info:' + getRepoURL()
});
```

**Comment by yakov116** [comment] 2020-08-19 11:49
I am not sure how the layout should be. But if anyone wants to send a PR, cherry-pick https://github.com/sindresorhus/refined-github/commit/e4728b616da839c8d0761700efbc74510aad29d3 to extract the function https://github.com/sindresorhus/refined-github/issues/3455#issuecomment-673753201

**Comment by anzz1** [comment] 2023-09-02 07:10
Just pinging this, as I'm currently using this JS bookmark to jump to the last page which is suboptimal.
```js
javascript:(function()%7B((%5B_%2C%20repo%5D)%20%3D%3E%20%7Bconst%20branchElement%20%3D%20document.querySelector(%22%23branch-select-menu%20%3E%20summary%20%3E%20span.css-truncate-target%22)%3Bconst%20branch%20%3D%20branchElement%20%3F%20branchElement.textContent%20%3A%20'master'%3Bfetch(%60https%3A%2F%2Fgithub.com%2F%24%7Brepo%7D%2Ftree%2F%24%7Bbranch%7D%60).then(res%20%3D%3E%20res.text()).then(res%20%3D%3E%20%7Bconst%20mainDocument%20%3D%20new%20DOMParser().parseFromString(res%2C%20'text%2Fhtml')%3Blet%20commitCount%20%3D%20mainDocument.evaluate('%2F%2Fspan%5B%40class%3D%22d-none%20d-sm-inline%22%5D%2F%2Fstrong'%2C%20mainDocument.body).iterateNext().innerText%3BcommitCount%20%3D%20Number(commitCount.trim().replaceAll('%2C'%2C%20''))%3Bconst%20commitId%20%3D%20mainDocument.evaluate('%2F%2F*%5B%40class%3D%22f6%20Link--secondary%20text-mono%20ml-2%20d-none%20d-lg-inline%22%5D'%2C%20mainDocument.body).iterateNext().getAttribute(%22href%22).split('%2F').pop()%3Bconst%20url%20%3D%20%60https%3A%2F%2Fgithub.com%2F%24%7Brepo%7D%2Fcommits%2F%24%7Bbranch%7D%3Fafter%3D%24%7BcommitId%7D%2B%24%7BcommitCount-10%7D%60%3Bwindow.location%20%3D%20url%3B%7D)%7D)(window.location.pathname.match(%2F%5C%2F(%5B%5E%5C%2F%5D%2B%5C%2F%5B%5E%5C%2F%5D%2B)(%3F%3A%5C%2F(%3F%3Atree%7Ccommits%7Cblob)%5C%2F(%5B%5E%5C%2F%5D%2B))%3F%2F))%7D)()
```

Suggestions for the layout, I think option 2 looks more cleaner.

Original:
![image](https://github.com/refined-github/refined-github/assets/13628128/01aa0c66-0b74-41f2-8b82-11b931a82069)

Suggestion 1:
![image](https://github.com/refined-github/refined-github/assets/13628128/af83ae0d-3e46-4282-822a-13a0ef76a86c)

Suggestion 2:
![image](https://github.com/refined-github/refined-github/assets/13628128/67e6e0b0-73a6-4fdf-99ea-4c6db612e34c)

**Comment by fregante** [comment] 2024-10-12 10:41
Closing as explained in https://github.com/refined-github/refined-github/issues/3455#issuecomment-673007657

In short:

- newest commit: already possible via native branch selector
- oldest commit: already possible via `repo-age`

`repo-age` can also be extended:

- https://github.com/refined-github/refined-github/issues/7148

**Closed by fregante** 2024-10-12 10:41 UTC
Labels: enhancement, help wanted
