### ISSUE TITLE
`clean-readme-url`: Remove parameter when navigating to another URL

### ISSUE THREAD

**Issue by injust** [refined-github/refined-github#7619] opened 2024-07-30 17:38 UTC
### Description

In the README, when you click a URL that navigates to another page, `tab=readme-ov-file` is added to the current URL before/while navigation happens. `clean-readme-url` _should_ remove this, but currently doesn't.

Once you get to the new URL, if you press Back in your browser, `tab=readme-ov-file` is still in the URL and isn't removed.

Another way of looking at this is: Shift+click the link. The destination opens in a new window, but `tab=readme-ov-file` is still added to the current page.

### How to replicate the issue + URL

https://github.com/community/community

Click on the Accessibility or About Accessibility links (probably all the links will repro this, but I only tried those 2)

### Extension version

24.7.23

### Browser(s) used

Chrome on macOS Sonoma 14.5

**Comment by fregante** [comment] 2024-07-30 17:51
Thanks for the report! Bug confirmed.

Judging by the code, I can't understand why it's not working, even when visiting this copy-pasted URL directly:

```
https://github.com/community/community?tab=readme-ov-file
```

**Comment by fregante** [comment] 2024-07-30 17:52
https://github.com/community/community?tab=readme-ov-file

**Comment by fregante** [comment] 2024-07-30 17:53
Or even live-links? 🤔 

https://github.com/community/community?tab=readme-ov-file

I thought we tackled this in the shortened as well? 

- https://github.com/refined-github/shorten-repo-url/pull/44

**Comment by injust** [comment] 2024-07-30 18:10
Oh that's really weird, because this feature has been working flawlessly until I ran into it on https://github.com/community/community.

Initially, I thought that the bug was limited to during navigation or shift-clicking, but it seems that the feature just doesn't work at all on this repo?

Same for the links on https://github.com/community/events, too.

**Comment by fregante** [comment] 2024-07-30 18:25
I know why

**Comment by fregante** [comment] 2024-07-30 18:26
https://github.com/Mottie/github-reserved-names/blob/f9ff2898ef6ca77991a786d7e7acc2fb87e500fe/reserved-names.json#L86

**Comment by fregante** [comment] 2024-07-30 18:42
That page is not detected as a repo:

https://refined-github.github.io/github-url-detection/?url=%2Fcommunity%2Fcommunity

Because `community` is marked as a reserved name:

https://github.com/Mottie/github-reserved-names/blob/f9ff2898ef6ca77991a786d7e7acc2fb87e500fe/reserved-names.json#L86

I sent a PR to fix it:

- https://github.com/Mottie/github-reserved-names/pull/22

**Comment by fregante** [comment] 2024-07-31 04:13
Fixed. It'll come on the next update

**Closed** 2024-07-31 04:13 UTC
Labels: bug, help wanted, small

**Comment by injust** [comment] 2024-08-08 05:49
> Fixed. It'll come on the next update

https://github.com/refined-github/refined-github/releases/tag/24.8.3 was a new release, but `github-reserved-names` is still on `2.0.5` in https://github.com/refined-github/refined-github/blob/main/package-lock.json.

Does it need to be manually bumped or something?

**Comment by fregante** [comment] 2024-08-08 08:08
Thanks for the ping. I did forget to update that specific dependency. I'll try to update all dependencies right before the next update (not sure when that'll come yet)
