### ISSUE TITLE
Option to add Pull Request Actions (approve, request for comment, reject) on the main page of PR

### ISSUE THREAD

**Issue by sedghi** [refined-github/refined-github#6224] opened 2023-01-13 14:34 UTC
### Description

This feature request suggests the addition of Pull Request Actions (approve, request for comment, reject) on the main page of the Pull Request in GitHub. These actions would allow users to quickly and easily review, comment on, and approve or reject pull requests without having to navigate to the files changed page. 

This would streamline the review process and make it more efficient for maintainers since often I know what I need to tell the contributor, but I need to go to the other page to comment OR If I know they have addressed my comments I just need to approve it, but then again I need to navigate to the page

### Screenshot

![image](https://user-images.githubusercontent.com/7490180/212345153-abf67962-4fac-4353-b298-f2a3db3eeb95.png)

### Example URLs

No, on the PR

**Comment by fregante** [comment] 2023-01-13 14:40
Duplicate of https://github.com/refined-github/refined-github/issues/6118

**Comment by fregante** [comment] 2023-01-13 14:41
> ### Example URLs
> No, on the PR

Example URL is always required.

**Closed by fregante** 2023-01-13 14:40 UTC
Labels: enhancement, under discussion
