### ISSUE TITLE
Add ability to override Github default PR merge commit title

### ISSUE THREAD

**Issue by nene** [refined-github/refined-github#5909] opened 2022-08-09 10:32 UTC
### Description

Use case: I don't like the merge commit titles that Github automatically generates for pull requests. Rather than mentioning a branch name in the commit title, which is often abbreviated and sometimes even misleading, I'd much more prefer to use the title of a PR as the title of the merge commit.

There is already a feature quite similar to what I want: `sync-pr-commit-title`, but this only applies to squash merges. I'd guess it wouldn't be too difficult to extend it to also work for normal merge commits. Actually the name of this feature doesn't even mention squashing, that part is only in the description. Though more likely this should be a separate feature that could be turned on and off.

The `sync-pr-commit-title` uses the following title format: `<Pull Request Title> (#NR)`. That likely won't do for the merge commit title - one would surely want the word "merge" to be in there somewhere. I've personally been using the following for merge PR-s: `Merge PR #NR: <Pull Request Title>`. But variations of this (e.g. `Merge PR: <Pull Request Title> (#NR)`) would work for me as well. Ideally the message would be configurable, but as I don't see such configurability with any other feature, that's probably off the table for now.

After finishing writing all this I stumbled upon on a 4-year old request for the same feature #1264 which was closed. So I guess it probably won't happen :(

### Example URLs

https://github.com/refined-github/refined-github/pull/5902

**Comment by fregante** [comment] 2022-08-09 12:10
Duplicate of https://github.com/refined-github/refined-github/issues/1264

**Closed by fregante** 2022-08-09 12:10 UTC
Labels: enhancement, under discussion

**Comment by fregante** [comment] 2022-08-24 04:30
GitHub implemented it

https://github.blog/changelog/2022-08-23-new-options-for-controlling-the-default-commit-message-when-merging-a-pull-request/
