### ISSUE TITLE
Duplicate `show-names` in private repos

### ISSUE THREAD

**Issue by nesl247** [refined-github/refined-github#3204] opened 2020-06-08 19:13 UTC
This appears to happen in private organization repositories only.

![image](https://user-images.githubusercontent.com/1037526/84068760-79646580-a997-11ea-8d0d-da1ecbbd1574.png)

**Comment by fregante** [comment] 2020-06-10 11:30
Related: https://github.com/sindresorhus/refined-github/issues/3081

**Comment by kidonng** [comment] 2020-06-18 02:31
This change seems to be in testing, as I didn't encounter it on my private issues.

**Comment by fregante** [comment] 2020-07-25 21:09
@nesl247 can you still reproduce this bug?

**Comment by nesl247** [comment] 2020-07-27 14:13
@fregante Yes I can.

**Comment by fregante** [comment] 2020-10-08 05:43
@yakov116 I added you to a private repo to help debug this

**Comment by yakov116** [comment] 2021-03-23 17:53
@nesl247 is this still an issue?

**Comment by nesl247** [comment] 2021-03-23 18:00
I'm actually not sure as I stopped using refined-github when I switched to Safari.

**Comment by fregante** [comment] 2021-03-23 23:19
Refined GitHub is available for Safari by the way, it’s on homebrew

**Comment by JakeMerdichAMD** [comment] 2021-06-22 16:12
Also repro'ing here (github ent server 3.0.x). Here's a snippet of what I see (anonymized):

```
<h3 class="timeline-comment-header-text f5 text-normal">

<a class="d-inline-block d-md-none" data-hovercard-type="user" data-hovercard-url="/users/usernamehere/hovercard" data-octo-click="hovercard-link-click" data-octo-dimensions="link_type:self" href="/usernamehere"><img class="avatar rounded-1 avatar-user" alt="@usernamehere" src="https://github.somecorp.com/avatars/u/7238?s=60&amp;u=6e45c6b00b89181d89f157cb9e775d61dea5daa8" width="20" height="20"></a>
<strong class="css-truncate">

<a class="author link-gray-dark css-truncate-target width-fit rgh-fullname" show_full_name="true" data-hovercard-type="user" data-hovercard-url="/users/usernamehere/hovercard" data-octo-click="hovercard-link-click" data-octo-dimensions="link_type:self" href="/usernamehere">usernamehere</a><span class="css-truncate expandable"><span class="css-truncate-target text-normal ml-1" style="max-width:175px;">(Here, Username)</span></span>

</strong> (<bdo class="css-truncate d-inline-block"><span class="css-truncate-target" style="max-width: 200px;">Here, Username</span></bdo>) <a href="#issue-25681" id="pullrequest-25681-permalink" class="link-gray js-timestamp"><relative-time datetime="2021-06-18T13:55:29Z" class="no-wrap" title="Jun 18, 2021, 9:55 AM EDT">4 days ago</relative-time></a>

<span class="js-comment-edit-history">
</span>
</h3>
```

**Comment by busches** [comment] 2021-10-12 02:34
I cannot recreate this in a private org and have never seen it happen on GHE. If someone can reliably recreate it, that would be ideal.

**Comment by fregante** [comment] 2021-12-03 17:02
Closing as too niche of a bug. If someone sees this, please send a PR, we can't fix it on our own.

**Closed by fregante** 2021-12-03 17:02 UTC
Labels: bug, help wanted, good first issue

**Comment by fregante** [comment] 2024-02-02 09:26
Fixed in 24.2.2 🎉
