### ISSUE TITLE
Filter repository workflows list

### ISSUE THREAD

**Issue by TPXP** [refined-github/refined-github#7766] opened 2024-08-28 14:07 UTC
### Description

Hello,

I'm working on a repository with many Github Actions Workflows (in my case, it's actions updating IAC infrastructure and we have one workflow per deployed component to speed up terraform). Whenever I want to check the state of the last run for a given workflow, I need to go through Github's actions pagination which requires many clicks on the "Show more workflows" link. I would prefer to be able to filter workflowsw by name (or manifest file) and open it directly in a similar fashion as Github's file finder. A "Show all workflows" button could also work.

<img width="539" alt="Capture d’écran 2024-08-28 à 16 03 08" src="https://github.com/user-attachments/assets/0ae2d4f9-a300-41be-9ab8-768c2fee2e1e">

*My writing is terrible - it says: To find the "Template" workflow, I need to click here many times :(*

### Example URLs

I can't share the repository I'm facing this on, but here's a repository with many github actions workflow - looking for the "Template" workflow on the left column requires clicking on the "Show more workflows" button many times. https://github.com/TPXP/repo-with-many-workflows/actions

**Comment by fregante** [comment] 2024-08-28 14:14
Duplicate of https://github.com/refined-github/refined-github/issues/6985

**Comment by TPXP** [comment] 2024-08-28 14:36
Thanks for the prompt response, sorry I missed the other discussion.

I think using many conditional jobs would make it quite difficult to know which part was run from the runs list (especially for cron jobs since the run name is the workflow name). Another use case I can find is a large monorepo with many microservices, each build separately.

`gh-cli` works, but I couldn't find an easy way to achieve this on the Web interface, which is the one I'm using the most frequently.

**Comment by fregante** [comment] 2024-08-28 14:45
I’d advise to just write a user script to look for and click that button if it exists. It’s too niche for Refined GitHub

**Closed by fregante** 2024-08-28 14:45 UTC
Labels: enhancement, under discussion

**Comment by TPXP** [comment] 2024-08-28 14:47
Got it, thanks for your answer 👍
