### ISSUE TITLE
Not working on GitHub Enterprise

### ISSUE THREAD

**Issue by chunming08** [refined-github/refined-github#6659] opened 2023-05-17 12:10 UTC
With the latest version installed, features become not working on GitHub Enterprise, like
- one-click-review-submission
- pr-branch-auto-delete
- table-input
- ...

Even if after clicking the feature toggle off and on, it would become not work again after switching between pages.

Any thoughts? Anyone has a similar issue? A bug?

**Comment by fregante** [comment] 2023-05-17 12:24
What browser? Have you tried closing the browser and opening it again?

cc @busches

**Comment by busches** [comment] 2023-05-17 12:42
I have to disable and enable the entire extension occasionally, but I'm not able to determine why. My guess is it's a memory issue and chrome is pausing it or it's a corporate policy being applied that isn't playing nice.

**Comment by fregante** [comment] 2023-05-17 13:12
Duplicate of https://github.com/refined-github/refined-github/issues/6025

**Closed by fregante** 2023-05-17 13:12 UTC
Labels: bug, under discussion, enterprise
