### ISSUE TITLE
Use `<input type="color" />` on color type input fields (new label / edit label)

### ISSUE THREAD

**Issue by samueldr** [refined-github/refined-github#7969] opened 2024-10-27 21:16 UTC
### Description

Using the inspector to change **only** the input type to color, at least under firefox the resulting values are directly compatible with the semantics of the field for saving the color. So at the very least there's not that much fighting to do with the current github.

```diff
- <input required="" aria-describedby="label--color-error" value="#5319e7" type="text" name="label[color]" id="label-color-" class="form-control input-monospace pb-1 mr-0 js-new-label-color-input width-full" maxlength="7" autocomplete="off" spellcheck="off" pattern="#?([a-fA-F0-9]{6}|[a-fA-F0-9]{3})" title="Hex colors should only contain numbers and letters from a-f">
+ <input required="" aria-describedby="label--color-error" value="#5319e7" type="color" name="label[color]" id="label-color-" class="form-control input-monospace pb-1 mr-0 js-new-label-color-input width-full" maxlength="7" autocomplete="off" spellcheck="off" pattern="#?([a-fA-F0-9]{6}|[a-fA-F0-9]{3})" title="Hex colors should only contain numbers and letters from a-f">
```

Challenges(?) to handle after would be:

 - I suppose, fixing whatever `onchange` handlers that update the color in the related DOM elements
 - Removing the default suggestions on activation

### Example URLs

 - `https://github.com/<org>/<repo>/labels`
 - https://github.com/refined-github/refined-github/labels

**Comment by fregante** [comment] 2024-10-28 03:22
Duplicate of https://github.com/refined-github/refined-github/issues/2224

**Closed** 2024-12-02 08:40 UTC
Labels: enhancement, under discussion
