### ISSUE TITLE
PRs: move checks info to sidebar

### ISSUE THREAD

**Issue by armcknight** [refined-github/refined-github#6770] opened 2023-07-14 02:12 UTC
### Description

Refined GitHub already does a great job of improving the checks display at the bottom of a PR! But, having to scroll to the bottom to see them gets repetitive. 

It would be nice to have them immediately visible upon entering a PR page. Either a compacted view in the sidebar, or a summary like "all checks passed" or a listing of only failed/skipped checks in the sidebar, somewhere amongst the assignees/labels/milestones/etc. 

Alternatively, it could be tacked onto the end of the PR description, or even above the conversation/commits/checks/files changed tabs.

### Example URLs

https://github.com/refined-github/refined-github/pull/3007

I would like to be able to see the checks information without having to scroll anywhere upon visiting such a PR.

**Comment by fregante** [comment] 2023-08-27 14:19
Duplicate of https://github.com/refined-github/refined-github/issues/4086

**Closed by fregante** 2023-08-27 14:19 UTC
Labels: enhancement, under discussion
