### ISSUE TITLE
"Draft a new release" button is wrapped

### ISSUE THREAD

**Issue by blakegearin** [refined-github/refined-github#7375] opened 2024-05-28 21:15 UTC
### Description

The "Draft a new release" button is being wrapped onto a new line instead of being in-line. I started encountering this a week or two ago.

![image](https://github.com/refined-github/refined-github/assets/17950836/5ca2ffcf-b3b2-4b51-92cb-f23437f5a801)

### How to replicate the issue + URL

I believe this buttons only show up when you have access to releases on the repo. So unless someone has created a repo giving every GitHub user release permissions, I don't think it's possible for me to find a public URL.

https://github.com/SVGtoPPT/svgtoppt

### Extension version

24.4.9

### Browser(s) used

Arc

**Comment by fregante** [comment] 2024-05-30 14:56
Duplicate of https://github.com/refined-github/refined-github/issues/7268

**Closed by fregante** 2024-05-30 14:56 UTC
Labels: bug, help wanted
