### ISSUE TITLE
Cannot save custom css in iOS Safari version Refined GitHub extension

### ISSUE THREAD

**Issue by erbanku** [refined-github/refined-github#5056] opened 2021-11-08 04:20 UTC
The added custom css disappears after refreshing.

![image](https://user-images.githubusercontent.com/79493862/140683795-d4216293-c5c6-4696-9d36-aed774e787bc.jpeg)

**Comment by fregante** [comment] 2021-11-08 22:29
Duplicate of https://github.com/refined-github/refined-github/issues/4823

**Closed by fregante** 2021-11-08 22:29 UTC
Labels: bug, under discussion
