### ISSUE TITLE
Excessive box shadow in dark mode

### ISSUE THREAD

**Issue by willdurand** [refined-github/refined-github#7305] opened 2024-03-19 20:28 UTC
### Description

In dark mode on Firefox Release 124, when navigating to https://github.com/notifications, there is a new excessive box shadow added by this style: https://github.com/refined-github/refined-github/blob/5e2f132d99a9ea3825cc5f01d19f0c38d3460c12/source/features/sticky-notifications-actions.css#L2

<img width="1272" alt="Screenshot 2024-03-19 at 21 18 49" src="https://github.com/refined-github/refined-github/assets/217628/2559c8a2-7a61-4e2f-a751-021f58abdba8">

I just updated from Firefox 123 to 124, I am not sure the add-on has been updated along the way (I doubt it since the add-on was last updated a month ago). Nothing else has changed.

### How to replicate the issue + URL

Browse https://github.com/notifications in dark mode on Firefox Release 124.

### Extension version

24.2.8

### Browser(s) used

Firefox Release 124.0

**Comment by jdreesen** [comment] 2024-03-19 20:53
I think it's GitHub that changed. Several plugins broke today.

Possibly a duplicate of #7304.

**Comment by tjhorner** [comment] 2024-03-19 21:51
Confirmed on Chrome 122.0.6261.129 too and it appears the shadow is added by the same declaration @willdurand linked

<img width="307" alt="image" src="https://github.com/refined-github/refined-github/assets/2646487/c41a32e4-82ca-46e9-abad-20bfca6d4899">

**Closed** 2024-03-20 00:30 UTC
Labels: bug
