### ISSUE TITLE
`warning-for-disallow-edits`: Doesn't display warning

### ISSUE THREAD

**Issue by omnigenous** [refined-github/refined-github#7608] opened 2024-07-27 15:46 UTC
### Description

https://github.com/user-attachments/assets/e2fa3657-f000-4e51-8557-eb06a0d18b18

### How to replicate the issue + URL

1. Open any PR
2. Toggle `Allow edits by maintainers` button
3. See _no_ warning when button is off

### Extension version

24.7.23

### Browser(s) used

Librewolf

**Comment by omnigenous** [comment] 2024-07-27 15:47
Can only play `video.mp4` in chromium. Not sure why

**Comment by fregante** [comment] 2024-07-27 16:38
Duplicate of https://github.com/refined-github/refined-github/issues/7574

**Comment by fregante** [comment] 2024-07-27 16:38
Thanks for the report!

This has actually been fixed already but not released yet. 

- https://github.com/refined-github/refined-github/issues/7574

**Closed by fregante** 2024-07-27 16:38 UTC
Labels: bug
