### ISSUE TITLE
Keep outdated comments in the "Files changed" view

### ISSUE THREAD

**Issue by davvelar** [refined-github/refined-github#7255] opened 2024-02-08 14:42 UTC
### Description

Gerrit, Bitbucket, Azure DevOps and others all have anchored review comments that remain even if the line they point to gets changed or removed, but Github simply removes the comment and marks it as "outdated", so it's not visible in "Files changed" anymore. This makes reviewing very cumbersome since you have to move between the "Files changed" and "Conversation" tabs to make sure all your comments have been adressed when making a second review. Default should be to keep the comment in the "Files changed" view until resolved.

The Github issue in question: https://github.com/orgs/community/discussions/23138

I've tested the scenario using Refined Github and it doesn't seem to be fixed, and I can't find it in your feature list, nor in open or closed issues when searching for it. Maybe it's something you would consider fixing?

Best regards

### Example URLs

https://github.com/lee-dohm/test-repo/pull/6/files

**Comment by fregante** [comment] 2024-02-08 15:00
Duplicate of https://github.com/refined-github/refined-github/issues/7048

**Closed by fregante** 2024-02-08 15:00 UTC
Labels: enhancement, under discussion
