### ISSUE TITLE
`quick-pr-diff-options` lightly conflicts with native "Show whitespace" button

### ISSUE THREAD

**Issue by cheap-glitch** [refined-github/refined-github#5009] opened 2021-10-29 13:13 UTC
### Please ensure:

- [X] The bug is caused by Refined GitHub. It doesn't happen if I disable the extension.

### Include in this issue:

- [X] Screenshots/video/gif demonstrating the bug, if it’s visual
- [ ] Console errors, if any

### Description

GitHub introduced a persistent "Show whitespace" (as in "whitespace changes") setting: https://github.blog/changelog/2021-10-14-hiding-whitespace-is-now-remembered-for-each-pull-request.

`quick-pr-diff-options` should either hide the native button or not inject its own.

![image](https://user-images.githubusercontent.com/46634000/139441104-cc33c2ea-3cd6-439b-8a67-5035a95c00b4.png)

### Example URL

https://togithub.com/refined-github/github-sandbox/pull/4/files?w=1

### Browser(s) used

Firefox

**Comment by kidonng** [comment] 2021-10-30 00:29
> This doesn't replace our feature because it's only visible when the whitespace is hidden. They only implemented a shortcut/indicator that the whitespace is hidden.

I'm not saying it _replaces_ our feature, since it requires 3 clicks and a hard reload to change a setting, while ours only requires one click and no hard reload.

I think ideally we should:

- Don't show our "Hide whitespace" button in light of the native one
- Make our "Show whitespace" button look like the native "Hide whitespace" one
- Optionally match the look of split diff button with the "Hide whitespace" one, or maybe only keep the icon and drop the text from whitespace button
- Our buttons should also send a request to make GitHub remember its options, just like the native one. 

There is a related bug: if you changed the options with native controls, our buttons won't reflect the real state since it doesn't look at the DOM. That should be fixed as well.

**Comment by fregante** [comment] 2021-10-31 17:16
> * Make our "Show whitespace" button look like the native "Hide whitespace" one

Not sure how. Their icon is just an eye, which we're already using for comments and it's too generic already.



> * Optionally match the look of split diff button with the "Hide whitespace" one, or maybe only keep the icon and drop the text from whitespace button

Not sure I understand. Mockup?

**Comment by kidonng** [comment] 2021-10-31 19:21
Yup, #5022 doesn't fix duplicate buttons on [`isSingleCommit`](https://github.com/refined-github/refined-github/commit/49fd6261e21d69bd62094bf0b38783a7e06020d1):

![image](https://user-images.githubusercontent.com/44045911/139598291-28f8caa3-ebd1-466f-bed1-00151e4dc2c2.png)

...and [`isCompare`](https://github.com/refined-github/refined-github/compare/main...add-multiple-prs-dropdown):

![image](https://user-images.githubusercontent.com/44045911/139598284-946a03ca-3df8-470a-aa16-a52f62a64ba7.png)

**Comment by fregante** [comment] 2021-10-31 19:32
> Yup, #5022 doesn't fix duplicate buttons on [`isSingleCommit`](https://github.com/refined-github/refined-github/commit/49fd6261e21d69bd62094bf0b38783a7e06020d1):

Time to open a new issue, that was never mentioned here 😃

**Comment by cheap-glitch** [comment] 2021-11-29 21:04
Hasn't this been completely fixed already? If not, what is there left to do?

**Comment by kidonng** [comment] 2021-11-29 21:11
The conflict is indeed "fixed" (skipped), but our buttons ought to do better than now.

**Comment by fregante** [comment] 2022-05-22 11:50
Can no longer reproduce, I assume it was fixed

![gif](https://user-images.githubusercontent.com/1402241/169693783-2bd081ee-5a70-468b-8ead-88b2335129ad.gif)

**Closed by fregante** 2022-05-22 11:50 UTC
Labels: enhancement, help wanted
