### ISSUE TITLE
`repo-age` alignment in repositories

### ISSUE THREAD

**Issue by Yash-Singh1** [refined-github/refined-github#4594] opened 2021-07-20 22:46 UTC
### Please ensure:

- [X] The bug is caused by Refined GitHub. It doesn't happen if I disable the extension.

### Description

Sometimes the repository age appears on top of the description of the repository.

Reproduction:

- Keep reloading a repository's page
- Notice how sometimes the age is on top of the description

It doesn't work on some repositories. I noticed it on mine: https://github.com/Yash-Singh1/react-thermometer-range-component.

### Screenshot

![Screenshot from 2021-07-20 15-40-52](https://user-images.githubusercontent.com/53054099/126404741-e054b633-97b1-4f77-a9a0-55288cf179ae.png)

### Console errors

```shell
None
```

### Example URL

https://github.com/Yash-Singh1/react-thermometer-range-component

### Browser(s) used

Chrome

**Comment by Yash-Singh1** [comment] 2021-10-12 02:32
I could still reproduce this:

![Screenshot from 2021-10-11 19-30-17](https://user-images.githubusercontent.com/53054099/136881111-f948611f-f6f9-4fa6-ae6d-aac2a24d9123.png)

Tested on Chrome 92.0.4515.159, and 21.10.4 for Refined GitHub.

**Comment by busches** [comment] 2021-10-12 02:48
@Yash-Singh1 Ha, this laptop is crap. I am on Chrome 94 and Windows though?

**Comment by Yash-Singh1** [comment] 2021-10-12 03:57
I’ll try updating my chrome version to 94. Shouldn’t be related but I am on Ubuntu.

**Comment by fregante** [comment] 2021-10-16 08:45
By looking at our code, the only way this could happen is if GitHub appended the content _after_ we did, for example via deferred loading.

We _could_ user a MutationObserver on the parent to see when new elements are added (once), but this feels rare enough to almost make it not worth it. Even testing a solution would be next to impossible.

**Comment by yakov116** [comment] 2022-07-05 17:38
I just tried this and I am not seeing it.

@kidonng can you still reproduce?

**Comment by kidonng** [comment] 2022-07-05 18:25
I think I still see this for a few times some months ago. We can close this since it's not particular troublesome, but it's something we should be aware.

**Closed** 2022-07-05 19:04 UTC
Labels: bug, help wanted
