### ISSUE TITLE
Add prev/next buttons to 'Group by: Repository' and/or show all notifications when grouped in /notifications

### ISSUE THREAD

**Issue by 0xdevalias** [refined-github/refined-github#6275] opened 2023-01-31 21:15 UTC
### Description

In `/notifications`, when the `Inbox` filter/view is selected, we can use the 'Group by' dropdown to select 'Repository'; which will group the notifications by repository (rather than just being ordered by date)

However, when 'Group by: Repository' is chosen, there is no prev/next button shown at the bottom of the page anymore, to be able to show more notifications; and the page doesn't show 100% of my outstanding notifications within the existing groups.

Ideally we would be able to do one or both of the following when 'Group by: Repository' is selected:

- see all notifications within the groups (so there is no need to click between multiple pages)
- see prev / next buttons (similar to what is shown when 'Group by: Date' is selected) so that we can change pages to see more notifications

### Screenshot

![image](https://user-images.githubusercontent.com/753891/215883928-55f7d994-9c59-404f-b59d-c822fb5b5139.png)

![image](https://user-images.githubusercontent.com/753891/215884780-ffb2911d-db52-4a57-800f-c1cf77e152df.png)

![image](https://user-images.githubusercontent.com/753891/215884844-2e2ccdd9-a55b-4031-ae9e-41a7b6ac7718.png)

### Example URLs

https://github.com/notifications

### See Also

My other `/notifications` feature requests:

- https://github.com/refined-github/refined-github/issues/6272
- https://github.com/refined-github/refined-github/issues/6273
- https://github.com/refined-github/refined-github/issues/6274
- https://github.com/refined-github/refined-github/issues/6276

**Comment by fregante** [comment] 2023-02-01 01:21
Duplicate of https://github.com/refined-github/refined-github/issues/6186

**Closed** 2023-02-01 01:24 UTC
Labels: enhancement, under discussion

**Comment by 0xdevalias** [comment] 2023-02-01 23:04
> Duplicate of #6186

I wouldn't say duplicate.. there are definite differences between that issue and this one. They are related for sure though.

> The "next" button is already shown by GitHub: it's "load more"

Where? Because I have literally never seen 'load more', and if I had, I likely would have never spent the time to articulate this request.

**Comment by fregante** [comment] 2023-02-02 01:08
"View all 129 notifications" is equivalent to "next"

**Comment by 0xdevalias** [comment] 2023-02-02 22:39
> "View all 129 notifications" is equivalent to "next"

That's not really accurate though. That will show the additional notifications for that repo, sure; and that's fine.

But if I have notifications that aren't grouped into the first set of repo's that are shown, they are never shown on this 'Group By: Repository' view.

> but for the reasons explaining in the other issue, that's not something we can do anything about

Disappointing, but understandable.
