### ISSUE TITLE
Show a label/icon next to each setting that requires a token

### ISSUE THREAD

**Issue by tupaschoal** [refined-github/refined-github#4950] opened 2021-10-21 03:35 UTC
### Description

When configuring the extension we have the link ["some features"](https://github.com/refined-github/refined-github/search?q=github-helpers+api) that takes the user to a search of all the features that require one or more of the permissions of the token to be set.

Though it works, it's a bit tedious to scroll through them all, and it would be good if the list itself hinted on that. I myself thought I had found multiple buggy features until I decided to double check my token.

### Screenshot

Very bad mockup examples

Current:
![image](https://user-images.githubusercontent.com/6443427/138206583-badd9b3d-868f-48c4-8609-50f5fac2774b.png)

When required token/token option is missing:
![image](https://user-images.githubusercontent.com/6443427/138207007-a3551fe1-92fa-421b-9bc6-42819a0c6c28.png)

When required token/token option is granted:
![image](https://user-images.githubusercontent.com/6443427/138207041-564aa295-f407-41df-b9b6-22e5e30f4b6d.png)

### Example URL

chrome://extensions/?options=hlepfoohegkhhmjieoechaddaejaokhf

**Comment by kidonng** [comment] 2021-10-21 03:39
It would be ideal if we can label all of them, but they are quite a lot:

```
$ rg --files-with-matches api | wc -l
      49
```

**Comment by tupaschoal** [comment] 2021-10-21 03:43
I can think of different solutions too:
- Start them disabled, until token is granted (and not allow them to be selected if token is not there, showing helpful tooltip)
- Allow to filter the list by ones needing token or split the list in two (this last one looks bad)

**Comment by yakov116** [comment] 2021-10-21 03:52
This was spoken about many times do a simple search. Ex. #3217

**Comment by fregante** [comment] 2021-10-31 16:40
Duplicate of #3217

**Closed by fregante** 2021-10-31 16:40 UTC
Labels: enhancement, under discussion

**Comment by kidonng** [comment] 2021-10-31 17:20
> Those features are already automatically disabled when the token is missing

Well, if you call that _disabled_... There is still room in improving this AFAIT.
