### ISSUE TITLE
Add discussions to global nav

### ISSUE THREAD

**Issue by KaKi87** [refined-github/refined-github#6449] opened 2023-04-04 17:58 UTC
### Description

Global nav includes links to [github.com/pulls](https://github.com/pulls) & [github.com/issues](https://github.com/issues) but not [github.com/discussions](https://github.com/discussions), which this feature would fix.

Before :

![screenshot-github com-2023 04 04-19_55_52](https://user-images.githubusercontent.com/21284089/229878114-ffd64eea-3d6b-49ec-863e-5f7ad211a168.png)

After :

![screenshot-github com-2023 04 04-19_56_50](https://user-images.githubusercontent.com/21284089/229878111-abe611bc-46b6-4b67-9170-cc3f4d006558.png)

### Example URLs

https://github.com

---

Thanks

**Comment by fregante** [comment] 2023-04-05 02:54
You can create a browser bookmark for that

**Comment by fregante** [comment] 2023-04-05 02:55
Duplicate of https://github.com/refined-github/refined-github/issues/6062

**Closed by fregante** 2023-04-05 02:55 UTC
Labels: enhancement, under discussion
