### ISSUE TITLE
hide all deployments events by default

### ISSUE THREAD

**Issue by shayaantx** [refined-github/refined-github#6928] opened 2023-09-18 18:27 UTC
### Description

Hello,

I notice in a repo I use where we are constantly deploying (they are not inactive deployments) to test environments, the deployment events continue to show. It gets very noisy very quickly (since there are many jobs with their own deployments), below is just a snippet of just 2 (but in my case its more like every push 7 events get added.

I know there is an activity filter that hides events or events/comments, this works great, but it doesn't persist.

It would be nice if we could just hide deployment events in general (seems trivial looking at hide-inactive-deployments.tsx, I can put it up for PR for it). The other possibility was maybe persisting the activity filter?

![image](https://github.com/refined-github/refined-github/assets/5449086/c965b498-cce8-4ce6-9193-812922c33cf2)

### Example URLs

n/a

**Comment by fregante** [comment] 2023-09-19 03:02
Duplicate of https://github.com/refined-github/refined-github/issues/6742#issuecomment-1596178561

**Closed by fregante** 2023-09-19 03:02 UTC
Labels: enhancement, under discussion

**Comment by shayaantx** [comment] 2023-09-19 13:53
@fregante appreciate the response, I tried 
```
event:has(deploy-icon) + event:has(deploy-icon) {
  margin-top: -2em
}
```

but it didn't seem to work, I wrote this instead which works for me

```
div.js-timeline-item div.js-socket-channel[data-url*="deployed_event"] {
	display: none !important;
}
```
