### ISSUE TITLE
fit-textarea causing significant slow down when adding PR review comments

### ISSUE THREAD

**Issue by gmaclennan** [refined-github/refined-github#4266] opened 2021-04-22 10:34 UTC
Browser: Safari 14.0.3
Example URL: https://github.com/digidem/mapeo-mobile/pull/566/files#

When reviewing a PR and adding a code comment with multiple lines, refined github causes a slowdown that results in a typing appearing on the screen a second or so after keys are pressed.

I ran the profiler on the page and identified that each keypress is calling the `fitTextArea()` function and takes ~5ms.

Turning off the fit-textarea feature resolves the problem and typing is not delayed any more.

**Comment by yakov116** [comment] 2021-04-22 10:38
Will be fixed in the next release

**Comment by fregante** [comment] 2021-04-22 10:49
Confirmed and hopefully it will be fixed in the next release. I don’t know when that’ll happen in Safari because releases aren’t automated there yet #3686

**Comment by fregante** [comment] 2021-04-22 10:50
For the time being, yes, disabling the feature is highly advised. I had to do the same for the past few months.

**Comment by fregante** [comment] 2021-06-06 07:26
We had to re-enable it due to https://github.com/sindresorhus/refined-github/issues/4275 unfortunately

**Comment by fregante** [comment] 2023-02-11 10:54
Closing because of  #4447

I'd basically need to rewrite or replace `fit-textareas` to enable the feature everywhere:

- https://github.com/fregante/fit-textarea/issues/21

**Closed by fregante** 2023-02-11 10:54 UTC
Labels: bug, safari
