### ISSUE TITLE
Side bar not docked when browser zoom is too large

### ISSUE THREAD

**Issue by bartgol** [refined-github/refined-github#7925] opened 2024-10-17 15:39 UTC
### Description

I'm not sure if this is a bug or a feature, but either way. I noticed that when scrolling down an issue or PR page, the right bar (with labels, assignee, milestone, projects, etc) does is not always locked. In particular, if the browser zoom is low (meaning small fonts) the bar seems to be locked, while if the zoom is high (meaning large fonts) the bar does not stay there, and you need to scroll up to, say, go check/set/unset labels.

This is quite inconvenient for folks that need a large zoom due to eyesight problems. While I can get away with small fonts on my office computer with a large monitor, my laptop is small, and I tend to zoom in a lot. And for long conversations, it takes a lot of scrolling to go back to the top.

### How to replicate the issue + URL

I don't think the particular repo matters, but just to fill this box, this is the page I was on just now: https://github.com/E3SM-Project/scream/pull/3005.

Attached are two screenshot with large/small font, showing the difference
![gh-small-font](https://github.com/user-attachments/assets/8d235d77-9e63-4ad0-bdc5-516076397089)
![gh-large-font](https://github.com/user-attachments/assets/4c10ed60-4eb6-4564-9ff7-9950a5c81d8e)

### Extension version

24.10.14

### Browser(s) used

Chrome Version 127.0.6533.99 (Official Build) (64-bit)

### Token ⚠️

- [X] I set a token in the options page. I understand that some features require a token to work.

**Comment by fregante** [comment] 2024-10-17 16:26
Duplicate of https://github.com/refined-github/refined-github/issues/6338

**Closed by fregante** 2024-10-17 16:26 UTC
Labels: bug

**Comment by bartgol** [comment] 2024-10-17 16:46
Ah, I see. Thanks for pointing me to that issue!
