### ISSUE TITLE
`small-user-avatars` needs more spacing before a user mention

### ISSUE THREAD

**Issue by NoahAndrews** [refined-github/refined-github#7002] opened 2023-10-27 19:06 UTC
### Description

The avatar starts significantly closer to the previous word than a normal letter would, which looks especially bad when the user mention is the first word of a new sentence.

Zoomed in using Windows Magnifier at 600%, with a vertical line added:
![image](https://github.com/refined-github/refined-github/assets/10224994/d9a55bc5-9bc5-4524-ac17-69d004c994de)

Zoomed at 110% using Firefox:
![image](https://github.com/refined-github/refined-github/assets/10224994/021769b0-982a-4f03-a3d6-63381612a164)

### How to replicate the issue + URL

https://github.com/electron/forge/pull/3391#issue-1965984062

### Extension version

23.10.5

### Browser(s) used

Firefox

**Comment by fregante** [comment] 2023-10-28 02:38
Great, yes! Let's try to add it via `' '` instead of CSS, because margins still apply when the mention appears at the beginning of the line

**Comment by Katsute** [comment] 2023-10-29 17:19
Caused by 

https://github.com/refined-github/refined-github/blob/4a9e021202ceb76962d08d70ecab2ec9becab8d9/source/features/small-user-avatars.css#L3

Can be resolved by removing `.rgh-small-user-avatars` from user mention avatars

https://github.com/refined-github/refined-github/blob/4a9e021202ceb76962d08d70ecab2ec9becab8d9/source/features/small-user-avatars.tsx#L31

**Comment by Katsute** [comment] 2023-10-29 18:03
> Great, yes! Let's try to add it via `' '` instead of CSS, because margins still apply when the mention appears at the beginning of the line

Margin is actually needed because the image bleeds out of the element, putting it before the start line

![image](https://github.com/refined-github/refined-github/assets/58778985/7f5362a9-07e7-4b98-9d75-be1d6bb43fb8)

![image](https://github.com/refined-github/refined-github/assets/58778985/b9feb0d7-c17b-4450-a90c-7b6da1f4486a)

**Closed** 2023-11-01 16:50 UTC
Labels: bug, help wanted, small
