### ISSUE TITLE
Table button is overflowing on mobile comment box

### ISSUE THREAD

**Issue by kyoyacchi** [refined-github/refined-github#7253] opened 2024-02-08 07:35 UTC
### Description

The table icon overflows in comment box, when i enable "table-input" option

### How to replicate the issue + URL

Example URL: https://github.com/refined-github/refined-github/issues/6988

enable "table-input"
This is with "table-input" enabled
![Screenshot_20240208-103011](https://github.com/refined-github/refined-github/assets/63583961/774beb1c-4c9f-4bec-a3e9-a5706fc66229)
And this is not:
![Screenshot_20240208-103041](https://github.com/refined-github/refined-github/assets/63583961/6b654085-3a68-47ab-80e3-96934fe4c911)

### Extension version

24.2.8

### Browser(s) used

Kiwi Browser

**Comment by fregante** [comment] 2024-02-08 09:25
Duplicate of #7236

**Closed by fregante** 2024-02-08 09:25 UTC
Labels: bug
