### ISSUE TITLE
Always display GitHub Status in the header

### ISSUE THREAD

**Issue by shiron-dev** [refined-github/refined-github#8153] opened 2024-12-12 08:54 UTC
### Description

I want to display the current GitHub service status on the header of every possible GitHub page. 
This will allow users to quickly identify if any or all parts of GitHub are down.

### Example URLs

https://www.githubstatus.com/

**Comment by fregante** [comment] 2024-12-12 10:01
Duplicate of https://github.com/refined-github/refined-github/issues/4653

**Closed by fregante** 2024-12-12 10:01 UTC
Labels: enhancement, under discussion
