### ISSUE TITLE
File previews broken due to lack of respect for user's `tab-size`

### ISSUE THREAD

**Issue by Lamparter** [refined-github/refined-github#6477] opened 2023-04-09 06:56 UTC
### Description

On XML based languages, Refined GitHub renders the code in weird ways:
Seemingly, it puts in more spacing than is usual, so there is a remain of the code in it's 'usual' state.
Not so sure about this one.
###### 📝 Note that this only occurs when selecting text.
Second of all, the text selector can only go to the end of the 'original' black text and not of the white one, so I cannot visually select the whole text.

**I have a video of this, but could not upload it to GitHub.**
![image](https://user-images.githubusercontent.com/71598437/230758815-ca1f3c50-8c40-458d-9efb-69ae19ca088c.png)
See:
https://riversidevalley-my.sharepoint.com/:v:/g/personal/lamparter_theriversi_de/EdcPsBJFcslMlVmICHSqgK0B_k0xd72Ep1hu9Tk35qFZoA?e=Dieyoo
This video is of https://github.com/files-community/Website/blob/cfcfa9098860261e4433eecc77ae80b2c0e8d281/src/i18n/locales/en-US.json

### How to replicate the issue + URL

Seemingly occurs in HTML/XML based languages, such as Svelte, XAML and of course, HTML, as well as JSON (a lot of web languages! but not Ruby); I have used the Refined GitHub feature identifier and it did not identify the problem, however disabling the Refined GitHub extension does fix the problem.

Example: https://github.com/RiversideValley/Website/blob/main/src/app.html
![image](https://user-images.githubusercontent.com/71598437/230758965-695678f3-c5c5-4e24-8602-6229d1aaf20b.png)

### Extension version

23.3.31

### Browser(s) used

Microsoft Edge Insider Dev

**Comment by fregante** [comment] 2023-04-09 07:48
This is likely a combination of:

- GitHub is playing with a hidden/duplicate element first [mentioned here](https://github.com/refined-github/refined-github/issues/6336#issuecomment-1498807645)
- your tab size is set to 8 characters
- our `tab-size` affects only the hidden element

As a temporary fix:

- you can [change your tab size](https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-personal-account-on-github/managing-personal-account-settings/managing-your-tab-size-rendering-preference) to 4 characters

**Comment by fregante** [comment] 2023-04-09 07:49
cc @kidonng

**Comment by fregante** [comment] 2023-04-09 07:53
I can replicate the issue because my tab size is also _not 4 characters_ and I have the new hidden element.

<img width="660" alt="Screenshot" src="https://user-images.githubusercontent.com/1402241/230760904-f987c263-c3be-44ea-98d5-25c7958ccf54.png">

<img width="648" alt="Screenshot 1" src="https://user-images.githubusercontent.com/1402241/230760964-5741da16-390a-4040-b657-da02e1261652.png">


I'll push a hotfix

**Comment by fregante** [comment] 2023-04-09 07:58
Hotfixed, no further action required on your part, just wait a few hours

**Comment by kidonng** [comment] 2023-04-09 09:55
Caused by

https://github.com/refined-github/refined-github/blob/154c0f8c86b23e52d1e1ee947b90bc36bc6188ba/source/features/tab-size.css#L3-L5

overriding

```html
<textarea
	id="read-only-cursor-text-area"
	style="tab-size: <what-you-set-in-your-preference>"
>
```

`*` is probably too wide. Just use more specific selector?

**Comment by fregante** [comment] 2023-04-09 10:10
> Just use more specific selector? 

Yeah back then we kept this to cover any situations that GitHub forgot:

- https://github.com/refined-github/refined-github/pull/5715

It seems that they still haven't been fixed. Maybe the new selector is just `.markdown-body pre`

**Comment by fregante** [comment] 2023-04-09 10:11
It seems that this was reported yesterday but I closed it as unreproducible: 

- https://github.com/refined-github/refined-github/issues/6461

**Comment by kidonng** [comment] 2023-04-09 10:29
We only really care tabs in two places:

- Code view (natively supported, both on main site and Gist)
- User content (`.markdown-body`)

Oh, maybe action logs?

**Comment by fregante** [comment] 2023-04-09 11:07
> * User content (`.markdown-body`)

I think yeah let's target this, like suggested in my previous comment.

> Oh, maybe action logs?

Would be ideal, but I don’t think it's common to print tabs in the console and **especially** not expecting them to be 8 characters, so probably it's best to not touch that.

**Closed** 2023-04-10 07:42 UTC
Labels: bug, help wanted

**Comment by Lamparter** [comment] 2023-04-12 06:08
Thanks!
