### ISSUE TITLE
Add a 'first' (and 'last'?) button to the 'prev' / 'next' buttons in /notifications

### ISSUE THREAD

**Issue by 0xdevalias** [refined-github/refined-github#6276] opened 2023-01-31 21:21 UTC
### Description

In `/notifications`, when using a filter other than 'Inbox', or using 'Inbox' with 'Group by: date' selected, at the bottom of the page we see 'prev' / 'next' buttons, to navigate between the pages of notifications.

When using Refined-GitHub, it seems as though the 'last' page is possible to be navigated to by clicking on the number of the highest notification count.

But when we are on a page other than the 'first' page of notifications, we're unable to jump back to the 'first' page.

It would be ideal if we had some way to jump back to this first page.

### Screenshot

Without Refined-GitHub:
![image](https://user-images.githubusercontent.com/753891/215885511-35a6a195-f174-4db6-887d-4a1f56d696f8.png)
![image](https://user-images.githubusercontent.com/753891/215885743-d298e29e-134e-4c73-b8ad-36f09ebfc22b.png)
![image](https://user-images.githubusercontent.com/753891/215885790-7d286815-53d4-4c39-8660-6f6c64bf61c5.png)

With Refined-GitHub:
![image](https://user-images.githubusercontent.com/753891/215885125-9245624d-8e19-4da7-abdc-ceb0beecefbb.png)
![image](https://user-images.githubusercontent.com/753891/215885881-96f08baf-0569-4340-91f9-fa339c2824ff.png)
![image](https://user-images.githubusercontent.com/753891/215885927-a033fad1-ef73-4fc0-8cb5-d85f8ea05aaa.png)

### Example URLs

https://github.com/notifications

### See Also

My other `/notifications` feature requests:

- https://github.com/refined-github/refined-github/issues/6272
- https://github.com/refined-github/refined-github/issues/6273
- https://github.com/refined-github/refined-github/issues/6274
- https://github.com/refined-github/refined-github/issues/6275

**Comment by fregante** [comment] 2023-02-01 01:17
Duplicate of https://github.com/refined-github/refined-github/issues/6126

**Closed by fregante** 2023-02-01 01:17 UTC
Labels: enhancement, under discussion

**Comment by 0xdevalias** [comment] 2023-02-01 23:08
> And the "first page" button just means you have to re-visit the current page, which either means it's the "inbox" link in the sidebar or, in any scenario, you can click in the search box and press enter.

@fregante Why is a convoluted and disconnected experience compared to using the existing navigation, of which you already provide the 'last'. Your answer here is akin to a workaround at best. If that's the way we are approaching 'refinements' to GitHub, then literally everything this extension does could be solved in a similar "just use this convoluted workaround" way.. Sub-par answer tbh. Particularly for what would be a trivially tiny amount of code to implement on top of the existing 'last'.

**Comment by fregante** [comment] 2023-02-02 01:05
We have 250+ refinements and GitHub is fighting us daily by changing the layout and by dropping classes, making it difficult to target anything. Every feature we add we have to support forever, they're not "free". This is why I'm not adding a button for something that exist and is not convoluted at all, it just exists 700px away. There are better refinements on which I will spend my time

**Comment by fregante** [comment] 2023-02-02 07:33
This feature is not that difficult to implement, actually. If you're willing to extend `last-notification-page-button` I'll accept your PR. It should look like this, probably:

<img width="321" alt="Screenshot" src="https://user-images.githubusercontent.com/1402241/216260005-a4ca3375-b504-4d6e-aa37-9dd62556b918.png">

The chevrons: «»

**Comment by 0xdevalias** [comment] 2023-02-02 22:44
> This feature is not that difficult to implement, actually. If you're willing to extend [`last-notification-page-button`](https://github.com/refined-github/refined-github/blob/main/source/features/last-notification-page-button.tsx) I'll accept your PR.

@fregante Shall look into it :)

**Comment by 0xdevalias** [comment] 2023-02-04 23:37
@fregante Given this is now an acceptable idea.. can you please re-open this issue to reflect that.

**Comment by fregante** [comment] 2023-02-05 02:00
I'll accept your PR, but I'm not going to track it until then

**Comment by 0xdevalias** [comment] 2023-02-05 03:18
@fregante That is so counterintuitive to how open source works.. _sigh_ But sure.. you run your repo how you want to... 🙄😮‍💨
