### ISSUE TITLE
`clean-repo-tabs`: menuItem is undefined

### ISSUE THREAD

**Issue by yarub123** [refined-github/refined-github#7371] opened 2024-05-23 02:36 UTC
### Description

```
onlyShowInDropdown@moz-extension://779573b7-ea92-4c01-95f4-da4859d4193d/assets/refined-github.js:11401:7
init@moz-extension://779573b7-ea92-4c01-95f4-da4859d4193d/assets/refined-github.js:11462:27
async*setupPageLoad/runFeature/<@moz-extension://779573b7-ea92-4c01-95f4-da4859d4193d/assets/refined-github.js:4060:28
setupPageLoad/runFeature/<@moz-extension://779573b7-ea92-4c01-95f4-da4859d4193d/assets/refined-github.js:4056:72
setupPageLoad/runFeature/<@moz-extension://779573b7-ea92-4c01-95f4-da4859d4193d/assets/refined-github.js:4056:45
runFeature@moz-extension://779573b7-ea92-4c01-95f4-da4859d4193d/assets/refined-github.js:4057:10
setupPageLoad@moz-extension://779573b7-ea92-4c01-95f4-da4859d4193d/assets/refined-github.js:4072:43
async*add@moz-extension://779573b7-ea92-4c01-95f4-da4859d4193d/assets/refined-github.js:4098:33
async*@moz-extension://779573b7-ea92-4c01-95f4-da4859d4193d/assets/refined-github.js:11439:21
@moz-extension://779573b7-ea92-4c01-95f4-da4859d4193d/assets/refined-github.js:12476:5
@moz-extension://779573b7-ea92-4c01-95f4-da4859d4193d/assets/refined-github.js:12477:3
```

### How to replicate the issue + URL

https://github.com/catppuccin/iterm/tree/main/colors

### Extension version

24.4.9

### Browser(s) used

Floorp

**Comment by fregante** [comment] 2024-06-03 06:33
Duplicate of https://github.com/refined-github/refined-github/issues/7140

**Closed by fregante** 2024-06-03 06:33 UTC
Labels: bug
