### ISSUE TITLE
monospace-textareas is now native in GitHub

### ISSUE THREAD

**Issue by AaronDewes** [refined-github/refined-github#4945] opened 2021-10-19 21:05 UTC
The feature previously provided by `monospace-textareas` is now an option in GitHub: https://github.blog/changelog/2021-10-12-fixed-width-font-support-in-markdown-enabled-fields/

I assume this could be removed from this plugin because of that.

**Comment by yakov116** [comment] 2021-10-19 21:08
Duplicate of #4917

**Closed by yakov116** 2021-10-19 21:08 UTC
Labels: under discussion
