### ISSUE TITLE
`default-branch-button` does not work with long branch names that are truncated in the UI

### ISSUE THREAD

**Issue by gamemaker1** [refined-github/refined-github#5240] opened 2021-12-23 12:13 UTC
### Please ensure:

- [X] The bug is caused by Refined GitHub. It doesn't happen if I disable the extension.

### Include in this issue:

- [ ] Screenshots/video/gif demonstrating the bug, if it’s visual
- [ ] Console errors, if any

### The Problem

Press the `default-branch-button` in the example url, and it will redirect you to [`https://github.com/gamemaker1/express-rate-limit/commits/opiniated-impr...`](https://github.com/gamemaker1/express-rate-limit/commits/opiniated-impr...). This is because the branch name is truncated in the `#branch-select-menu` div.

### Possible Fix

Change the selector in the `getDefaultBranch` helper function that retrieves the branch name from the UI:

https://github.com/refined-github/refined-github/blob/main/source/github-helpers/get-default-branch.ts#L26

From:

```ts
select('#branch-select-menu [data-menu-button]');
```

To:

```ts
select('#branch-select-menu [data-menu-button]:not(.css-truncate-target)');
```

So that it makes an API call and gets the default branch instead of using the truncated name from the UI (an alternative would be getting the branch from somewhere else in the DOM).

Not tested, but I think this should work.

### Example URL

https://github.com/gamemaker1/test/tree/very-very-long-long-long-long-branch-name

### Browser(s) used

Firefox

**Comment by kidonng** [comment] 2021-12-25 08:02
Example URL is 404.

**Comment by gamemaker1** [comment] 2021-12-25 08:03
Ahh sorry about that

**Comment by gamemaker1** [comment] 2021-12-25 08:05
Here is another one - https://github.com/gamemaker1/test/tree/very-very-long-long-long-long-branch-name

**Comment by kidonng** [comment] 2021-12-26 17:03
Cannot reproduce with the new example URL.

**Comment by yakov116** [comment] 2021-12-26 17:16
> Cannot reproduce with the new example URL. I don't even see [`default-branch-button`](https://github.com/refined-github/refined-github/blob/main/source/features/default-branch-button.tsx?rgh-link-date=2021-12-26T17%3A03%3A54Z) on `very-very-long-long-long-long-branch-name` branch (and it will be another issue if it does).

Because its the default branch...

**Comment by kidonng** [comment] 2021-12-26 17:30
@yakov116 that's what the example URL points to. Can anyone provide a _real_ buggy URL or better, screenshots/screencasts?

**Comment by gamemaker1** [comment] 2021-12-28 04:14
Sorry about the wrong example URLs :(

It happens _sometimes_ on this URL (commits page of a default branch) - https://github.com/gamemaker1/test/commits/very-very-long-long-long-long-branch-name - only when the `default-branch-button` shows up. And from what I understand, that is another bug - the `default-branch-button` should not show up on a page with the default branch.

I tried out #5246 and I don't see these issues anymore.

**Comment by fregante** [comment] 2021-12-28 15:13
Did you set the default branch to a long name at some point?

**Comment by gamemaker1** [comment] 2021-12-28 15:57
Yes, I did the change the default branch name before this happened. Maybe this happened because of a value in cache?

**Comment by fregante** [comment] 2021-12-29 06:01
That's why it happened. We have a few ways to figure out the default branch and one of them might be reading the truncated value somewhere. 

To fix this, we just need to verify all of these *ways*

**Comment by kidonng** [comment] 2021-12-29 07:20
I think this is already fixed in the associated PR.

**Closed** 2022-01-11 03:05 UTC
Labels: bug, help wanted
