### ISSUE TITLE
`tags-on-commits-list`: Cannot read properties of undefined (reading 'pathname')

### ISSUE THREAD

**Issue by jiaqiluo** [refined-github/refined-github#7691] opened 2024-08-16 19:13 UTC
### Description

```
TypeError: Cannot read properties of undefined (reading 'pathname')
    at getCommitHash (chrome-extension://hlepfoohegkhhmjieoechaddaejaokhf/assets/refined-github.js:6125:35)
    at init (chrome-extension://hlepfoohegkhhmjieoechaddaejaokhf/assets/refined-github.js:7411:134)
    at chrome-extension://hlepfoohegkhhmjieoechaddaejaokhf/assets/refined-github.js:3119:28
    at chrome-extension://hlepfoohegkhhmjieoechaddaejaokhf/assets/refined-github.js:3115:64
    at Array.map (<anonymous>)
    at chrome-extension://hlepfoohegkhhmjieoechaddaejaokhf/assets/refined-github.js:3115:45
    at runFeature (chrome-extension://hlepfoohegkhhmjieoechaddaejaokhf/assets/refined-github.js:3116:10)
    at setupPageLoad (chrome-extension://hlepfoohegkhhmjieoechaddaejaokhf/assets/refined-github.js:3131:43)
    at async chrome-extension://hlepfoohegkhhmjieoechaddaejaokhf/assets/refined-github.js:3156:11
```
<img width="1123" alt="Screenshot 2024-08-16 at 12 11 39 PM" src="https://github.com/user-attachments/assets/3650ab52-89fc-4e4f-97ac-29928198bae2">

### How to replicate the issue + URL

https://github.com/kubernetes-sigs/cri-tools/commits/release-1.31

### Extension version

24.8.13

### Browser(s) used

Version 127.0.6533.100 (Official Build) (arm64)
Version 127.0.6533.120 (Official Build) (arm64)

### Token ⚠️

- [X] I set a token in the options page. I understand that some features require a token to work.

**Comment by fregante** [comment] 2024-08-17 02:02
Duplicate of https://github.com/refined-github/refined-github/issues/7682

**Closed by fregante** 2024-08-17 02:02 UTC
Labels: bug
