### ISSUE TITLE
Extension causes 100% CPU lockups when creating PRs - (addApproveAndMerge button bug?)

### ISSUE THREAD

**Issue by sammcj** [refined-github/refined-github#6860] opened 2023-08-27 22:22 UTC
### Description

When creating PRs often a bug occurs after click the "Create Pull Request" button that causes the extension to use 100% CPU and locks up the tab.

This only occurs in Firefox and only after creating a PR.

This has been occurring off and on for a few months, I thought it was just my browser but I encountered the same problem on a recent install on another machine.

### How to replicate the issue + URL

1. Open Firefox
2. Fork a [repo](https://github.com/oobabooga/text-generation-webui)
3. When the upstream is newer than your fork create a PR
4. Observe Firefox pegging one CPU thread at 100% and the tab becoming unresponsive.

Sometimes you will also see the pull request section of the site endlessly loading:

<img width="1189" alt="image" src="https://github.com/refined-github/refined-github/assets/862951/8f5b0921-b47a-4963-85e2-f44b54dcfc14">

- Clearing the extension cache does not resolve the issue.
- Opening the same PR in Chrome with the extension also installed does not render the same issue.
- Disabling the extension in Firefox resolves the issue.

Here is a performance trace I captured:

https://profiler.firefox.com/public/g802n5q60q45hd11vpva42cqk6bpszhbfgvbsh8/calltree/?globalTrackOrder=0&implementation=js&thread=0&v=9

<img width="800" alt="image" src="https://github.com/refined-github/refined-github/assets/862951/c3d8fee2-e342-495f-9c26-3551ff51e14b">

I think that's suggesting it's a problem with the `addApproveAndMerge` button?

<img width="778" alt="image" src="https://github.com/refined-github/refined-github/assets/862951/c243b9f8-53a7-4a09-9cf1-df17343480df">

![SCR-20230828-hrpx](https://github.com/refined-github/refined-github/assets/862951/3addd9ac-1ed1-4bdf-af11-0f3750560fde)

<img width="552" alt="SCR-20230828-hrml" src="https://github.com/refined-github/refined-github/assets/862951/14c6e3ae-f43c-4888-9523-02f06b87f53e">

### Extension version

23.8.24

### Browser(s) used

Firefox 117

**Comment by fregante** [comment] 2023-08-28 06:53
We don't have that `addApproveAndMergeButton` and we don't use `Node.insertBefore` anywhere, so the issue is definitely not pointing to Refined GitHub. Do you have any other extensions? I can't find that function anywhere on google nor GitHub

**Comment by fregante** [comment] 2023-08-28 07:02
Closing because the code does not belong to an extension at all, as visible from the profile (which I thank you for including)

<img width="575" alt="Screenshot 1" src="https://github.com/refined-github/refined-github/assets/1402241/feb8a727-eafe-486c-bbbd-521b974ab1ae">

**Closed by fregante** 2023-08-28 07:02 UTC
Labels: bug

**Comment by sammcj** [comment] 2023-08-28 07:55
ohhhh my gosh, what an egg I am 🤦 

Sorry for wasting your time!

**Comment by fregante** [comment] 2023-08-28 08:15
No worries. I don't exclude conflicts with others but it's best to check what that specific function is doing first
