### ISSUE TITLE
Random arrows for scrolling

### ISSUE THREAD

**Issue by Milo123459** [refined-github/refined-github#4597] opened 2021-07-21 12:45 UTC
### Please ensure:

- [X] The bug is caused by Refined GitHub. It doesn't happen if I disable the extension.

### Description

https://github.com/discordjs/discord.js/pull/6162#issuecomment-884157859 < An example issue comment with random scrollable buttons to go up and down

### Screenshot

![image](https://user-images.githubusercontent.com/50248166/126490710-5bee6a27-e9df-48b4-951d-0ef59dbc7d57.png)

### Example URL

https://github.com/discordjs/discord.js/pull/6162#issuecomment-884157859

### Browser(s) used

Google chrome Version 91.0.4472.164 on Windows 10

**Comment by fregante** [comment] 2021-07-21 17:24
Duplicate of https://github.com/sindresorhus/refined-github/issues/3012

**Comment by Milo123459** [comment] 2021-07-21 17:28
Sorry.

**Comment by fregante** [comment] 2021-07-21 17:29
No it's ok, if you see the issue it means it still exists

**Comment by fregante** [comment] 2021-11-08 22:36
Maybe we need more `padding-bottom` in the fields we're adding the scrollbars to

**Comment by fregante** [comment] 2022-02-21 07:56
This is still an issue for me (Safari 15.3)

https://github.com/refined-github/refined-github/pull/5416#issuecomment-1041546190

![gif](https://user-images.githubusercontent.com/1402241/154911966-c5ba3c36-66b6-40ea-bf83-4d9bc6bff3a8.gif)

**Closed** 2022-03-15 07:59 UTC
Labels: bug, help wanted, good first issue
