### ISSUE TITLE
Add ability to collapse entire comments 

### ISSUE THREAD

**Issue by banagale** [refined-github/refined-github#4808] opened 2021-09-23 07:01 UTC
### Description

- In the top-right of a comment, add a chevron icon that lets you collapse a comment to just the title bar. 
- Preserver collapsed issue comments between pageloads

This is useful in issues where you need to reference only specific issues and are scrolling past intermediary ones.

This is not Hide Comment, which is used to hide comments from everyone. This is a convenience behavior.

I searched around and did not see that this exists yet, and I'm not seeing it somehow. If so, please point me at it. 

### Screenshot

<img width="333" alt="image" src="https://user-images.githubusercontent.com/1409710/134466106-2866e958-854f-4ef4-93f7-dafc9e05df30.png">

I'd probably put this in the far right, despite the ellipsis begging to be the last item of a list. 

Reason is, window management typically puts this minimize type behavior in the corner. Also I don't think its good jam something to the left of where the comment author is located. 

### Example URL

https://github.com/PostHog/posthog.com/issues/2018

**Comment by OnkarRuikar** [comment] 2022-04-23 05:47
One more use case: https://github.com/mdn/content/pull/15112
Here, the bot adds huge comment in every PR. Getting to the reviews requires a lot of scrolling.

Minimize all and expand all buttons would be really nice.

**Comment by fregante** [comment] 2022-05-03 03:04
> Here, the bot adds a huge comment in every PR.

The bot is made by humans. Tell the humans to tell the bot to wrap it all in a `details` tag. The UX of that bot is currently atrocious by default.

**Comment by OnkarRuikar** [comment] 2022-05-03 03:44
> Tell the humans to tell the bot to wrap it all in a `details` tag.

The discussion is already underway. Use of the `details` tag and [hide-comment-action](https://github.com/int128/hide-comment-action) has been suggested. 

But it's been a long time, and I am afraid if the quorum is not reached they'll not make any changes. Also, every repo we contribute to may not want to change their practices.

@fregante  can we add such a feature in refined-github, where we can provide user names in settings and their comments will be minimized?

**Comment by cheap-glitch** [comment] 2022-05-03 05:47
> where we can provide user names in settings

We don't do feature settings, but we _could_ extend e.g. `dim-bots` to matching comments. But would that make sense as a default for every user? Not sure about that.

**Comment by OnkarRuikar** [comment] 2022-05-03 06:12
> e.g. [`dim-bots`](https://github.com/refined-github/refined-github/blob/main/source/features/dim-bots.tsx) to matching comments. But would that make sense as a default for every user? Not sure about that.

Mostly bot comments are tagged with `<span class="Label Label--secondary">bot</span>` label, e.g. [example1](https://github.com/GoogleChrome/web.dev/pull/7830#issuecomment-1115208008), [example2](https://github.com/GoogleChrome/web.dev/pull/7830#issuecomment-1115208008), [example3](https://github.com/mdn/content/pull/15629#issuecomment-1115525934). Can we use that?

**Comment by fregante** [comment] 2022-08-05 09:09
@OnkarRuikar your feature request is a nearly-exact duplicate of:

- https://github.com/refined-github/refined-github/issues/1629

and it's not exactly what's being suggested here. I hid your comments for this reason.

It was implemented and later removed due to a serious bug. Now this feature can no longer be implemented in Refined GitHub because it essentially needs "options" to show the list of collapsed user, which [we don't do](https://github.com/refined-github/refined-github/wiki/%22Can-you-add-this-feature%3F%22#3-it-doesnt-require-options)

The good news is that in Safari 15.4+ and Chrome 105+ you will be able to write your own CSS to hide/collapse bot comments. I will very likely use this myself. Example:

```css
.timeline-comment:not(:hover):has(.author[href="/apps/github-actions"]) {
	overflow: hidden;
	height: 100px;
	opacity: 50%;
}
```

![text](https://user-images.githubusercontent.com/1402241/183043547-62f9192c-7c8e-4383-98cf-86688e317fa7.gif)

**Comment by fregante** [comment] 2022-08-05 09:13
> This is useful in issues where you need to reference only specific issues and are scrolling past intermediary ones.

We can implement this feature as it's similar to `easy-toggle-files` and `toggle-files-button`, no extra UI necessary though, just click anywhere to toggle the list. We'd also need this piece of UI though:

- https://github.com/refined-github/refined-github/pull/5653

**Comment by banagale** [comment] 2022-08-19 18:48
Thanks for keeping this issue alive. Some clarifying questions:

> We can implement this feature as it's similar to `easy-toggle-files` and `toggle-files-button`, no extra UI necessary though, just click anywhere to toggle the list.

For reference, here's [the UI behavior for `easy-toggle-files`](https://github.com/refined-github/refined-github/pull/5352).

I believe what you're saying is:

1. Click anywhere in the `timeline-comment-header` class that is not an existing visible element. ~"_the white space_".
1. Visibility of the (suspiciously potentially partially implemented) named `edit-comment-hide` class is toggled.
1. Toggle state is maintained between page loads.

> We'd also need this piece of UI though:
> 
>     * [Make `toggle-files-button` unforgettable #5653](https://github.com/refined-github/refined-github/pull/5653)

I believe you're saying add this label: 

![label](https://user-images.githubusercontent.com/1402241/169680163-ad6bf8dd-c745-4ebd-ab8b-b7ecbdf2104d.png)

But have the copy read, "Comment Hidden <up arrow>"

**Comment by fregante** [comment] 2023-02-16 10:02
Too many feature requests, realistically we’ll never get there. I’m closing those I think aren’t worth it.

**Closed by fregante** 2023-02-16 10:02 UTC
Labels: help wanted, under discussion, good first issue

**Comment by banagale** [comment] 2023-02-16 22:02
Okay. Thanks for the heads up. Maybe someday!
