### ISSUE TITLE
Features not loading though navigating - new issues page

### ISSUE THREAD

**Issue by ToBinio** [refined-github/refined-github#7953] opened 2024-10-24 18:56 UTC
### Description

No features are loaded when navigating to the new issue page via the GitHub UI.

this seems to be caused by `turbo:render` not being trigger
https://github.com/refined-github/refined-github/blob/c67b4bde4de38ba2a92ae83acc9e73f03a1b3c33/source/feature-manager.tsx#L263-L267

### How to replicate the issue + URL

go to
https://github.com/download-directory/download-directory.github.io/issues?q=sort%3Aupdated-desc%20is%3Aissue%20state%3Aclosed

click on the issue called `Testing`

no features are enabled

### Extension version

24.10.24

### Browser(s) used

Firefox

### Token ⚠️

- [X] I set a token in the options page. I understand that some features require a token to work.

**Comment by fregante** [comment] 2024-10-25 03:57
Duplicate of #6554

**Closed by fregante** 2024-10-25 03:57 UTC
Labels: bug
