### ISSUE TITLE
Occasionally Overly Persistent Popover/Hovercard

### ISSUE THREAD

**Issue by KyleKing** [refined-github/refined-github#6243] opened 2023-01-27 11:37 UTC
### Description

I would expect that if the mouse is moved away from the hover target or hovercard area, the hovercard should disappear, right? However, I've noticed that the popovers don't always disappear following those rules and there seems to be at least two places where this is most noticeable:

## (1) PRs

When attempting to copy the branch name, accidentally hovering over the user's profile pictures, fixes ticket id, or name, the hovercard appears and doesn't disappear when moving the mouse, clicking, or tapping ESC.

![Popover](https://user-images.githubusercontent.com/3784339/215076638-121a32eb-ce73-4377-98cb-3e2d68f88d53.gif)

## (2) My Issues

On this page, all the tickets are assigned to me and the popover only disappears when replaced. Clicking, tapping ESC, or moving the cursor away doesn't clear the popover.

![Popover](https://user-images.githubusercontent.com/3784339/215074571-d5ea517a-248d-4b24-8775-b6909f683fef.gif)

Tickets that aren't assigned or opened by me seem to behave as expected

### How to replicate the issue + URL

First open PR used to test: https://github.com/refined-github/refined-github/pull/6230

### Extension version

22.12.15

### Browser(s) used

Firefox (109.0)

**Comment by fregante** [comment] 2023-01-27 11:38
Duplicate of #6227

**Closed by fregante** 2023-01-27 11:38 UTC
Labels: bug

**Comment by KyleKing** [comment] 2023-01-27 13:01
Thanks! I was looking everywhere to find if someone else had seen this issue
