### ISSUE TITLE
Add emoji picker to comment section

### ISSUE THREAD

**Issue by Nico-Connor** [refined-github/refined-github#5660] opened 2022-05-25 07:15 UTC
### Description

Desktop operating systems do not allow for an easy way to add emoji in comments. Unlike smartphones you can't swap your keyboard at a press of a button.  

This leaves a sub-par experience for desktop users when adding emojis. In recognition of this downfall, many online platform have added an in-line option to add emojis to their comments. 

The way many social/communication application has gone about to enhance emoji experience on desktop is to add an inline emoji picker.    And I think the same feature should be available in GitHub.  

Exhibit A Facebook:

![image](https://user-images.githubusercontent.com/93364146/170202128-9ccf0319-59f8-47d0-bbab-a39dadaf33e0.png)

Exhibit B twitter:

![image](https://user-images.githubusercontent.com/93364146/170202163-dd553660-746e-4e8e-b192-682b5ec49d69.png)

Exhibit C Google Messages for the web:

![image](https://user-images.githubusercontent.com/93364146/170202197-ed39f2ac-7500-4545-9b6b-baaaeb2266c8.png)

Adding an emoji to a comment in GitHub is a tedious process and often requires users to consult an external cheat sheet of emojis to copy them back over to GitHub.  I think it's only fair to expect GitHub to have the same feature for desktop users as other major communication/social websites. 

### Screenshot

Here is bad mockup of how it could look on GitHub:

![image](https://user-images.githubusercontent.com/93364146/170202581-6e24a60b-305f-47e2-916b-9868ad93dfe5.png)

**Comment by fregante** [comment] 2022-05-25 08:43
Duplicate of https://github.com/refined-github/refined-github/issues/2890

**Closed by fregante** 2022-05-25 08:43 UTC
Labels: enhancement, under discussion

**Comment by fregante** [comment] 2022-05-25 08:46
> I believe the burden of proving a good user experience when it comes to picking an emoji on devices without digital keyboards is at the application layer, not the OS layer.

I disagree. The OS *already* has a picker, would should every application duplicate this feature?

Also this request fails the requirement number 1: https://github.com/refined-github/refined-github/issues/2960#issuecomment-606764895

> 1. It doesn't already exist as a userscript or extension.



https://www.google.com/search?q=emoji+picker+chrome+extension
