### ISSUE TITLE
`quick-review-comment-deletion`: Cannot read properties of null (reading 'click')

### ISSUE THREAD

**Issue by danikdanik** [refined-github/refined-github#6067] opened 2022-10-11 09:54 UTC
### Description

Failing to delete a comment in an opened PR

### How to replicate the issue + URL

Open pull request and assign a reviewer.
The reviewer adds a comment for a change.
When the reviewer attempts to delete the comment it fails with:

> listenerFn @ refined-github.js:5211
refined-github.js:3663 ❌ quick-review-comment-deletion
refined-github.js:3663 📕 22.10.10 → Cannot read properties of null (reading 'click')
refined-github.js:3664 🔍 Search issue https://github.com/refined-github/refined-github/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+Cannot+read+properties+of+null+%28reading+%27click%27%29
refined-github.js:3664 🚨 Report issue https://github.com/refined-github/refined-github/issues/new?labels=bug&template=1_bug_report.yml&title=%60quick-review-comment-deletion%60%3A+Cannot+read+properties+of+null+%28reading+%27click%27%29&example_urls=https%3A%2F%2Fgithub.com%2FMinervaLabs%2FArmor%2Fpull%2F463%2Ffiles&description=%60%60%60%0ACannot+read+properties+of+null+%28reading+%27click%27%29%0A%60%60%60
refined-github.js:10607 Uncaught (in promise) Error: Feature broken. Please open an issue with the link found in the console
    at HTMLHtmlElement.quick_review_comment_deletion_onButtonClick (refined-github.js:10607:19)
    at HTMLHtmlElement.listenerFn (refined-github.js:5211:20)
quick_review_comment_deletion_onButtonClick @ refined-github.js:10607
listenerFn @ refined-github.js:5211
await in listenerFn (async)
quick_review_comment_deletion_onButtonClick @ refined-github.js:10607

![image](https://user-images.githubusercontent.com/8233041/195058658-beefa20b-b925-4fbb-9d8a-8679010ad176.png)

### Extension version

n/a

### Browser(s) used

Chrome  106.0.5249.91

**Comment by fregante** [comment] 2022-10-11 10:54
Duplicate of #6065

**Closed by fregante** 2022-10-11 10:54 UTC
Labels: bug
