### ISSUE TITLE
Hide AI Buttons

### ISSUE THREAD

**Issue by TheOnlyTails** [refined-github/refined-github#8168] opened 2024-12-18 19:58 UTC
### Description

GitHub recently released an update which includes a Copilot button on the main Navbar, and an "Ask Copilot" textbox at the top of the main dashboard. Refined GitHub should include options to disable these, for users who don't want to use/see Copilot cluttering up their homepage and the navbar on every single page on GitHub.

### Example URLs

https://github.com/

**Comment by fregante** [comment] 2024-12-18 20:06
Duplicate of https://github.com/refined-github/refined-github/issues/8004

**Comment by fregante** [comment] 2024-12-18 20:07
Duplicate of #8124

**Closed by fregante** 2024-12-18 20:07 UTC
Labels: enhancement, under discussion
