### ISSUE TITLE
Enable "hide whitespace" on PR page by default (willing to submit PR if blessed)

### ISSUE THREAD

**Issue by ialexryan** [refined-github/refined-github#7939] opened 2024-10-22 17:40 UTC
### Description

[Users have been clamoring for years](https://github.com/orgs/community/discussions/65597) for the ability to enable "Hide whitespace" by default and GitHub has ignored them. In my experience, this is a major pain point and it feels to me like a natural fit for Refined GitHub. There are browser extensions for Chrome and FF that can do this (although none for Safari, my daily driver 😔), but they are unmaintained and request more permissions than they should.

 If you would be willing to accept a PR for this I would be delighted to create one!

### Example URLs

https://github.com/refined-github/refined-github/pull/7918/files

**Comment by fregante** [comment] 2024-10-23 03:21
Duplicate of https://github.com/refined-github/refined-github/issues/5829 https://github.com/refined-github/refined-github/issues/3655 https://github.com/refined-github/refined-github/issues/4812 https://github.com/refined-github/refined-github/issues/4548  https://github.com/refined-github/refined-github/issues/2503

**Closed by fregante** 2024-10-23 03:21 UTC
Labels: enhancement, under discussion

**Comment by ialexryan** [comment] 2025-03-18 20:06
@fregante had the same thought again today – I think the number of duplicates you listed reflects a real desire for this feature among the community. Many (most?) developers are using auto-formatting nowadays, which means that whitespace changes are never semantically meaningful and should always be ignored. Imo making this feature only persistent per PR (rather than per repo or even just per account) was a big miss on Github's part and I really think it fits Refined Github's niche perfectly. I would love to submit a PR if you would consider considering it. Thanks for everything! ~Alex
