### ISSUE TITLE
`hide-newsfeed-noise` isn't hiding grouped "follow" events correctly 

### ISSUE THREAD

**Issue by tjx666** [refined-github/refined-github#6305] opened 2023-02-07 16:26 UTC
### Description

<img width="1431" alt="image" src="https://user-images.githubusercontent.com/41773861/217303521-f89f176e-1e82-4cec-8064-7dc43cfceedb.png">

### How to replicate the issue + URL

https://github.com/

### Extension version

23.2.5

### Browser(s) used

Chrome

**Comment by fregante** [comment] 2023-02-07 17:48
🤔 we dropped that feature 2 versions ago. Can you close and reopen your browser? 

If it's still there, can you look at the DOM of the page to see what selector is hiding those elements?

**Comment by fregante** [comment] 2023-02-07 17:50
Duplicate of https://github.com/refined-github/refined-github/issues/6232

**Comment by fregante** [comment] 2023-02-07 18:08
Fixed in #6306 and via hotfix 👍

**Closed by fregante** 2023-02-07 18:08 UTC
Labels: bug

**Comment by tjx666** [comment] 2023-03-13 20:17
@fregante 

This time doesn't work for fork

<img width="1433" alt="image" src="https://user-images.githubusercontent.com/41773861/224822346-2d23d385-579d-4df2-8ec8-bcfe4473b5d1.png">
