### ISSUE TITLE
Cannot read properties of null (reading 'style')

### ISSUE THREAD

**Issue by klippx** [refined-github/refined-github#7452] opened 2024-06-14 13:07 UTC
### Description

Cannot read properties of null (reading 'style')

```sh
refined-github.js:7363 Uncaught TypeError: Cannot read properties of null (reading 'style')
    at refined-github.js:7363:82
    at refined-github.js:12422:5
    at refined-github.js:12423:3
```

![Image](https://github.com/refined-github/refined-github/assets/2785359/2b5279c1-95c0-4619-9e96-ec8fd0a2856b)

### How to replicate the issue + URL

https://github.com/notifications

### Extension version

24.6.13.1731

### Browser(s) used

Arc 1.46.0 using Chromium Engine Version 125.0.6422.142

**Comment by fregante** [comment] 2024-06-14 13:41
Duplicate of https://github.com/refined-github/refined-github/issues/7447

**Closed by fregante** 2024-06-14 13:41 UTC
Labels: bug
