### ISSUE TITLE
`clean-repo-tabs`: adds the menu button to profile page and breaks 

### ISSUE THREAD

**Issue by alexanderniebuhr** [refined-github/refined-github#7107] opened 2023-11-23 12:09 UTC
### Description

Opening a user profile page, e.g. `https://github.com/alexanderniebuhr`, the `clean-repo-tabs` menu button is shown. However clicking it shows an empty dropdown and makes some fancy UI jumps for me.

<img width="1495" alt="Screenshot 2023-11-23 at 13 07 23" src="https://github.com/refined-github/refined-github/assets/45965090/8bd7e322-75c7-47f1-a762-cf7ac3ef1f35">

### How to replicate the issue + URL

https://github.com/alexanderniebuhr

### Extension version

23.11.23

### Browser(s) used

Arc (Chromium)

**Comment by fregante** [comment] 2023-11-23 12:25
Duplicate of #7106

**Comment by fregante** [comment] 2023-11-23 12:36
The logic here is off:

https://github.com/refined-github/refined-github/blob/1c68bce3dccf2b6c23415ff51ea4a357efbd6b7f/source/features/clean-repo-tabs.tsx/#L137-L140

A function that alters the DOM is being used as a check, which may be `true`, but then fail `hasRepoHeader`. 

`clean-repo-tabs` and `more-dropdown-links`  are  not enabled on profiles

**Closed** 2024-02-02 07:22 UTC
Labels: bug, help wanted, small
