### ISSUE TITLE
Sort commit checks by status

### ISSUE THREAD

**Issue by mrcasals** [refined-github/refined-github#6344] opened 2023-02-13 12:25 UTC
### Description

First of all, thank you so much for the work you put in this extension. I've been using it for years and it's awesome, thank you ❤️ 

In my current company with have >100 possible checks on PRs. Not all of them run (we have a mono repo, and some check sonly run if you modify files from a given folder) but still it's very common to have >50 checks in a single PR. There's a counter, telling you how many checks are in a given status (eg "12 running, 3 queued, 5 successful, 3 failed, 3 cancelled") but it's very hard to understand what checks are in what state. The list is very long and the actual scrollable section is very small in comparison, so it gets complicated. It's very common to miss one of the failed jobs because of this.

I'm thinking, could there be a way to filter jobs by state? Maybe a dropdown with the current states, and if you select one state you only see the jobs in that state? Eg, I select "Failed" and I only see the failed ones.

I can't give  you a screenshot of the jobs in our repo since it's a private one, though 😞 

I think it makes sense for PR views, but it would be extra awesome if this worked with the checks in the commits page

### Example URLs

https://github.com/refined-github/refined-github/pulls/1
https://github.com/refined-github/refined-github/commits/main

**Comment by fregante** [comment] 2023-02-13 13:33
We already do, did the feature break? https://github.com/refined-github/refined-github/pull/5858

**Comment by mrcasals** [comment] 2023-02-13 15:03
@fregante I was not aware it existed, but checking the configuration for the app on Firefox I can't find it under that name: 
![image](https://user-images.githubusercontent.com/491891/218493601-b94c45fd-abe7-47ba-ad97-ef74ef053e46.png)

Also, looking for "checks" there doesn't seem to return anything relevant:
![image](https://user-images.githubusercontent.com/491891/218493839-f3b966df-1c9e-473f-8754-9d95dc897ddc.png)

**Comment by yakov116** [comment] 2023-02-13 15:15
Its a CSS only feature. Are you using firefox?

**Comment by fregante** [comment] 2023-02-13 16:46
Duplicate of https://github.com/refined-github/refined-github/issues/3136

**Closed by fregante** 2023-02-13 16:46 UTC
Labels: enhancement, under discussion

**Comment by mrcasals** [comment] 2023-02-14 13:59
Yup, I'm using Firefox. I see in https://github.com/refined-github/refined-github/issues/3136#issuecomment-1196366626 you meention this will land to Firefox during 2023, so maybe it still hasn't landed? 🤔 

This is what I'm seeing right now in a PR on my repo: 
![image](https://user-images.githubusercontent.com/491891/218759324-6990b4d1-ebc4-4335-867a-62a843d33fa0.png)

It's scrolled to the top, as you can see The first result is successfull. I have to scroll down to get to the first in progress job, and they're not grouped

**Comment by fregante** [comment] 2023-02-14 15:21
Yes. Firefox does not support that feature yet. No other option then waiting for it: https://github.com/refined-github/refined-github/issues/5797#issuecomment-1384857294

**Comment by mrcasals** [comment] 2023-02-15 07:33
Oh, I see! Thanks for the reply, I was not aware Firefox doesn't support `has()` yet 🙈
