### ISSUE TITLE
Add button to copy file path on comments in the Pull Request Conversation tab

### ISSUE THREAD

**Issue by cmotsn** [refined-github/refined-github#7258] opened 2024-02-09 13:59 UTC
### Description

Context: when handling feedback, I iterate on comments on the Pull Request Conversation tab. Often, this means I need to open the file in my IDE of choice, which is best achieved by using the appropriate shortcut to find a file by its path, which I copy by hand from the top of the PR comment:
![image](https://github.com/refined-github/refined-github/assets/105796626/925396fd-f68d-4d85-9bd2-bb3f1a3311aa)

Proposal:
It would be quicker to have a button next to the displayed filepath to copy the path without having to select it with the mouse beforehand, exactly like there is on the PR Files tab:
![image](https://github.com/refined-github/refined-github/assets/105796626/fe8336b3-f34d-4d8a-902a-ee43a29683e1)

### Example URLs

https://github.com/refined-github/refined-github/pull/7160

**Comment by fregante** [comment] 2024-02-09 14:00
Duplicate of https://github.com/refined-github/refined-github/issues/1912

**Closed by fregante** 2024-02-09 14:00 UTC
Labels: enhancement, under discussion
