### ISSUE TITLE
Option to share settings cross device

### ISSUE THREAD

**Issue by tommyliang-dev** [refined-github/refined-github#6172] opened 2022-11-19 14:08 UTC
Is there a way to share my settings on device A to device B? 

I use GitHub on multiple devices (two laptops and a desktop) and was wondering if there's an easy way to persist the settings across all of them or generate a json file that I can paste in

**Comment by busches** [comment] 2022-11-19 14:20
Chrome will sync your extension settings if enabled.

**Comment by fregante** [comment] 2022-11-19 14:22
Duplicate of https://github.com/refined-github/refined-github/issues/3981

**Closed by fregante** 2022-11-19 14:22 UTC
Labels: under discussion
