### ISSUE TITLE
RGH is injecting code into websites other than Github.

### ISSUE THREAD

**Issue by Pandustry-Dev** [refined-github/refined-github#7336] opened 2024-04-21 18:39 UTC
### Description

[https://techcommunity.microsoft.com/t5/outlook/got-weird-internal-publishing-page-instead-of-login/m-p/3902338/highlight/false#M17590](https://techcommunity.microsoft.com/t5/outlook/got-weird-internal-publishing-page-instead-of-login/m-p/3902338/highlight/false#M17590)

This was my reply to someone having outlook login issues after doing a google search for a portion of the injected code appearing in my Userstyle CSS scripts as I installed them:

"This appears to be caused by the firefox addon Refined-Github. Turn off the permission "Access your data for all websites" on the permissions tab and it should fix it. For me it was inserting extra code to userstyle CSS scripts from userstyle.world and some already install userstyles in FireMonkey. I realized looking at you post what the "RGH" CSS handle was for Refined-GitHub."

### How to replicate the issue + URL

Enable the "Access your data for all websites" permission.
Install a userscript from userscript.world into FireMonkey or apparently try to log into outlook.com and the follow code appears (note, this has been formatting via prettyprint):

:where(.user-mention:not(.commit-author)[data-hovercard-type="user"]):not(
    .rgh-seen--26062470120
  ) {
  animation: 1ms rgh-selector-observer;
}

:where(
    .js-issue-row [data-hovercard-type="user"],
    .notification-thread-subscription [data-hovercard-type="user"]
  ):not(.rgh-seen--26062499911) {
  animation: 1ms rgh-selector-observer;
}

:where(
    .js-hovercard-content
      .Popover-message
      div.d-flex.mt-3.overflow-hidden
      > div.d-flex,
    .js-hovercard-content
      .Popover-message
      div.d-flex.mt-3
      > div.overflow-hidden.ml-3
  ):not(.rgh-seen-722523370) {
  animation: 1ms rgh-selector-observer;
}

:where(
    [itemprop="homeLocation"] svg.octicon-location,
    [aria-label="User location"] svg.octicon-location
  ):not(.rgh-seen-668154795) {
  animation: 1ms rgh-selector-observer;
}

:where(a[href*="?tab=repositories"]:is([href^="/"], [href^="https://userstyles.world/"]):not([href*="&type="], .issues-reset-query),a[href*="/repositories"]:is([href^="/orgs/"], [href^="https://userstyles.world/orgs/"]):not([href*="&type="], .issues-reset-query)):not(.rgh-seen--393030416)
{
  animation: 1ms rgh-selector-observer;
}

:where(
    .BorderGrid--spacious .f4.my-3,
    .js-commits-list-item pre,
    .js-commit-group pre,
    .release-header,
    .Box-row .mb-1 a,
    #pull-requests a.Link--primary,
    [id^="check_suite"] a.Link--primary,
    .js-socket-channel[data-url*="/header_partial"] h3,
    .js-wiki-sidebar-toggle-display a,
    #wiki-wrapper .gh-header-title,
    #user-repositories-list [itemprop="description"],
    .js-hovercard-content > .Popover-message .Link--primary,
    .search-title a,
    .notification-thread-subscription [id^="subscription_link_"]
  ):not(.rgh-seen-27766609435) {
  animation: 1ms rgh-selector-observer;
}

:where(
    a:is(
        [href*="/issues"],
        [href*="/pulls"],
        [href*="/projects"],
        [href*="/labels/"]
      ):not([href*="sort%3A"], .issues-reset-query)
  ):not(.rgh-seen--1282261975) {
  animation: 1ms rgh-selector-observer;
}

:where([data-hydro-view*="pull-request-hovercard-hover"] ~ .d-flex.mt-2):not(
    .rgh-seen--1968497660
  ) {
  animation: 1ms rgh-selector-observer;
}

:where(.comment-body a[href]:not(.rgh-linkified-code)):not(
    .rgh-seen-26849672246
  ) {
  animation: 1ms rgh-selector-observer;
}

### Extension version

24.4.9

### Browser(s) used

Firefox 127.0a1 (2024-04-20) (64-bit)

**Comment by busches** [comment] 2024-04-21 19:56
Duplicate of https://github.com/refined-github/refined-github/issues/7319

**Closed by busches** 2024-04-21 19:56 UTC
Labels: bug

**Comment by Pandustry-Dev** [comment] 2024-04-21 21:56
I guess I should have said RGH is ignoring the "Domain Selector" option as this behavior is observed with either setting. Also this is a rather recent change, I had that setting that way for a long while and never had an issue. I assumed it was for the preview popup cards that would appear during a mouseover of a link (which hasn't worked for me for a long while), so links outside Git leading into it could show those popups. 

If it's required for Enterprise users, wouldn't a whitelist be more appropriate? Even Enterprise users still use Microsoft and Google. How are they limiting the scope of these injections? I don't see any option besides "Default" and "*" and I had it set to Default. 

I don't mean to bug you and I don't require a fix as the feature I thought it was for doesn't work anyway, I am just trying to make sure you're not dismissing an issue that is pretty hard for the average user to trace and could be effecting many others without you ever knowing. You have an auto update mechanism to fix it rather easily in comparison to the thousands of hours being collective wasted.

**Comment by fregante** [comment] 2024-04-22 02:17
> Enable the "Access your data for all websites" permission.

I don't really understand what you expect to happen when you enable this option. You enable it, you waste your time. Don't waste ours

**Comment by fregante** [comment] 2024-04-22 02:21
> this is a rather recent change

It's not, our permissions haven't changed since 2017-ish

> I assumed it was for the preview popup cards that would appear during a mouseover of a link

That's a native GitHub feature 

> wouldn't a whitelist be more appropriate?

That's what we already have, but the browser also shows users that toggle. You're not supposed to enable that if you don't need it, and you don't. 

> to fix it rather easily

There's no bug, there's nothing to fix. In order to have the whitelist as you mentioned, we **must** specify that optional permission for all websites.
