### ISSUE TITLE
`clean-repo-tabs`: Cannot read properties of undefined (reading 'removeAttribute')

### ISSUE THREAD

**Issue by PMHEX** [refined-github/refined-github#6913] opened 2023-09-15 01:52 UTC
### Description

```
TypeError: Cannot read properties of undefined (reading 'removeAttribute')
    at onlyShowInDropdown (chrome-extension://hlepfoohegkhhmjieoechaddaejaokhf/assets/refined-github.js:11876:16)
    at updateProjectsTab (chrome-extension://hlepfoohegkhhmjieoechaddaejaokhf/assets/refined-github.js:11912:14)
    at async chrome-extension://hlepfoohegkhhmjieoechaddaejaokhf/assets/refined-github.js:4255:22
    at async Promise.all (index 3)
    at async chrome-extension://hlepfoohegkhhmjieoechaddaejaokhf/assets/refined-github.js:4251:11
    at async runFeature (chrome-extension://hlepfoohegkhhmjieoechaddaejaokhf/assets/refined-github.js:4250:9)
    at async setupPageLoad (chrome-extension://hlepfoohegkhhmjieoechaddaejaokhf/assets/refined-github.js:4267:37)
```

### How to replicate the issue + URL

https://github.com/PMHEX/POSApp/blob/master/Projects/rv/Debug/_UpgradeReport_Files/UpgradeReport.xslt

### Extension version

23.9.7

### Browser(s) used

)_(

**Comment by fregante** [comment] 2023-09-15 05:59
I can't reproduce this bug. It's strange that it would fail since the element appears to exist:

<img width="452" alt="Screenshot 1" src="https://github.com/refined-github/refined-github/assets/1402241/f172bfeb-3eba-4878-834a-ad85b2a289cd">


This is the relevant code:

https://github.com/refined-github/refined-github/blob/98d785403903d10e706bd0cd3b12c8a5854738d8/source/features/clean-repo-tabs.tsx#L107-L108

https://github.com/refined-github/refined-github/blob/98d785403903d10e706bd0cd3b12c8a5854738d8/source/features/clean-repo-tabs.tsx#L43-L44

**Comment by fregante** [comment] 2023-09-15 06:04
I can't reproduce this bug. It's strange that it would fail since the element appears to exist:

<img width="452" alt="Screenshot 1" src="https://github.com/refined-github/refined-github/assets/1402241/f172bfeb-3eba-4878-834a-ad85b2a289cd">


This is the relevant code:

https://github.com/refined-github/refined-github/blob/98d785403903d10e706bd0cd3b12c8a5854738d8/source/features/clean-repo-tabs.tsx#L107-L108

https://github.com/refined-github/refined-github/blob/98d785403903d10e706bd0cd3b12c8a5854738d8/source/features/clean-repo-tabs.tsx#L43-L44

This line can only be reached if the tab exists but the menu item doesn't. Maybe it's a duplicate run? That shouldn't happen either thanks to the `has-rgh` check

**Comment by fregante** [comment] 2023-09-15 06:05
Closing as unreproducible and because no browser was specified 

> ### Browser(s) used
> )_(

**Closed by fregante** 2023-09-15 06:05 UTC
Labels: bug
