### ISSUE TITLE
How to disable repo info centering?

### ISSUE THREAD

**Issue by radstevee** [refined-github/refined-github#5617] opened 2022-05-03 14:55 UTC
It looks like this for me:
![image](https://user-images.githubusercontent.com/96977790/166478104-169b69df-1b31-4d3f-8525-7b8444a0802c.png)
(i'm using [the catppuccin theme](https://github.com/catppuccin/github))

**Comment by fregante** [comment] 2022-05-03 15:27
Duplicate of https://github.com/refined-github/refined-github/issues/4519

**Closed by fregante** 2022-05-03 15:27 UTC
Labels: under discussion

**Comment by fregante** [comment] 2023-02-01 07:23
This feature has now been dropped in https://github.com/refined-github/refined-github/pull/6247
