### ISSUE TITLE
`extractCurrentBranchFromBranchPicker`  Cannot read properties of undefined (reading 'title')

### ISSUE THREAD

**Issue by isaacrlevin** [refined-github/refined-github#6832] opened 2023-08-16 16:53 UTC
### Description

```
TypeError: Cannot read properties of undefined (reading 'title')
    at extractCurrentBranchFromBranchPicker (chrome-extension://hlepfoohegkhhmjieoechaddaejaokhf/assets/refined-github.js:3455:57)
    at chrome-extension://hlepfoohegkhhmjieoechaddaejaokhf/assets/refined-github.js:4646:81
    at async CachedFunction.updater (chrome-extension://hlepfoohegkhhmjieoechaddaejaokhf/assets/refined-github.js:4645:121)
    at async getSet (chrome-extension://hlepfoohegkhhmjieoechaddaejaokhf/assets/refined-github.js:2344:30)
```

### How to replicate the issue + URL

https://github.com/isaacrlevin/CoffeeAndOpenSource.com

### Extension version

23.8.3

### Browser(s) used

Edge

**Comment by fregante** [comment] 2023-08-16 17:05
> `TypeError: Cannot read properties of undefined (reading 'title')`

I'm not sure of how this is possible. There's a boolean check before this so `undefined` should not get through; we don't even have any `!` nearby 🤔 

https://github.com/refined-github/refined-github/blob/d8939719446c0504da7b151037f0aba197a4734c/source/github-helpers/get-current-git-ref.ts#L14C1-L15

https://github.com/refined-github/refined-github/blob/d8939719446c0504da7b151037f0aba197a4734c/source/github-helpers/index.ts#L142-L145

**Comment by fregante** [comment] 2023-08-25 08:01
Duplicate of https://github.com/refined-github/refined-github/issues/6818

**Closed by fregante** 2023-08-25 08:01 UTC
Labels: bug
