### ISSUE TITLE
Duplicate `ci-link`

### ISSUE THREAD

**Issue by Milo123459** [refined-github/refined-github#5755] opened 2022-06-30 07:02 UTC
### Please ensure:

- [X] The bug is caused by Refined GitHub. It doesn't happen if I disable the extension.
- [X] The bug happens after clearing extension cache. The "Clear cache" button below can also be found at the bottom of the options page.

### Example URLs

https://github.com/serenity-rs/serenity

### Extension version

22.6.25

### Browser(s) used

Google Chrome

### Description

<img width="907" alt="image" src="https://user-images.githubusercontent.com/50248166/176613616-5b22e276-1a06-4b66-b318-9733da52bd7e.png">

The bugs tab appears twice on certain repos.

### Include in this issue:

- [x] Screenshots/video/gif demonstrating the bug, if it’s visual
- [ ] Console errors, if any

**Comment by fregante** [comment] 2022-06-30 07:41
Duplicate of https://github.com/refined-github/refined-github/issues/5738

**Comment by Milo123459** [comment] 2022-07-07 16:10
<img width="426" alt="image" src="https://user-images.githubusercontent.com/50248166/177820719-0bece162-c7bd-4aad-9e1d-ebe42efdb2f4.png">

Still happening.

**Comment by fregante** [comment] 2022-07-07 16:13
Version? I never saw that. How do you replicate the issue?

**Comment by Milo123459** [comment] 2022-07-07 16:16
Version: 22.7.7

No idea how to reproduce, it just happened.

**Comment by yakov116** [comment] 2022-07-07 16:23
I got it to happen when I changed versions of the extension. Had to just refresh the page.

**Comment by fregante** [comment] 2022-07-08 06:27
Repro:

1. Open https://github.com/refined-github/refined-github/actions/runs/2633901459
2. Switch to any other tab, like PRs

**Comment by kidonng** [comment] 2022-07-09 08:36
`bugs-tab` doesn't seem to duplicate anymore, it's `ci-link` here we are talking about.

But there are more features suffering:

```
❌ clean-repo-tabs
refined-github.js:3897 📕 22.7.7 → TypeError: Cannot read properties of undefined (reading 'removeAttribute')
    at onlyShowInDropdown (refined-github.js:11301:16)
    at init (refined-github.js:11342:57)
    at async runFeature (refined-github.js:3951:20)
    at async setupPageLoad (refined-github.js:3957:34)
❌ toggle-files-button
refined-github.js:3897 📕 22.7.7 → TypeError: Failed to execute 'observe' on 'MutationObserver': parameter 1 is not of type 'Node'.
    at observeElement (refined-github.js:6851:23)
    at init (refined-github.js:6905:28)
    at async runFeature (refined-github.js:3951:20)
    at async setupPageLoad (refined-github.js:3957:34)
```

**Comment by fregante** [comment] 2022-07-14 12:24
More repro steps can be found in https://github.com/refined-github/refined-github/issues/5822

**Comment by Milo123459** [comment] 2022-07-14 12:26
> More repro steps can be found in https://github.com/refined-github/refined-github/issues/5822

It also happens in repos that aren't forks.

**Closed** 2022-07-20 13:41 UTC
Labels: bug, help wanted, ajax
