### ISSUE TITLE
`more-dropdown-links`: Cannot read properties of undefined (reading 'title')

### ISSUE THREAD

**Issue by isaacrlevin** [refined-github/refined-github#6833] opened 2023-08-16 16:53 UTC
### Description

```
TypeError: Cannot read properties of undefined (reading 'title')
    at extractCurrentBranchFromBranchPicker (chrome-extension://hlepfoohegkhhmjieoechaddaejaokhf/assets/refined-github.js:3455:57)
    at chrome-extension://hlepfoohegkhhmjieoechaddaejaokhf/assets/refined-github.js:4646:81
    at async CachedFunction.updater (chrome-extension://hlepfoohegkhhmjieoechaddaejaokhf/assets/refined-github.js:4645:121)
    at async getSet (chrome-extension://hlepfoohegkhhmjieoechaddaejaokhf/assets/refined-github.js:2344:30)
```

### How to replicate the issue + URL

https://github.com/isaacrlevin/CoffeeAndOpenSource.com

### Extension version

23.8.3

### Browser(s) used

Edge

**Comment by fregante** [comment] 2023-08-16 17:01
Duplicate of https://github.com/refined-github/refined-github/issues/6832

**Closed by fregante** 2023-08-16 17:01 UTC
Labels: bug
