### ISSUE TITLE
`highest-rated-comment`: Cannot read properties of undefined (reading 'before')

### ISSUE THREAD

**Issue by AbhinavAchha** [refined-github/refined-github#6198] opened 2022-12-13 10:00 UTC
### Description

TypeError: Cannot read properties of undefined (reading 'before')
    at refined-github.js:8074:88
    at init (refined-github.js:8078:10)
    at runFeature (refined-github.js:3709:26)
    at setupPageLoad (refined-github.js:3715:40)
    at refined-github.js:3736:35

### How to replicate the issue + URL

https://github.com/react-hook-form/react-hook-form/issues/4055

Any github issue which has highest-rated comment visible

### Extension version

22.11.21

### Browser(s) used

Brave Version 1.46.140 Chromium: 108.0.5359.99 (Official Build) (64-bit)

**Comment by fregante** [comment] 2022-12-13 10:19
Duplicate of #6196

**Closed by fregante** 2022-12-13 10:19 UTC
Labels: bug

**Comment by meche-gh** [comment] 2022-12-16 15:20
Fix released in https://github.com/refined-github/refined-github/releases/tag/22.12.15
