### ISSUE TITLE
`download-folder-button` is not deinited

### ISSUE THREAD

**Issue by 134130** [refined-github/refined-github#6843] opened 2023-08-19 08:43 UTC
### Description

<img width="283" alt="image" src="https://github.com/refined-github/refined-github/assets/50487467/a1abf679-c5fb-4296-8b84-a71585032239">

### How to replicate the issue + URL

- Visit some folder in repo (refined-github/source)
  - https://github.com/refined-github/refined-github/tree/main/source
- Visit some file in folder (refined-github/source/background.ts)
  - https://github.com/refined-github/refined-github/blob/main/source/background.ts

### Extension version

23.8.3

### Browser(s) used

Chrome

**Comment by fregante** [comment] 2023-08-19 15:09
Duplicate of https://github.com/refined-github/refined-github/issues/6554

**Closed by fregante** 2023-08-19 15:09 UTC
Labels: bug
