### ISSUE TITLE
Allow for opening 10 (or x) unread issues/PR's/etc at a time

### ISSUE THREAD

**Issue by muellerzr** [refined-github/refined-github#7872] opened 2024-10-08 15:42 UTC
### Description

Working at HF I deal with hundreds of unread notifications to get through every day. What'd be great is if we can (in a configuration) open up only the first `n` notifications, to make it easier to digest and get through without needing to navigate a few hundred tabs suddenly opening

### Example URLs

https://github-production-user-asset-6210df.s3.amazonaws.com/140871606/257085496-17e5c6fa-6bad-443d-96d2-d97e73cd1a5e.png

Same spot as here (maybe even same button)

**Comment by fregante** [comment] 2024-10-08 16:37
> a few hundred tabs suddenly opening

That button only opens 25 tabs at most, so that number is much inflated. I'm not convinced that 25 new tabs is a substantial amount (it's a lot, but it's already limited)

**Comment by muellerzr** [comment] 2024-10-08 16:44
Fair! Yes that was overblown :) 

However if we could do less than that too it'd be nice. (It's alright if you deem that a non-issue ofc)

**Comment by fregante** [comment] 2024-10-09 10:50
> in a configuration

The issue is that we [don't offer options](https://github.com/refined-github/refined-github/wiki/%22Can-you-add-this-feature%3F%22#3-it-doesnt-require-options) and this is a little niche to deserve its own button. An alternative would be to extend our confirmation dialog:

https://github.com/refined-github/refined-github/blob/54267e2478b1731dd8209402165cd8bcce613a82/source/helpers/open-tabs.ts#L6

For example it could be `prompt('enter how many tabs you want to open')`. However this would be awkward, would introduce further complexity (i.e. bring this number back to the caller so that only X notifications are marked as unread), and I'd be unsure which ones to open (first X or last X?)

That button is supposed to be a quick way to just open all in 1-2 clicks. If you want to customize how many and which ones to open, you can do so also in 3 clicks:

![regular](https://github.com/user-attachments/assets/1774b5e7-7558-42f8-b5b0-b00676588b31)

**Closed by fregante** 2024-10-09 10:50 UTC
Labels: enhancement, under discussion

**Comment by fregante** [comment] 2024-10-09 10:51
By the way I'm pressing <kbd>shift</kbd> in that gif.

Anyway thanks for the issue, this will actually be something I need to be aware of if/when this other feature is added:

- https://github.com/refined-github/refined-github/issues/7442
