### ISSUE TITLE
Option to toggle annotations for all files in PR

### ISSUE THREAD

**Issue by ankushg** [refined-github/refined-github#5216] opened 2021-12-17 00:22 UTC
### Description

Many CI tools leave Check Run Annotations on PRs, which can clutter a PR's "Files changed" view.

Currently, we can show or hide Annotations on a per-file-basis.

<img width="232" alt="CleanShot 2021-12-16 at 19 21 35@2x" src="https://user-images.githubusercontent.com/227041/146468131-71e604fd-66ea-43ca-bc07-f5e29d612efe.png">

It would be great if there were a top-level option in a PR's "Files changed" tab to show/hide annotations for ALL files in the PR:
<img width="835" alt="CleanShot 2021-12-16 at 19 22 23@2x" src="https://user-images.githubusercontent.com/227041/146468209-1a4bcd40-ee08-4d11-ab92-2e03ea04e470.png">

### Example URL

https://github.com/reviewdog/reviewdog/pull/967/files

**Comment by fregante** [comment] 2021-12-17 06:08
Duplicate of https://github.com/refined-github/refined-github/issues/3431

**Closed** 2021-12-19 08:29 UTC
Labels: enhancement, under discussion
