### ISSUE TITLE
Add a condensed-navigation-tab option

### ISSUE THREAD

**Issue by ssbarnea** [refined-github/refined-github#4836] opened 2021-09-30 15:35 UTC
### Description

For people that use screen in portrait mode or split screens that tab-navigation-bar is often too small to include all useful links, especially when bugs are separated from issues.

We should have an option to enable a more condensed more where one of the following measures could be used:
* less spacing between buttons
* Remove text for most common options as we already have icons
* Replace text with shorter version, like `Pull Requests` could easily be `PRs`.

### Example URL

https://github.com/sindresorhus/refined-github

**Comment by yakov116** [comment] 2021-09-30 15:46
Do you mean the below?

>While I'm at it, here's a related "refinement" that won't be part of Refined GiHub 😃 
>
><img width="539" alt="Screen Shot 1" src="https://user-images.githubusercontent.com/1402241/116839634-4e14e580-abfd-11eb-9ec7-e1f3c1f187ae.png">
>
>
>```css
>.UnderlineNav-octicon {
>	margin-right: 0 !important;
>}
>.UnderlineNav-item [data-content] {
>	display: none;
>}
>```

_Originally posted by @fregante in https://github.com/sindresorhus/refined-github/issues/4286#issuecomment-831005339_

**Comment by ssbarnea** [comment] 2021-10-01 18:19
Very close to this but you will discover that while making the button smaller the ones that were hidden to dropdown menu to not come after them, they remain into the dropdown.

Basically it does declutter the UI a little bit but without making the options that did not originally fit back.

**Comment by kidonng** [comment] 2022-02-13 11:01
Maybe we can enable these styles on small screens. But [there won't be options](https://github.com/refined-github/refined-github/issues/2960#issuecomment-606765658).

**Comment by fregante** [comment] 2022-02-14 09:53
> Maybe we can enable these styles on small screens

I like that. I'd rather hide the labels than hide everything in the dropdown, especially on a phone screen.

**Comment by kidonng** [comment] 2022-02-25 10:56
As can be seen in #5437 screenshots, the ellipsis appears where it shouldn't, presumably because we added a few extras tab.

Approve this proposal and use a condensed icon would probably mitigate the issue.

**Comment by fregante** [comment] 2022-07-08 19:04
Some CSS can be found in https://github.com/refined-github/refined-github/issues/5805

We can add it below 700px, let's see how people react to it. Maybe we can even hotfix it _before_ merging it to get some early feedback.

**Comment by fregante** [comment] 2023-04-26 16:11
Duplicate of https://github.com/refined-github/refined-github/issues/5805

**Closed by fregante** 2023-04-26 16:11 UTC
Labels: enhancement, help wanted, good first issue
