### ISSUE TITLE
Max image size for image previews

### ISSUE THREAD

**Issue by Katsute** [refined-github/refined-github#5740] opened 2022-06-29 01:59 UTC
### Description

For very large images it makes more sense to resize it to fit the screen, rather than crop it (current behavior). A simple `max-height` and `max-width` for image previews would make these pages easier to see.

### Screenshot

**Current:**

![github com_KatsuteDev_Mal4J_blob_main_assets_banner-sq png](https://user-images.githubusercontent.com/58778985/176334504-4ba48bd5-baa3-49b3-99e3-02e784d1414d.png)

**Proposed:**

![github com_KatsuteDev_Mal4J_blob_main_assets_banner-sq png (1)](https://user-images.githubusercontent.com/58778985/176334521-8cf94534-0a48-4e29-891b-48a8601b8eae.png)

### Example URLs

https://github.com/KatsuteDev/Mal4J/blob/main/assets/banner-sq.png

**Comment by fregante** [comment] 2022-06-29 03:49
Duplicate of https://github.com/refined-github/refined-github/issues/2616

**Closed** 2022-06-30 18:40 UTC
Labels: enhancement, under discussion
