### ISSUE TITLE
[UI] Running actions in forked repo will cause status dupe 

### ISSUE THREAD

**Issue by 01101sam** [refined-github/refined-github#5822] opened 2022-07-13 12:28 UTC
### Description

The UI goes wrong when click as the following steps:
1. Actions -> (Any) Workflow Job
2. Click (Any) Tab

Affected positions:
![image](https://user-images.githubusercontent.com/100821827/178732808-fd93a507-06cc-4d8b-96f5-a99882eb4eb5.png)
![image](https://user-images.githubusercontent.com/100821827/178732844-0b9b565d-fa9b-43f4-b8d6-13c40e271829.png)

### How to replicate the issue

(Basically any forked repo with actions enabled can do this, for example https://github.com/01101sam/node-https-proxy-agent)

https://user-images.githubusercontent.com/100821827/178733445-d810ae82-9615-4e7f-8b0f-d4fcd9f4b285.mp4

### Extension version

22.7.11

### Browser(s) used

Chrome

**Comment by fregante** [comment] 2022-07-13 12:47
Duplicate of https://github.com/refined-github/refined-github/issues/5755

**Closed by fregante** 2022-07-13 12:47 UTC
Labels: bug
