### ISSUE TITLE
Show failing status checks at the top

### ISSUE THREAD

**Issue by thomaseizinger** [refined-github/refined-github#6907] opened 2023-09-11 23:40 UTC
### Description

On repos with many status checks, scrolling to find the failing ones can be quite tedious. For example:

[Scrolling through long list of status checks](https://github.com/refined-github/refined-github/assets/5486389/14b94695-e5f0-449c-81d0-0eff52076382)

The list could be sorted to list all failing status checks at the top as those are the ones you most likely want to view.

### Example URLs

https://github.com/libp2p/rust-libp2p/pull/4473

**Comment by fregante** [comment] 2023-09-12 01:29
Duplicate of https://github.com/refined-github/refined-github/issues/4086

**Closed by fregante** 2023-09-12 01:29 UTC
Labels: enhancement, under discussion

**Comment by thomaseizinger** [comment] 2023-09-12 01:35
> Duplicate of #4086

Is it? From what I understand, #4086 is about adding a new link at the top that summarizes the CI state. Would that popup sort the list to show the failing CI checks first? It would still be one click away to get to the failing one whereas sorting the existing list to always show the failing ones at the top wouldn't require any clicks.

**Comment by fregante** [comment] 2023-09-12 02:13
Oh actually you're probably talking about this:

- https://github.com/refined-github/refined-github/pull/5858

We have the feature, but I assume you're using Firefox?

**Comment by thomaseizinger** [comment] 2023-09-12 02:29
> We have the feature, but I assume you're using Firefox?

I am!

**Comment by fregante** [comment] 2023-09-12 02:31
Yep, Firefox does not support it, so you'll have to wait

- https://github.com/refined-github/refined-github/issues/5797

**Comment by thomaseizinger** [comment] 2023-09-12 02:34
> Yep, Firefox does not support it, so you'll have to wait
> 
>     * [:has() selector discussion #5797](https://github.com/refined-github/refined-github/issues/5797)

Thanks! I just enabled the flag in `about:config` but it seems whatever we are doing for the status checks still doesn't work. I did notice that merge commits are now grayed out which is a nice bonus :)

**Comment by thomaseizinger** [comment] 2023-09-12 02:41
Don't mind me, after reloading the page this now seems to work correctly, exciting :tada:

**Comment by fregante** [comment] 2023-09-12 03:22
Duplicate of https://github.com/refined-github/refined-github/issues/6344
