### ISSUE TITLE
update-pr-from-base-branch allows for updating via rebase

### ISSUE THREAD

**Issue by jay-babu** [refined-github/refined-github#7445] opened 2024-06-14 02:03 UTC
### Description

As the title says. currently only merge commit is allowed

### Example URLs

https://github.com/refined-github/refined-github/blob/main/source/features/update-pr-from-base-branch.tsx

**Comment by fregante** [comment] 2024-06-14 03:20
Duplicate of https://github.com/refined-github/refined-github/issues/7270

**Closed by fregante** 2024-06-14 03:21 UTC
Labels: enhancement, under discussion
