### ISSUE TITLE
`batch-mark-files-as-viewed` alt+click broken

### ISSUE THREAD

**Issue by mfulton26** [refined-github/refined-github#5697] opened 2022-06-16 18:32 UTC
Some time ago I noticed that Alt+Click on a "Viewed" checkbox while reviewing files on a PR stopped toggling all files as viewed/not-viewed. Was this intentional or a regression?

I believe it was originally added in https://github.com/refined-github/refined-github/issues/3043.

I know some changes have been made to make marking a range of files as viewed easier, etc. but personally I'd prefer to be able to view all the files in a PR and then quickly mark them all as viewed once satisfied (at least I do this on some reviews) but such functionality doesn't appear to be working at the moment.

Please advise.

Thank you.

**Comment by yakov116** [comment] 2022-06-16 18:35
Yeah something looks wrong there, it works only if you click on the first one then click again and then it will unmark the current one and mark the others....

@cheap-glitch did you change anything there recently?

**Comment by cheap-glitch** [comment] 2022-06-16 22:38
> @cheap-glitch did you change anything there recently?

Don't think so. Maybe it was https://togithub.com/refined-github/refined-github/pull/5587?

**Comment by fregante** [comment] 2022-06-17 04:26
I saw this bug. Also reported in https://github.com/refined-github/refined-github/pull/5587#issuecomment-1105122918

**Comment by fregante** [comment] 2022-09-25 11:33
Duplicate of https://github.com/refined-github/refined-github/issues/5880

**Closed** 2022-09-25 11:33 UTC
Labels: bug, help wanted
