### ISSUE TITLE
Automatically fold files in PR -> Files changed

### ISSUE THREAD

**Issue by corani** [refined-github/refined-github#7525] opened 2024-07-05 02:46 UTC
### Description

We are vendoring dependencies in our Go projects, resulting sometimes in PRs with hundreds of files with most of them being dependencies. This clutters up the UI during reviews, as typically you're not looking at the files in the `vendor/...` folders.

It would be nice to have an option to automatically fold (or even mark-as-viewed?) files based on some pattern.

### Example URLs

https://github.com/refined-github/refined-github/pull/3/files

**Comment by fregante** [comment] 2024-07-05 10:02
Duplicate of https://github.com/refined-github/refined-github/pull/1085

**Closed** 2024-07-05 10:02 UTC
Labels: enhancement, under discussion
