### ISSUE TITLE
`rgh-feature-descriptions` hides first line if feature is disabled 

### ISSUE THREAD

**Issue by rm-steele** [refined-github/refined-github#7765] opened 2024-08-28 12:16 UTC
### Description

When I visit the source code for a disabled feature, the box notifying me it's disabled covers about half of the first line. Applies to both automatically and manually disabled features.
![checkboxes](https://github.com/user-attachments/assets/6954bc33-4675-4db2-b185-4cbe2b7d0bdb)
![example1](https://github.com/user-attachments/assets/0cedb068-3a03-455f-b929-85fa9878549b)
![example2](https://github.com/user-attachments/assets/0ecbbd88-7a9c-4f35-a69b-41cd94d16eed)
![example3](https://github.com/user-attachments/assets/15c882e5-f145-46ec-a40c-a7d06f7edd20)

### How to replicate the issue + URL

1. Disable a feature if none are disabled
2. In the extension settings, find a disabled feature and click the "source" link
3. Wait for the yellow "This feature is disabled" text box to load

As of writing, the easiest place to view the issue would be the [table input source code](https://github.com/refined-github/refined-github/blob/main/source/features/table-input.tsx), because it's forced off.

### Extension version

24.8.26.1

### Browser(s) used

Mozilla Firefox 129.0

### Token ⚠️

- [X] I set a token in the options page. I understand that some features require a token to work.

**Comment by fregante** [comment] 2024-08-28 13:19
Thanks! We had this same exact issue before, but I don’t remember which feature caused it. I think the yellow bar needs to change container/parent

**Comment by fregante** [comment] 2024-08-29 06:38
Duplicate of https://github.com/refined-github/refined-github/issues/6337

**Closed** 2024-08-29 07:21 UTC
Labels: bug, help wanted, small
