### ISSUE TITLE
Migrating to Manifest V3

### ISSUE THREAD

**Issue by kidonng** [refined-github/refined-github#5531] opened 2022-03-22 01:55 UTC
### Description

I don't think we mentioned this anywhere so here we are. Nothing to hurry, just in case we don't forget it.

[Manifest V2 will be gone next year](https://developer.chrome.com/docs/extensions/mv3/mv2-sunset/), and we don't want Refined GitHub to stop evolving and rot in GitHub updates.

![](https://wd.imgix.net/image/SHhb2PDKzXTggPGAYpv8JgR81pX2/zXdU3hdkj1K0Ks6tAfB4.png)

_Hope we are not going through the 2to3 pain again like last time the world upgrades a certain reptile_

### Screenshot

![](https://i.imgflip.com/69izzk.jpg)

### Example URL

The universe

**Comment by fregante** [comment] 2022-03-22 02:28
A few things keeping us from updating:

- no Firefox support: https://bugzilla.mozilla.org/show_bug.cgi?id=1578284
- support for GHE isn't possible at the moment and it won't be until the figure out the `optional_permissions`:
	- https://github.com/w3c/webextensions/issues/119
	- https://github.com/fregante/webext-dynamic-content-scripts/issues/18
	- https://github.com/fregante/webext-domain-permission-toggle/issues/19

**Comment by Katsute** [comment] 2022-05-11 21:35
If you want to preserve some compatibility between Chrome and Firefox you could have a post build script that modifies the manifest version and produces two distributions: one for Chrome and one for Firefox.

https://github.com/Katsute/GitHub-Red-Issues/blob/3ff79d59722e1851508b5e6d87804a1d335de932/build.ts#L35-L45

The optional perm issue might only be solvable with a separate GHE distribution that requires the perm if they don't added it to MV3.

**Comment by fregante** [comment] 2022-05-12 15:17
I fully expect both issues to be resolved by January 2023, we really don't need to update _now_. If the deadline is near and issues persist, we'll figure something out then.

**Comment by FloEdelmann** [comment] 2022-05-19 10:20
FYI: https://blog.mozilla.org/addons/2022/05/18/manifest-v3-in-firefox-recap-next-steps/

**Comment by fregante** [comment] 2022-05-20 04:19
Let's not waste time debugging their stuff just yet, we'll do it in 5-6 months. 👍 

Support for GHE is completely missing in Chrome MV3 so Firefox is not the only reason to wait.

**Comment by fregante** [comment] 2022-09-30 10:41
It's probably time to start testing. We can convert the extension to use MV3 and then call a MV3-to-MV2 script here:

- in package.json as `mv2-conversion`
- https://github.com/refined-github/refined-github/blob/5e17c86770cc63a86e1dde6d5951d2d90a3ea013/.github/workflows/release.yml#L72
- in ci.yml, just to ensure it runs

**Comment by fregante** [comment] 2023-05-31 06:25
I somehow missed this!

> Manifest V3 became generally available in Firefox 109 (January 2023)

**Comment by delucis** [comment] 2023-05-31 06:47
I was looking at this a couple of months ago and I think there's still some compatibility quirks: Chrome moved to service workers for persistent background scripts but Firefox haven't implemented that — https://extensionworkshop.com/documentation/develop/manifest-v3-migration-guide/

It may be possible to use the same script and switch the manifest config to use v3 in Chrome, v2 in Firefox though.

**Comment by fregante** [comment] 2023-05-31 07:58
Thanks for the comment!

> switch the manifest config to use v3 in Chrome, v2 in Firefox

We could have done that years ago but avoided the complexity of 2 builds.

> Chrome moved to service workers for persistent background scripts but Firefox haven't

Ugh, that's right, so we'll keep waiting:

- https://bugzilla.mozilla.org/show_bug.cgi?id=1573659

**Comment by fregante** [comment] 2023-05-31 11:46
This might come a little earlier than expected IF Chrome manages to ship a schema change:

- https://github.com/w3c/webextensions/issues/282#issuecomment-1525220582

In short we will be able to ship MV3 with a single manifest.json: and Firefox will continue using the current background script, while Chrome and Safari use the worker. 

The issue is that Chrome is currently rejecting the `script` property entirely so we’re blocked until they allow it (which is planned/accepted, but not yet shipped):

- https://bugs.chromium.org/p/chromium/issues/detail?id=1418934

**Comment by FloEdelmann** [comment] 2023-05-31 15:11
> I don’t think we have many Firefox-based contributors

At least I am :wink: 
Upvote this comment if you are, too.

**Comment by fregante** [comment] 2023-05-31 15:29
@FloEdelmann time to switch to Edge then 😃

**Comment by delucis** [comment] 2023-05-31 22:07
I have the inverse set-up on an extension I maintaint and do this to convert my Manifest v2, Firefox-compatible config to a v3 Chrome manifest: https://github.com/delucis/github-to-linear/blob/12ce5ab43ea9d257cb04c3715d95a51551a30bf0/scripts/build.mjs#L11-L18

So yeah, do-able but like you say makes local dev annoying for whichever browser you’re not defaulting to. That schema change would be super helpful, assuming FF isn’t implementing service workers any time soon.

**Comment by fregante** [comment] 2023-09-18 13:43
No. I don’t think there's a lot to do here, the dependencies should already be compatible. We're essentially waiting for Firefox to implement Service Workers, or for Chrome to *not* throw errors if it finds background.script in a MV3 manifest.

**Comment by markphip** [comment] 2023-09-18 13:49
> No. I don’t think there's a lot to do here, the dependencies should already be compatible. We're essentially waiting for Firefox to implement Service Workers, or for Chrome to _not_ throw errors if it finds background.script in a MV3 manifest.

What does it require to try it out locally (for Chrome)? I am assuming it requires a bit more than just changing the version to 3 in the manifest and removing the reference to the background script.

**Comment by fregante** [comment] 2023-09-18 13:51
> What does it require to try it out locally (for Chrome)?

Feel free to open a PR when you find out, there's a migration document from the Chrome team.

**Closed** 2024-06-21 09:04 UTC
Labels: help wanted, meta

**Comment by jerone** [comment] 2024-06-22 08:52
In Firefox, the RGH options page moved in the latest update. 
Is that an consequence of Manifest V3?
![image](https://github.com/refined-github/refined-github/assets/55841/2d962088-f781-477a-8602-5cca7cbef94d)

Also changelog is not visible.

**Comment by jerone** [comment] 2024-06-22 09:10
> In Firefox (127.0.1), the RGH options page moved in the latest update.

Ah, nvm; #7465
