### ISSUE TITLE
`Delete fork` button appears repeatedly after click one of the Actions workflow

### ISSUE THREAD

**Issue by Howard20181** [refined-github/refined-github#5917] opened 2022-08-18 16:30 UTC
### Description

When clicking one of the workflow and then clicking another tabs, the `Delete fork` button appears repeatedly
![image](https://user-images.githubusercontent.com/40033067/185446716-6f529bb4-7d41-4df3-84ec-0d6cc34da13c.png)

### How to replicate the issue

https://user-images.githubusercontent.com/40033067/185447802-1259e346-3b8c-4704-8ead-2d58f29c493d.mp4

### Extension version

22.8.8

### Browser(s) used

Microsoft Edge	104.0.1293.54

**Comment by fregante** [comment] 2022-08-18 16:38
There's an open issue for this behavior, but let's keep this open so we know which features are broken exactly.

**Comment by cheap-glitch** [comment] 2022-08-25 09:22
This may have been fixed in `22.8.23` because I can't reproduce it on Firefox.

**Comment by fregante** [comment] 2022-08-25 09:59
https://github.com/refined-github/refined-github/pull/5907 touched the feature, so that's likely

**Closed by fregante** 2022-08-25 09:59 UTC
Labels: bug, help wanted, good first issue, Please! ♥︎
