### ISSUE TITLE
`bypass-checks` messes up "Details" link for a custom action check

### ISSUE THREAD

**Issue by dzenanz** [refined-github/refined-github#5088] opened 2021-11-19 19:24 UTC
### Please ensure:

- [X] The bug is caused by Refined GitHub. It doesn't happen if I disable the extension.

### Include in this issue:

- [ ] Screenshots/video/gif demonstrating the bug, if it’s visual
- [ ] Console errors, if any

### Description

`ghostflow-check-master` custom GitHub action check has a **Details** link which points to a page with some diagnostic/error messages produced by that check when running on the PR in question. With the extension enabled, that link always points to [the same link as the check's logo](https://github.com/apps/kwrobot-v1).

List of checks are at the bottom of the example URL, hidden under button `View details`.

### Example URL

https://github.com/InsightSoftwareConsortium/ITK/pull/2881

### Browser(s) used

Google Chrome Version 95.0.4638.69 (Official Build) (64-bit)

**Comment by cheap-glitch** [comment] 2021-11-19 20:54
Bisect points to `bypass-checks` being the culprit.

**Comment by fregante** [comment] 2021-11-19 22:00
Duplicate of https://github.com/refined-github/refined-github/issues/3938

**Closed by fregante** 2021-11-19 22:00 UTC
Labels: bug
