### ISSUE TITLE
`rgh-feature-descriptions` only works when opened in a new page

### ISSUE THREAD

**Issue by kidonng** [refined-github/refined-github#6528] opened 2023-04-15 14:58 UTC
### Description

Navigate to the following file (e.g. via Go to file) vs opening it in a new tab, `rgh-feature-descriptions` only works for the latter

### How to replicate the issue + URL

https://github.com/refined-github/refined-github/blob/main/source/features/linkify-code.tsx

### Extension version

23.4.10

### Browser(s) used

Chrome

**Comment by kidonng** [comment] 2023-04-15 15:06
😅 Well this is probably the AJAX related one

`download-file-button` is also missing sometimes

**Comment by fregante** [comment] 2023-04-15 15:06
I think you're using the sidebar to change files, which basically isn't supported by our `turbo:` event listener, for which we already have an issue open.

**Comment by fregante** [comment] 2023-05-21 17:48
Duplicate of https://github.com/refined-github/refined-github/issues/6554

**Closed by fregante** 2023-05-21 17:48 UTC
Labels: bug, help wanted, ajax
