### ISSUE TITLE
Ability to mark renamed, unmodified files as "viewed" in bulk

### ISSUE THREAD

**Issue by seanf** [refined-github/refined-github#7721] opened 2024-08-22 04:15 UTC
### Description

For pull requests with a lot of renamed files (eg a bulk JavaScript to TypeScript conversion), it would be nice if there were an easy way to skip over the simple renames marked `File renamed without changes.` by marking them as "Viewed".

<img width="996" alt="image" src="https://github.com/user-attachments/assets/849c1b8e-2020-4ba7-89e6-9cd99fe695b4">

### Example URLs

https://github.com/refined-github/refined-github/pull/7238/files?w=1#diff-8abad52debf84e1fe3716fa4fef643fa41d9e84af8a5ae72cdadfc579d0a79d6

**Comment by fregante** [comment] 2024-08-22 04:59
Duplicate of https://github.com/refined-github/refined-github/issues/3045

**Closed** 2024-10-12 10:18 UTC
Labels: enhancement, under discussion
