### ISSUE TITLE
GitHub Releases appears multiple times on some repositories.

### ISSUE THREAD

**Issue by JaydenDev** [refined-github/refined-github#5759] opened 2022-06-30 16:59 UTC
### Please ensure:

- [X] The bug is caused by Refined GitHub. It doesn't happen if I disable the extension.
- [X] The bug happens after clearing extension cache. The "Clear cache" button below can also be found at the bottom of the options page.

### Example URLs

https://github.com/JaydenDev/Catalyst

### Extension version

22.6.25

### Browser(s) used

Firefox 101.0

### Description

Basically, go to the example link in examples. It's my Catalyst web browser repository, there you will find GitHub Releases being shown 3 times on the page. One on the right panel, twice on the top.

Highlighted areas are instances of this bug.
![Group 1](https://user-images.githubusercontent.com/92550746/176735130-4942ef10-16a8-4e62-9a5c-aebd73913b55.png)

### Include in this issue:

- [X] Screenshots/video/gif demonstrating the bug, if it’s visual
- [ ] Console errors, if any

**Comment by yakov116** [comment] 2022-06-30 17:00
Duplicate of #5738

**Closed by yakov116** 2022-06-30 17:00 UTC
Labels: bug
