### ISSUE TITLE
support displaying lines of code

### ISSUE THREAD

**Issue by fawaf** [refined-github/refined-github#5445] opened 2022-03-02 03:12 UTC
### Description

similar to https://github.com/kas-elvirov/gloc

can appear in either repo list (e.g. https://github.com/kas-elvirov) or in repo itself

### Example URL

https://github.com/kas-elvirov/gloc

**Comment by fregante** [comment] 2022-03-02 05:38
Duplicate of https://github.com/refined-github/refined-github/issues/5256

**Closed by fregante** 2022-03-02 05:38 UTC
Labels: enhancement, under discussion
