### ISSUE TITLE
Overlap when search menu is open

### ISSUE THREAD

**Issue by LAPCoder** [refined-github/refined-github#6225] opened 2023-01-14 08:44 UTC
### Description

With Refined GitHub:

![image](https://user-images.githubusercontent.com/97749743/212463568-0bbd5dd8-af06-4e5f-98b8-32003b72b7d0.png)

The sidebar has a problem.

Without Refined GitHub:

![image](https://user-images.githubusercontent.com/97749743/212463691-df5e416c-3851-44da-b98c-9222df4f1610.png)

### How to replicate the issue + URL

The bug appear on every repository like [SnabbGET repo](https://github.com/SnabbGET/SnabbGET) (for the images), Refined GitHub repo or Linux repo.

I have [GitHub code search](https://github.com/features/code-search).

### Extension version

22.12.15

### Browser(s) used

Firefox 108.0.2

**Comment by fregante** [comment] 2023-01-14 10:51
Duplicate of https://github.com/refined-github/refined-github/issues/6151

**Closed by fregante** 2023-01-14 10:51 UTC
Labels: bug
