### ISSUE TITLE
`conversation-filters` shows the wrong "current filter" checkbox

### ISSUE THREAD

**Issue by fregante** [refined-github/refined-github#4589] opened 2021-07-20 06:00 UTC
### Please ensure:

- [X] The bug is caused by Refined GitHub. It doesn't happen if I disable the extension.

### Describe the problem and how to replicate it

"Everything mentioning you" is cloned as a whole and the checkbox is preserved, but it shouldn't be

### Screenshots/video/gif showing the issue, if it’s visual

<img width="345" alt="Screen Shot" src="https://user-images.githubusercontent.com/1402241/126269218-3bb1ec09-4d5b-4fe4-885a-dbdc23134aa3.png">

### Example URL

```js
// https://github.com/sindresorhus/refined-github/issues?q=is%3Aopen+mentions%3A%40me
```

### Browser(s) used

safari

**Comment by cheap-glitch** [comment] 2021-07-20 09:01
Can't reproduce on Firefox 90.0

**Comment by yakov116** [comment] 2021-07-20 11:45
@cheap-glitch click `everything assigned to you`, then click `everything mentioning you`

**Closed** 2021-11-23 09:31 UTC
Labels: bug, help wanted
